// ─── 全量 POI 数据（~225个商家/景点，覆盖北京120+上海100+）────────────
// 每个 POI 的 images 数组：[外景, 内景/产品, 特写, 氛围]
// 命名规则: images/stores/{slug}-{1..4}.jpg

const ALL_PLACES = {

// ═══════════════════════════════════════════════════════════════
// 北京 — 展览 / 文化
// ═══════════════════════════════════════════════════════════════
'城东微展厅':{id:'p-chenxi',name:'城东微展厅 · 当代城市影像',short:'城东微展厅',category:'展览',rating:4.7,review_count:1284,avg_price:30,opening_hours:'10:00 - 19:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['出片好看','适合拍照','人不多','安静'],risk_tags:['闭馆较早'],recommendation_reason:'离地铁口8分钟，展厅不大，出片好看不挤，逛完正好饭点。',lng:116.4600,lat:39.9325,images:['images/stores/chenxi-exhibition-1.jpg','images/stores/chenxi-exhibition-2.jpg','images/stores/chenxi-exhibition-3.jpg','images/stores/chenxi-exhibition-4.jpg'],address:'朝阳区团结湖北路3号',mock_x:28,mock_y:22},
'798 街区漫步':{id:'p-798',name:'798 艺术街区',short:'798 街区漫步',category:'街区 / 展览',rating:4.6,review_count:5620,avg_price:0,opening_hours:'全天开放',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['出片好看','网红打卡','艺术氛围','逛逛走走'],risk_tags:['下午光线最好'],recommendation_reason:'几百个画廊和艺术空间，随手拍都是大片，适合慢慢逛。',lng:116.4950,lat:39.9840,images:['images/stores/798-art-district-1.jpg','images/stores/798-art-district-2.jpg','images/stores/798-art-district-3.jpg','images/stores/798-art-district-4.jpg'],address:'朝阳区酒仙桥路4号',mock_x:55,mock_y:12},
'城西胶片小展':{id:'p-westfilm',name:'城西胶片小展',short:'城西胶片小展',category:'展览',rating:4.5,review_count:876,avg_price:45,opening_hours:'10:00 - 18:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['出片好看','文艺','安静'],risk_tags:['周一闭馆'],recommendation_reason:'小众胶片摄影展，光线柔和，适合安静约会。',lng:116.3200,lat:39.9100,images:['images/stores/west-film-exhibition-1.jpg','images/stores/west-film-exhibition-2.jpg','images/stores/west-film-exhibition-3.jpg','images/stores/west-film-exhibition-4.jpg'],address:'海淀区中关村大街42号',mock_x:35,mock_y:25},
'城市互动展':{id:'p-cityex',name:'城市互动科技展',short:'城市互动展',category:'展览',rating:4.7,review_count:2103,avg_price:80,opening_hours:'09:30 - 17:30',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'需提前预约',tags:['互动体验','亲子友好','科技感'],risk_tags:['需提前预约','记得带身份证'],recommendation_reason:'沉浸式互动展览，孩子能专注玩2小时以上。',lng:116.4700,lat:39.9200,images:['images/stores/city-interactive-exhibition-1.jpg','images/stores/city-interactive-exhibition-2.jpg','images/stores/city-interactive-exhibition-3.jpg','images/stores/city-interactive-exhibition-4.jpg'],address:'朝阳区光华路9号',mock_x:60,mock_y:40},

// ═══════════════════════════════════════════════════════════════
// 北京 — 书店 / 阅读
// ═══════════════════════════════════════════════════════════════
'隔壁书店咖啡角':{id:'p-gebi',name:'隔壁书店 · 咖啡角',short:'隔壁书店咖啡角',category:'书店 / 咖啡',rating:4.5,review_count:678,avg_price:30,opening_hours:'10:00 - 21:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['安静','可以看书','人少'],risk_tags:['21:00关门'],recommendation_reason:'藏在居民区里的小书店，有座不吵，可以打发一整个下午。',lng:116.4500,lat:39.9290,images:['images/stores/gebi-bookstore-cafe-1.jpg','images/stores/gebi-bookstore-cafe-2.jpg','images/stores/gebi-bookstore-cafe-3.jpg','images/stores/gebi-bookstore-cafe-4.jpg'],address:'朝阳区团结湖北二条6号',mock_x:75,mock_y:75},
'河边书店咖啡':{id:'p-riverside',name:'河边书店 · 咖啡',short:'河边书店咖啡',category:'书店 / 咖啡',rating:4.6,review_count:892,avg_price:35,opening_hours:'09:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['安静','河边风景','适合拍照','约会'],risk_tags:[],recommendation_reason:'坐在河边看书喝咖啡，慢节奏约会的理想场景。',lng:116.3850,lat:39.9150,images:['images/stores/riverside-bookstore-cafe-1.jpg','images/stores/riverside-bookstore-cafe-2.jpg','images/stores/riverside-bookstore-cafe-3.jpg','images/stores/riverside-bookstore-cafe-4.jpg'],address:'东城区安定门内大街35号',mock_x:40,mock_y:80},
'小院图书馆':{id:'p-xiaoyuan',name:'小院图书馆',short:'小院图书馆',category:'书店',rating:4.6,review_count:765,avg_price:25,opening_hours:'10:00 - 20:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['安静','有院子','可久坐','文艺'],risk_tags:['周末人略多'],recommendation_reason:'藏在胡同里，有院子和猫，可以坐一下午。',lng:116.4050,lat:39.9380,images:['images/stores/xiaoyuan-library-1.jpg','images/stores/xiaoyuan-library-2.jpg','images/stores/xiaoyuan-library-3.jpg','images/stores/xiaoyuan-library-4.jpg'],address:'东城区北锣鼓巷61号',mock_x:20,mock_y:42},
'迷你绘本角':{id:'p-minibook',name:'迷你绘本角',short:'迷你绘本角',category:'书店',rating:4.5,review_count:432,avg_price:30,opening_hours:'09:30 - 19:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['亲子友好','有绘本','安静','有儿童区'],risk_tags:[],recommendation_reason:'有几百本绘本，孩子能安静翻半小时，家长也能歇口气。',lng:116.4750,lat:39.9300,images:['images/stores/mini-book-corner-1.jpg','images/stores/mini-book-corner-2.jpg','images/stores/mini-book-corner-3.jpg','images/stores/mini-book-corner-4.jpg'],address:'朝阳区光华路甲8号',mock_x:72,mock_y:48},
'社区图书馆门厅':{id:'p-librarylobby',name:'社区图书馆门厅',short:'社区图书馆门厅',category:'公共空间',rating:4.3,review_count:234,avg_price:0,opening_hours:'09:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['免费','安静','有座'],risk_tags:[],recommendation_reason:'绝对安静，适合等人、讲重要的事，免费有座。',lng:116.4150,lat:39.9100,images:['images/stores/library-lobby-1.jpg','images/stores/library-lobby-2.jpg','images/stores/library-lobby-3.jpg','images/stores/library-lobby-4.jpg'],address:'东城区东四南大街15号',mock_x:45,mock_y:65},
'PageOne 书店':{id:'p-pageone',name:'PageOne 书店（前门店）',short:'PageOne 书店',category:'书店',rating:4.7,review_count:2300,avg_price:35,opening_hours:'10:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['设计感','安静','可久坐','拍照好看'],risk_tags:[],recommendation_reason:'三层空间，二楼看正阳门，设计类图书最全。',lng:116.3980,lat:39.8990,images:['images/stores/pageone-bookstore-1.jpg','images/stores/pageone-bookstore-2.jpg','images/stores/pageone-bookstore-3.jpg','images/stores/pageone-bookstore-4.jpg'],address:'西城区前门北京坊东区E1楼',mock_x:22,mock_y:65},
'三联韬奋书店':{id:'p-sanlian',name:'三联韬奋书店（24小时）',short:'三联韬奋书店',category:'书店',rating:4.6,review_count:3200,avg_price:30,opening_hours:'24小时',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['24小时','安静','深夜可去','文化地标'],risk_tags:[],recommendation_reason:'北京文化地标，深夜无处可去时的精神避难所。',lng:116.4100,lat:39.9325,images:['images/stores/sanlian-bookstore-1.jpg','images/stores/sanlian-bookstore-2.jpg','images/stores/sanlian-bookstore-3.jpg','images/stores/sanlian-bookstore-4.jpg'],address:'东城区美术馆东街22号',mock_x:40,mock_y:35},

// ═══════════════════════════════════════════════════════════════
// 北京 — 博物馆 / 美术馆
// ═══════════════════════════════════════════════════════════════
'故宫博物院':{id:'p-gugong',name:'故宫博物院',short:'故宫博物院',category:'博物馆',rating:4.8,review_count:98000,avg_price:60,opening_hours:'08:30 - 17:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'amber',wait_time:'旺季排队约30分钟',tags:['世界遗产','必去','历史','宏伟'],risk_tags:['需提前预约','周一闭馆'],recommendation_reason:'世界五大宫之首，建议预留至少半天，旺季门票需提前一周预约。',lng:116.3970,lat:39.9160,images:['images/stores/forbidden-city-1.jpg','images/stores/forbidden-city-2.jpg','images/stores/forbidden-city-3.jpg','images/stores/forbidden-city-4.jpg'],address:'东城区景山前街4号',mock_x:42,mock_y:32},
'国家博物馆':{id:'p-guobo',name:'中国国家博物馆',short:'国家博物馆',category:'博物馆',rating:4.7,review_count:45000,avg_price:0,opening_hours:'09:00 - 17:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'amber',wait_time:'需预约，排队约20分钟',tags:['免费','国宝','历史','需预约'],risk_tags:['需提前预约','周一闭馆'],recommendation_reason:'中华文明五千年，镇馆之宝数不过来，建议逛3小时以上。',lng:116.4010,lat:39.9050,images:['images/stores/national-museum-1.jpg','images/stores/national-museum-2.jpg','images/stores/national-museum-3.jpg','images/stores/national-museum-4.jpg'],address:'东城区东长安街16号',mock_x:43,mock_y:38},
'中国美术馆':{id:'p-artmuseum',name:'中国美术馆',short:'中国美术馆',category:'美术馆',rating:4.5,review_count:5600,avg_price:0,opening_hours:'09:00 - 17:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'需预约',tags:['免费','艺术','美术','展览'],risk_tags:['周一闭馆'],recommendation_reason:'国家级美术殿堂，经常有重磅特展，免费但需预约。',lng:116.4080,lat:39.9250,images:['images/stores/national-art-museum-1.jpg','images/stores/national-art-museum-2.jpg','images/stores/national-art-museum-3.jpg','images/stores/national-art-museum-4.jpg'],address:'东城区五四大街1号',mock_x:42,mock_y:28},
'红砖美术馆':{id:'p-redbrick',name:'红砖美术馆',short:'红砖美术馆',category:'美术馆',rating:4.6,review_count:3400,avg_price:80,opening_hours:'10:00 - 18:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['出片好看','建筑美学','安静','文艺'],risk_tags:['周一闭馆'],recommendation_reason:'红砖建筑本身就是艺术品，园林+展览一步一景，拍照圣地。',lng:116.4900,lat:40.0200,images:['images/stores/redbrick-museum-1.jpg','images/stores/redbrick-museum-2.jpg','images/stores/redbrick-museum-3.jpg','images/stores/redbrick-museum-4.jpg'],address:'朝阳区崔各庄乡何各庄村',mock_x:60,mock_y:5},
'UCCA':{id:'p-ullens',name:'UCCA 尤伦斯当代艺术中心',short:'UCCA',category:'美术馆',rating:4.5,review_count:2800,avg_price:100,opening_hours:'10:00 - 19:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['当代艺术','国际展览','798核心'],risk_tags:[],recommendation_reason:'798最核心的艺术机构，国际级当代艺术展水准极高。',lng:116.4940,lat:39.9830,images:['images/stores/ucca-1.jpg','images/stores/ucca-2.jpg','images/stores/ucca-3.jpg','images/stores/ucca-4.jpg'],address:'朝阳区酒仙桥路4号798艺术区',mock_x:65,mock_y:10},
'天坛公园':{id:'p-titan',name:'天坛公园',short:'天坛公园',category:'景点',rating:4.7,review_count:52000,avg_price:15,opening_hours:'06:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['世界遗产','古建筑','公园','晨练'],risk_tags:[],recommendation_reason:'祈年殿+回音壁，北京的灵魂在这里，建议早上去看大爷大妈晨练。',lng:116.4100,lat:39.8820,images:['images/stores/temple-of-heaven-1.jpg','images/stores/temple-of-heaven-2.jpg','images/stores/temple-of-heaven-3.jpg','images/stores/temple-of-heaven-4.jpg'],address:'东城区天坛内东里7号',mock_x:44,mock_y:73},

// ═══════════════════════════════════════════════════════════════
// 北京 — 更多文化（科技馆/图书馆/胡同博物馆）
// ═══════════════════════════════════════════════════════════════
'中国科学技术馆':{id:'p-scitech',name:'中国科学技术馆',short:'中国科学技术馆',category:'科技馆',rating:4.7,review_count:15000,avg_price:30,opening_hours:'09:30 - 17:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'amber',wait_time:'周末排队约15分钟',tags:['亲子','科学','互动','趣味'],risk_tags:['周一闭馆'],recommendation_reason:'孩子去了不想走，科学乐园能玩一整天，大人也能学到很多。',lng:116.3930,lat:39.9980,images:['images/stores/scitech-museum-1.jpg','images/stores/scitech-museum-2.jpg','images/stores/scitech-museum-3.jpg','images/stores/scitech-museum-4.jpg'],address:'朝阳区北辰东路5号',mock_x:38,mock_y:3},
'中国电影博物馆':{id:'p-filmmuseum',name:'中国电影博物馆',short:'中国电影博物馆',category:'博物馆',rating:4.5,review_count:3200,avg_price:0,opening_hours:'09:00 - 17:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['电影','免费','IMAX','历史'],risk_tags:['周一闭馆'],recommendation_reason:'世界最大的电影博物馆，IMAX GT激光厅看电影超震撼。',lng:116.5100,lat:40.0000,images:['images/stores/film-museum-1.jpg','images/stores/film-museum-2.jpg','images/stores/film-museum-3.jpg','images/stores/film-museum-4.jpg'],address:'朝阳区南影路9号',mock_x:72,mock_y:5},
'中国国家图书馆':{id:'p-nationallib',name:'中国国家图书馆',short:'中国国家图书馆',category:'图书馆',rating:4.6,review_count:4500,avg_price:0,opening_hours:'09:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['学习','安静','免费','建筑美学'],risk_tags:[],recommendation_reason:'亚洲最大图书馆，在知识的海洋里安静度过一天。',lng:116.3260,lat:39.9460,images:['images/stores/national-library-1.jpg','images/stores/national-library-2.jpg','images/stores/national-library-3.jpg','images/stores/national-library-4.jpg'],address:'海淀区中关村南大街33号',mock_x:18,mock_y:18},
'东四胡同博物馆':{id:'p-dongshan',name:'东四胡同博物馆',short:'东四胡同博物馆',category:'博物馆',rating:4.4,review_count:560,avg_price:0,opening_hours:'09:00 - 17:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['胡同文化','免费','四合院','安静'],risk_tags:[],recommendation_reason:'免费的四合院博物馆，三进院落讲北京胡同的前世今生。',lng:116.4200,lat:39.9280,images:['images/stores/dongsi-museum-1.jpg','images/stores/dongsi-museum-2.jpg','images/stores/dongsi-museum-3.jpg','images/stores/dongsi-museum-4.jpg'],address:'东城区东四四条77号',mock_x:45,mock_y:25},

// ═══════════════════════════════════════════════════════════════
// 北京 — 餐厅：烤肉 / 火锅
// ═══════════════════════════════════════════════════════════════
'山野炭火烤肉':{id:'p-shanye',name:'山野炭火烤肉（团结湖店）',short:'山野炭火烤肉',category:'烤肉',rating:4.6,review_count:3412,avg_price:95,opening_hours:'11:30 - 22:30',current_status:'当前营业中 · 预计等位15分钟',current_status_short:'等位约15分',status_tone:'amber',wait_time:'约15分钟',tags:['适合朋友聚会','分量足','离地铁近','适合聊天','服务好'],risk_tags:['晚高峰可能等位','环境偏热闹'],recommendation_reason:'人均95，靠近地铁口，分量足、适合一群人吃，已预留取号时间。',lng:116.4655,lat:39.9270,images:['images/stores/shanye-kaorou-1.jpg','images/stores/shanye-kaorou-2.jpg','images/stores/shanye-kaorou-3.jpg','images/stores/shanye-kaorou-4.jpg'],address:'朝阳区团结湖南路12号',mock_x:52,mock_y:60},
'聚宝源涮肉':{id:'p-jubaoyuan',name:'聚宝源涮肉（牛街总店）',short:'聚宝源涮肉',category:'火锅',rating:4.8,review_count:8700,avg_price:110,opening_hours:'11:00 - 22:00',current_status:'当前营业中 · 预计等位40分钟',current_status_short:'等位约40分钟',status_tone:'amber',wait_time:'约40分钟',tags:['排队王','老北京涮肉','清真','手切羊肉'],risk_tags:['排队时间极长','建议错峰'],recommendation_reason:'北京涮肉天花板，手切鲜羊肉必点，排队是真排但值得。',lng:116.3630,lat:39.8880,images:['images/stores/jubaoyuan-hotpot-1.jpg','images/stores/jubaoyuan-hotpot-2.jpg','images/stores/jubaoyuan-hotpot-3.jpg','images/stores/jubaoyuan-hotpot-4.jpg'],address:'西城区牛街西里商业1号楼',mock_x:8,mock_y:68},
'海底捞火锅（三里屯）':{id:'p-haidilao',name:'海底捞火锅（三里屯店）',short:'海底捞火锅（三里屯）',category:'火锅',rating:4.5,review_count:12000,avg_price:130,opening_hours:'10:00 - 07:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'等位约25分钟',tags:['服务好','深夜营业','等位有零食','聚会首选'],risk_tags:['餐期排队较久'],recommendation_reason:'凌晨三点想吃火锅？海底捞等你，服务永远在线。',lng:116.4550,lat:39.9340,images:['images/stores/haidilao-1.jpg','images/stores/haidilao-2.jpg','images/stores/haidilao-3.jpg','images/stores/haidilao-4.jpg'],address:'朝阳区三里屯太古里南区B1',mock_x:52,mock_y:38},
'官也街澳门火锅':{id:'p-guanyejie',name:'官也街澳门火锅',short:'官也街澳门火锅',category:'火锅',rating:4.6,review_count:2300,avg_price:250,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['澳门风味','汤底鲜美','海鲜','约会'],risk_tags:[],recommendation_reason:'猪骨鸡脚汤底，涮菜前先喝三碗汤，鲜掉眉毛。',lng:116.4430,lat:39.9180,images:['images/stores/guanyejie-hotpot-1.jpg','images/stores/guanyejie-hotpot-2.jpg','images/stores/guanyejie-hotpot-3.jpg','images/stores/guanyejie-hotpot-4.jpg'],address:'朝阳区建国门外大街甲1号',mock_x:50,mock_y:45},
'老坑记打边炉':{id:'p-laokeng',name:'老坑记港式打边炉',short:'老坑记打边炉',category:'火锅',rating:4.4,review_count:1800,avg_price:160,opening_hours:'17:00 - 02:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约15分钟',tags:['港式','深夜食堂','花胶鸡','聚会'],risk_tags:['晚上才有'],recommendation_reason:'夜深了来一锅花胶鸡，汤浓料足，暖到心底。',lng:116.4350,lat:39.9200,images:['images/stores/laokeng-hotpot-1.jpg','images/stores/laokeng-hotpot-2.jpg','images/stores/laokeng-hotpot-3.jpg','images/stores/laokeng-hotpot-4.jpg'],address:'朝阳区工体北路甲2号',mock_x:48,mock_y:42},
'聚宝源涮肉（望京店）':{id:'p-jubaoyuan2',name:'聚宝源涮肉（望京店）',short:'聚宝源涮肉（望京）',category:'火锅',rating:4.6,review_count:4300,avg_price:110,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'amber',wait_time:'约25分钟',tags:['涮肉','老北京','排队','聚会'],risk_tags:['餐期排队'],recommendation_reason:'聚宝源望京分店，排队没那么夸张但品质一样好。',lng:116.4800,lat:39.9950,images:['images/stores/jubaoyuan-hotpot-1.jpg','images/stores/jubaoyuan-hotpot-2.jpg','images/stores/jubaoyuan-hotpot-3.jpg','images/stores/jubaoyuan-hotpot-4.jpg'],address:'朝阳区望京街9号',mock_x:62,mock_y:10},
'南门涮肉（天坛店）':{id:'p-huoguo',name:'南门涮肉（天坛店）',short:'南门涮肉（天坛）',category:'火锅',rating:4.5,review_count:5600,avg_price:100,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'amber',wait_time:'约20分钟',tags:['老北京涮肉','铜锅','天坛','实惠'],risk_tags:[],recommendation_reason:'逛完天坛来吃铜锅涮肉，手切鲜羊肉配糖蒜，老北京的满足感。',lng:116.4120,lat:39.8820,images:['images/stores/nanmen-hotpot-1.jpg','images/stores/nanmen-hotpot-2.jpg','images/stores/nanmen-hotpot-3.jpg','images/stores/nanmen-hotpot-4.jpg'],address:'东城区天坛东路62号',mock_x:44,mock_y:73},

// ═══════════════════════════════════════════════════════════════
// 北京 — 烤鸭 / 北京菜
// ═══════════════════════════════════════════════════════════════
'四季民福烤鸭店（故宫店）':{id:'p-sijiminfu',name:'四季民福烤鸭店（故宫店）',short:'四季民福烤鸭店（故宫店）',category:'烤鸭',rating:4.7,review_count:12800,avg_price:150,opening_hours:'10:30 - 21:30',current_status:'当前营业中 · 预计等位50分钟',current_status_short:'等位约50分钟',status_tone:'amber',wait_time:'约50分钟',tags:['故宫景观位','排队王','烤鸭','约会'],risk_tags:['景观位极难排到','至少排1小时'],recommendation_reason:'故宫角楼旁吃烤鸭，景观位+半只烤鸭=北京最佳午餐。',lng:116.3990,lat:39.9140,images:['images/stores/sijiminfu-duck-1.jpg','images/stores/sijiminfu-duck-2.jpg','images/stores/sijiminfu-duck-3.jpg','images/stores/sijiminfu-duck-4.jpg'],address:'东城区南池子大街11号',mock_x:40,mock_y:36},
'大董烤鸭（工体店）':{id:'p-dadong',name:'大董烤鸭（工体店）',short:'大董烤鸭（工体店）',category:'烤鸭',rating:4.6,review_count:6700,avg_price:350,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约15分钟',tags:['高端烤鸭','创意菜','环境好','商务宴请'],risk_tags:['人均较高'],recommendation_reason:'意境菜开创者，酥不腻烤鸭配鱼子酱，商务局首选。',lng:116.4430,lat:39.9320,images:['images/stores/dadong-duck-1.jpg','images/stores/dadong-duck-2.jpg','images/stores/dadong-duck-3.jpg','images/stores/dadong-duck-4.jpg'],address:'朝阳区工人体育场东门',mock_x:50,mock_y:35},
'花家怡园（簋街店）':{id:'p-huajiayiyuan',name:'花家怡园（簋街店）',short:'花家怡园（簋街店）',category:'北京菜',rating:4.4,review_count:4500,avg_price:130,opening_hours:'11:00 - 23:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['北京菜','四合院','适合聚会','有包间'],risk_tags:[],recommendation_reason:'四合院里的北京菜，宫廷官府菜和市井小吃都有。',lng:116.4320,lat:39.9380,images:['images/stores/huajiayiyuan-1.jpg','images/stores/huajiayiyuan-2.jpg','images/stores/huajiayiyuan-3.jpg','images/stores/huajiayiyuan-4.jpg'],address:'东城区东直门内大街235号',mock_x:46,mock_y:32},
'那家小馆':{id:'p-najia',name:'那家小馆（酒仙桥店）',short:'那家小馆',category:'北京菜',rating:4.5,review_count:2300,avg_price:100,opening_hours:'11:00 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['北京菜','环境好','私房菜','安静'],risk_tags:[],recommendation_reason:'798逛完来这吃，古色古香的满族官府菜，秘制酥皮虾必点。',lng:116.4920,lat:39.9820,images:['images/stores/najia-xiaoguan-1.jpg','images/stores/najia-xiaoguan-2.jpg','images/stores/najia-xiaoguan-3.jpg','images/stores/najia-xiaoguan-4.jpg'],address:'朝阳区酒仙桥北路2号',mock_x:62,mock_y:12},

// ═══════════════════════════════════════════════════════════════
// 北京 — 川菜 / 粤菜 / 湘菜 / 东北菜 / 新疆菜 / 素食
// ═══════════════════════════════════════════════════════════════
'川办餐厅':{id:'p-chuanban',name:'川办餐厅',short:'川办餐厅',category:'川菜',rating:4.5,review_count:5600,avg_price:80,opening_hours:'11:00 - 21:00',current_status:'当前营业中 · 等位约30分钟',current_status_short:'等位约30分钟',status_tone:'amber',wait_time:'约30分钟',tags:['正宗川菜','实惠','排队','口水鸡'],risk_tags:['排队时间较长'],recommendation_reason:'驻京办里的顶流，口水鸡和毛血旺一绝，排队也值。',lng:116.4280,lat:39.9080,images:['images/stores/chuanban-restaurant-1.jpg','images/stores/chuanban-restaurant-2.jpg','images/stores/chuanban-restaurant-3.jpg','images/stores/chuanban-restaurant-4.jpg'],address:'东城区建国门内大街贡院西街头条5号',mock_x:48,mock_y:48},
'张妈妈川味馆':{id:'p-zhangmama',name:'张妈妈特色川味馆',short:'张妈妈川味馆',category:'川菜',rating:4.4,review_count:3400,avg_price:55,opening_hours:'11:00 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'amber',wait_time:'约20分钟',tags:['平价川菜','钵钵鸡','苍蝇馆子','辣'],risk_tags:['苍蝇馆子环境一般'],recommendation_reason:'平价川菜传奇，钵钵鸡和连山回锅肉，辣到过瘾。',lng:116.4200,lat:39.9350,images:['images/stores/zhangmama-sichuan-1.jpg','images/stores/zhangmama-sichuan-2.jpg','images/stores/zhangmama-sichuan-3.jpg','images/stores/zhangmama-sichuan-4.jpg'],address:'东城区安定门内大街分司厅胡同5号',mock_x:44,mock_y:30},
'金鼎轩（24小时）':{id:'p-jindingxuan',name:'金鼎轩（24小时）',short:'金鼎轩（24小时）',category:'粤菜',rating:4.3,review_count:8900,avg_price:90,opening_hours:'24小时',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['24小时','粤式点心','深夜可去','品种多'],risk_tags:[],recommendation_reason:'深夜想吃虾饺凤爪？24小时茶餐厅，凌晨三点也有热乎的。',lng:116.4350,lat:39.9420,images:['images/stores/jindingxuan-1.jpg','images/stores/jindingxuan-2.jpg','images/stores/jindingxuan-3.jpg','images/stores/jindingxuan-4.jpg'],address:'东城区东直门内大街15号',mock_x:46,mock_y:28},
'利苑酒家':{id:'p-liyuan',name:'利苑酒家（国贸店）',short:'利苑酒家',category:'粤菜',rating:4.6,review_count:2100,avg_price:400,opening_hours:'11:30 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['米其林','粤菜','商务','精致'],risk_tags:['人均较高'],recommendation_reason:'北京最好的粤菜之一，冰烧三层肉和杨枝甘露是标杆。',lng:116.4580,lat:39.9090,images:['images/stores/liyuan-cantonese-1.jpg','images/stores/liyuan-cantonese-2.jpg','images/stores/liyuan-cantonese-3.jpg','images/stores/liyuan-cantonese-4.jpg'],address:'朝阳区建国门外大街甲6号',mock_x:53,mock_y:48},
'乡村基湘菜馆':{id:'p-xiangcun',name:'乡村基湘菜馆',short:'乡村基湘菜馆',category:'湘菜',rating:4.3,review_count:1500,avg_price:65,opening_hours:'11:00 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['湘菜','辣','实惠','下饭'],risk_tags:[],recommendation_reason:'剁椒鱼头配米饭，辣得过瘾吃得痛快，湖南人在北京的食堂。',lng:116.4080,lat:39.9120,images:['images/stores/xiangcun-hunan-1.jpg','images/stores/xiangcun-hunan-2.jpg','images/stores/xiangcun-hunan-3.jpg','images/stores/xiangcun-hunan-4.jpg'],address:'东城区东四北大街145号',mock_x:42,mock_y:42},
'东北人家饺子馆':{id:'p-dongbeicai',name:'东北人家饺子馆',short:'东北人家饺子馆',category:'东北菜',rating:4.3,review_count:2300,avg_price:45,opening_hours:'10:00 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['东北菜','饺子','实惠','锅包肉'],risk_tags:[],recommendation_reason:'手工现包大馅饺子，锅包肉外酥里嫩，东北人的家乡味。',lng:116.4200,lat:39.9600,images:['images/stores/dongbei-dumpling-1.jpg','images/stores/dongbei-dumpling-2.jpg','images/stores/dongbei-dumpling-3.jpg','images/stores/dongbei-dumpling-4.jpg'],address:'海淀区学院南路55号',mock_x:42,mock_y:15},
'巴州办餐厅':{id:'p-xinjiang',name:'巴州办餐厅',short:'巴州办餐厅',category:'新疆菜',rating:4.4,review_count:1800,avg_price:90,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['新疆菜','大盘鸡','羊肉串','驻京办'],risk_tags:[],recommendation_reason:'新疆驻京办餐厅，大盘鸡和红柳烤羊肉串，肉食爱好者的天堂。',lng:116.3700,lat:39.9150,images:['images/stores/xinjiang-restaurant-1.jpg','images/stores/xinjiang-restaurant-2.jpg','images/stores/xinjiang-restaurant-3.jpg','images/stores/xinjiang-restaurant-4.jpg'],address:'海淀区中关村南大街32号',mock_x:30,mock_y:38},
'莲花空间素食':{id:'p-su vegetarian',name:'莲花空间素食',short:'莲花空间素食',category:'素食',rating:4.5,review_count:1200,avg_price:120,opening_hours:'11:00 - 21:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['素食','精致','安静','健康'],risk_tags:[],recommendation_reason:'精致素食料理，每道菜都像艺术品，吃完感觉身体都轻盈了。',lng:116.4180,lat:39.9250,images:['images/stores/lotus-vegetarian-1.jpg','images/stores/lotus-vegetarian-2.jpg','images/stores/lotus-vegetarian-3.jpg','images/stores/lotus-vegetarian-4.jpg'],address:'东城区雍和宫大街38号',mock_x:44,mock_y:32},
'淮扬府':{id:'p-huaiyang',name:'淮扬府',short:'淮扬府',category:'淮扬菜',rating:4.5,review_count:1600,avg_price:200,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约5分钟',tags:['淮扬菜','精致','文思豆腐','商务'],risk_tags:[],recommendation_reason:'大煮干丝、文思豆腐刀工了得，淮扬菜的清雅在北京也能吃到。',lng:116.4200,lat:39.9050,images:['images/stores/huaiyangfu-1.jpg','images/stores/huaiyangfu-2.jpg','images/stores/huaiyangfu-3.jpg','images/stores/huaiyangfu-4.jpg'],address:'东城区建国门内大街18号',mock_x:44,mock_y:48},
'鲜馔海鲜小馆':{id:'p-xiancun',name:'鲜馔 · 海鲜小馆',short:'鲜馔海鲜小馆',category:'海鲜',rating:4.4,review_count:2100,avg_price:160,opening_hours:'11:30 - 23:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['海鲜','新鲜','聚会','蒜蓉生蚝'],risk_tags:[],recommendation_reason:'每天空运到货，海鲜池现捞现做，蒜蓉生蚝一口气能嗦一打。',lng:116.4480,lat:39.9200,images:['images/stores/xiancun-seafood-1.jpg','images/stores/xiancun-seafood-2.jpg','images/stores/xiancun-seafood-3.jpg','images/stores/xiancun-seafood-4.jpg'],address:'朝阳区工体北路甲12号',mock_x:50,mock_y:42},
'韩馆烤肉':{id:'p-hanguan',name:'韩馆烤肉',short:'韩馆烤肉',category:'韩式烤肉',rating:4.4,review_count:3400,avg_price:110,opening_hours:'11:00 - 22:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'amber',wait_time:'约15分钟',tags:['韩式烤肉','五花肉','小菜多','望京'],risk_tags:[],recommendation_reason:'望京韩国城的正宗韩式烤肉，厚切五花肉烤到焦香，生菜包着吃绝了。',lng:116.4790,lat:39.9960,images:['images/stores/hanguan-kbbq-1.jpg','images/stores/hanguan-kbbq-2.jpg','images/stores/hanguan-kbbq-3.jpg','images/stores/hanguan-kbbq-4.jpg'],address:'朝阳区望京西园四区416号',mock_x:62,mock_y:8},
'素直素食':{id:'p-sushifu',name:'素直素食',short:'素直素食',category:'素食',rating:4.5,review_count:890,avg_price:90,opening_hours:'11:00 - 21:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['素食','轻食','健康','沙拉'],risk_tags:[],recommendation_reason:'CBD白领午餐救星，素食也能做得有滋有味，吃完身体零负担。',lng:116.4500,lat:39.9200,images:['images/stores/suzhi-vegetarian-1.jpg','images/stores/suzhi-vegetarian-2.jpg','images/stores/suzhi-vegetarian-3.jpg','images/stores/suzhi-vegetarian-4.jpg'],address:'朝阳区东大桥路8号SOHO尚都北塔1F',mock_x:52,mock_y:42},
'澳门味道':{id:'p-macau',name:'澳门味道',short:'澳门味道',category:'澳门菜',rating:4.3,review_count:1200,avg_price:90,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['澳门菜','猪扒包','葡挞','茶餐厅'],risk_tags:[],recommendation_reason:'正宗的澳门猪扒包和安德鲁葡挞，吃完像去了趟澳门。',lng:116.4300,lat:39.9120,images:['images/stores/macau-taste-1.jpg','images/stores/macau-taste-2.jpg','images/stores/macau-taste-3.jpg','images/stores/macau-taste-4.jpg'],address:'朝阳区工体北路甲15号',mock_x:48,mock_y:46},

// ═══════════════════════════════════════════════════════════════
// 北京 — 日料 / 云南菜 / 越南菜 / 小吃
// ═══════════════════════════════════════════════════════════════
'铃木食堂':{id:'p-lingmu',name:'铃木食堂（南锣鼓巷）',short:'铃木食堂',category:'日料',rating:4.5,review_count:3400,avg_price:80,opening_hours:'11:30 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'amber',wait_time:'约15分钟',tags:['日料','小院','安静','牛肉饭'],risk_tags:[],recommendation_reason:'胡同小院里的日式食堂，牛肉饭和杏仁豆腐是标配。',lng:116.4030,lat:39.9370,images:['images/stores/lingmu-shokudo-1.jpg','images/stores/lingmu-shokudo-2.jpg','images/stores/lingmu-shokudo-3.jpg','images/stores/lingmu-shokudo-4.jpg'],address:'东城区小菊儿胡同77号',mock_x:38,mock_y:30},
'望京小腰':{id:'p-wangjingxy',name:'望京小腰',short:'望京小腰',category:'烧烤',rating:4.4,review_count:4500,avg_price:80,opening_hours:'17:00 - 02:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'amber',wait_time:'约15分钟',tags:['烧烤','深夜','朋友聚会','路边摊'],risk_tags:['露天摊位','天冷慎去'],recommendation_reason:'望京传奇路边摊，一把小腰一把串，烟火气拉满。',lng:116.4780,lat:39.9970,images:['images/stores/wangjing-xiaoyao-1.jpg','images/stores/wangjing-xiaoyao-2.jpg','images/stores/wangjing-xiaoyao-3.jpg','images/stores/wangjing-xiaoyao-4.jpg'],address:'朝阳区望京西园四区420号',mock_x:62,mock_y:8},
'一坐一忘云南菜':{id:'p-yizuoyiwang',name:'一坐一忘云南菜',short:'一坐一忘云南菜',category:'云南菜',rating:4.5,review_count:2800,avg_price:110,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['云南菜','环境好','适合约会','酸汤鱼'],risk_tags:[],recommendation_reason:'三里屯的云南风情，酸汤鱼和茉莉花炒蛋，白领最爱。',lng:116.4530,lat:39.9330,images:['images/stores/yizuoyiwang-1.jpg','images/stores/yizuoyiwang-2.jpg','images/stores/yizuoyiwang-3.jpg','images/stores/yizuoyiwang-4.jpg'],address:'朝阳区三里屯北小街1号',mock_x:52,mock_y:36},
'Susu 越南菜':{id:'p-susu',name:'Susu 越南菜',short:'Susu 越南菜',category:'越南菜',rating:4.6,review_count:2100,avg_price:120,opening_hours:'11:30 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约10分钟',tags:['越南菜','胡同小院','约会','清新'],risk_tags:[],recommendation_reason:'藏在钱粮胡同的越南小院，春卷和河粉都是治愈系。',lng:116.4070,lat:39.9360,images:['images/stores/susu-vietnamese-1.jpg','images/stores/susu-vietnamese-2.jpg','images/stores/susu-vietnamese-3.jpg','images/stores/susu-vietnamese-4.jpg'],address:'东城区钱粮胡同西巷10号',mock_x:42,mock_y:32},
'大理院子':{id:'p-dali',name:'大理院子',short:'大理院子',category:'云南菜',rating:4.4,review_count:1500,avg_price:100,opening_hours:'11:00 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约5分钟',tags:['云南菜','小院','汽锅鸡','安静'],risk_tags:[],recommendation_reason:'胡同小院里的云南菜，汽锅鸡和过桥米线温暖治愈，小院氛围极好。',lng:116.4040,lat:39.9370,images:['images/stores/dali-yard-1.jpg','images/stores/dali-yard-2.jpg','images/stores/dali-yard-3.jpg','images/stores/dali-yard-4.jpg'],address:'东城区南锣鼓巷小菊儿胡同65号',mock_x:38,mock_y:30},
'护国寺小吃':{id:'p-huguosi',name:'护国寺小吃（总店）',short:'护国寺小吃',category:'小吃',rating:4.4,review_count:6700,avg_price:25,opening_hours:'06:00 - 20:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约5分钟',tags:['老北京小吃','便宜','品种多','早餐'],risk_tags:['部分品类过午售罄'],recommendation_reason:'豌豆黄、艾窝窝、豆汁焦圈，老北京小吃一站式集齐。',lng:116.3700,lat:39.9360,images:['images/stores/huguosi-snacks-1.jpg','images/stores/huguosi-snacks-2.jpg','images/stores/huguosi-snacks-3.jpg','images/stores/huguosi-snacks-4.jpg'],address:'西城区护国寺大街93号',mock_x:28,mock_y:32},
'姚记炒肝':{id:'p-yaoji',name:'姚记炒肝',short:'姚记炒肝',category:'小吃',rating:4.4,review_count:3400,avg_price:30,opening_hours:'06:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'amber',wait_time:'约10分钟',tags:['炒肝','包子','老北京','鼓楼'],risk_tags:[],recommendation_reason:'鼓楼一拐弯，炒肝配包子，北京人的灵魂早餐。',lng:116.3930,lat:39.9380,images:['images/stores/yaoji-chaogan-1.jpg','images/stores/yaoji-chaogan-2.jpg','images/stores/yaoji-chaogan-3.jpg','images/stores/yaoji-chaogan-4.jpg'],address:'东城区鼓楼东大街311号',mock_x:36,mock_y:30},

// ═══════════════════════════════════════════════════════════════
// 北京 — 更多餐厅：西餐 / 简餐 / 面馆
// ═══════════════════════════════════════════════════════════════
'街角法餐 · 露台':{id:'p-cornerfrench',name:'街角法餐 · 露台',short:'街角法餐 · 露台',category:'法餐',rating:4.6,review_count:987,avg_price:200,opening_hours:'11:30 - 23:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'露台座位有限',tags:['露台','出片好看','约会','氛围好'],risk_tags:['露台座位有限'],recommendation_reason:'露台位的傍晚光线最好，配一杯红酒，约会氛围满分。',lng:116.3250,lat:39.9120,images:['images/stores/corner-french-1.jpg','images/stores/corner-french-2.jpg','images/stores/corner-french-3.jpg','images/stores/corner-french-4.jpg'],address:'海淀区学院路15号',mock_x:30,mock_y:30},
'TRB Hutong':{id:'p-trb',name:'TRB Hutong',short:'TRB Hutong',category:'法餐',rating:4.7,review_count:1800,avg_price:600,opening_hours:'11:30 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约5分钟',tags:['米其林','法餐','四合院','纪念日'],risk_tags:['人均较高'],recommendation_reason:'六百年的寺改建的法餐厅，北京最浪漫的纪念日之选。',lng:116.3980,lat:39.9280,images:['images/stores/trb-hutong-1.jpg','images/stores/trb-hutong-2.jpg','images/stores/trb-hutong-3.jpg','images/stores/trb-hutong-4.jpg'],address:'东城区沙滩北街23号',mock_x:40,mock_y:26},
'蘑屋拍照面馆':{id:'p-mowu',name:'蘑屋 · 拍照面馆',short:'蘑屋拍照面馆',category:'面食',rating:4.5,review_count:1102,avg_price:42,opening_hours:'11:00 - 21:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['出片好看','面好吃','有意思'],risk_tags:[],recommendation_reason:'蘑菇主题面馆，店内布置很出片，吃完还能拍一组。',lng:116.4880,lat:39.9800,images:['images/stores/mowu-noodle-1.jpg','images/stores/mowu-noodle-2.jpg','images/stores/mowu-noodle-3.jpg','images/stores/mowu-noodle-4.jpg'],address:'朝阳区酒仙桥路10号',mock_x:65,mock_y:20},
'街口面馆':{id:'p-jiekou',name:'街口面馆',short:'街口面馆',category:'面食',rating:4.4,review_count:876,avg_price:30,opening_hours:'10:30 - 21:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['实惠','快','面好吃'],risk_tags:[],recommendation_reason:'一碗热面十几块，快进快出不耽误，邻里老店。',lng:116.4100,lat:39.9220,images:['images/stores/jiekou-noodle-1.jpg','images/stores/jiekou-noodle-2.jpg','images/stores/jiekou-noodle-3.jpg','images/stores/jiekou-noodle-4.jpg'],address:'东城区安定门内大街88号',mock_x:35,mock_y:85},
'老张牛肉面':{id:'p-laozhang',name:'老张牛肉面',short:'老张牛肉面',category:'面食',rating:4.5,review_count:1543,avg_price:40,opening_hours:'10:00 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['上菜快','牛肉多','热乎','不用等位'],risk_tags:['辣度可调，建议提前说'],recommendation_reason:'不用等位，10分钟上桌，一碗热面直接回家。',lng:116.4350,lat:39.9250,images:['images/stores/laozhang-noodle-1.jpg','images/stores/laozhang-noodle-2.jpg','images/stores/laozhang-noodle-3.jpg','images/stores/laozhang-noodle-4.jpg'],address:'朝阳区东大桥路45号',mock_x:55,mock_y:75},
'邻家厨房':{id:'p-linjia',name:'邻家厨房',short:'邻家厨房',category:'简餐',rating:4.3,review_count:543,avg_price:45,opening_hours:'11:00 - 20:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['家常菜','适合孩子','不辣'],risk_tags:['中午是用餐高峰'],recommendation_reason:'家常口味，有儿童餐，吃完就能回家午睡。',lng:116.4800,lat:39.9330,images:['images/stores/linjia-kitchen-1.jpg','images/stores/linjia-kitchen-2.jpg','images/stores/linjia-kitchen-3.jpg','images/stores/linjia-kitchen-4.jpg'],address:'朝阳区惠新东街7号',mock_x:82,mock_y:50},
'展厅旁的简餐':{id:'p-excafe',name:'展厅旁的简餐',short:'展厅旁的简餐',category:'简餐',rating:4.2,review_count:345,avg_price:55,opening_hours:'09:00 - 18:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['方便','适合孩子','近'],risk_tags:[],recommendation_reason:'就在展厅隔壁，看完展就能吃，不用折腾。',lng:116.4720,lat:39.9180,images:['images/stores/exhibition-cafe-1.jpg','images/stores/exhibition-cafe-2.jpg','images/stores/exhibition-cafe-3.jpg','images/stores/exhibition-cafe-4.jpg'],address:'朝阳区光华路11号',mock_x:68,mock_y:42},
'隔壁便民食堂':{id:'p-canteen',name:'隔壁便民食堂',short:'隔壁便民食堂',category:'简餐',rating:4.2,review_count:456,avg_price:20,opening_hours:'07:00 - 20:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['便宜','快','近'],risk_tags:[],recommendation_reason:'便宜实惠，吃完继续户外活动，不耽误时间。',lng:116.4870,lat:39.9370,images:['images/stores/community-canteen-1.jpg','images/stores/community-canteen-2.jpg','images/stores/community-canteen-3.jpg','images/stores/community-canteen-4.jpg'],address:'朝阳区惠新西街3号院',mock_x:88,mock_y:48},
'渔小馆家常菜':{id:'p-yuxiaoguan',name:'渔小馆家常菜',short:'渔小馆家常菜',category:'小馆',rating:4.4,review_count:1023,avg_price:55,opening_hours:'11:00 - 21:30',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['实惠','家常口味','不用等位','安静'],risk_tags:[],recommendation_reason:'人均50出头，几乎不排队，邻里小馆的踏实感。',lng:116.4550,lat:39.9300,images:['images/stores/yuxiaoguan-1.jpg','images/stores/yuxiaoguan-2.jpg','images/stores/yuxiaoguan-3.jpg','images/stores/yuxiaoguan-4.jpg'],address:'朝阳区团结湖北头条8号',mock_x:48,mock_y:68},
'巷里小馆 · 双人位':{id:'p-xiangli',name:'巷里小馆 · 双人位',short:'巷里小馆 · 双人位',category:'私房菜',rating:4.7,review_count:1456,avg_price:140,opening_hours:'11:30 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'建议提前预约',tags:['安静','双人位','私密','出品好'],risk_tags:['周末晚餐需提前预约'],recommendation_reason:'两人位提前订好，安静私密，出品稳当。',lng:116.4300,lat:39.9150,images:['images/stores/xiangli-bistro-1.jpg','images/stores/xiangli-bistro-2.jpg','images/stores/xiangli-bistro-3.jpg','images/stores/xiangli-bistro-4.jpg'],address:'东城区朝阳门内大街23号',mock_x:50,mock_y:40},
'北平机器':{id:'p-beipingji',name:'北平机器（方家胡同店）',short:'北平机器',category:'精酿/简餐',rating:4.5,review_count:2800,avg_price:110,opening_hours:'16:00 - 01:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['精酿啤酒','厂房改造','朋友聚会','汉堡'],risk_tags:[],recommendation_reason:'老厂房里的精酿酒馆，百花深处IPA配牛肉汉堡，胡同夜生活标配。',lng:116.4100,lat:39.9390,images:['images/stores/beiping-machine-1.jpg','images/stores/beiping-machine-2.jpg','images/stores/beiping-machine-3.jpg','images/stores/beiping-machine-4.jpg'],address:'东城区方家胡同46号',mock_x:42,mock_y:28},

// ═══════════════════════════════════════════════════════════════
// 北京 — 咖啡 / 甜品
// ═══════════════════════════════════════════════════════════════
'慢岛甜品咖啡':{id:'p-mandao',name:'慢岛 · 甜品咖啡',short:'慢岛甜品咖啡',category:'咖啡 / 甜品',rating:4.8,review_count:902,avg_price:38,opening_hours:'11:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['适合聊天','环境安静','出片好看','甜品好吃'],risk_tags:[],recommendation_reason:'吃完走6分钟就到，环境安静，提拉米苏和窗边位被提到最多。',lng:116.4625,lat:39.9310,images:['images/stores/mandao-dessert-1.jpg','images/stores/mandao-dessert-2.jpg','images/stores/mandao-dessert-3.jpg','images/stores/mandao-dessert-4.jpg'],address:'朝阳区团结湖东街5号',mock_x:80,mock_y:30},
'独椅咖啡':{id:'p-duyi',name:'独椅咖啡',short:'独椅咖啡',category:'咖啡',rating:4.6,review_count:765,avg_price:35,opening_hours:'09:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['安静','适合发呆','不催台','咖啡好喝'],risk_tags:['周末人略多'],recommendation_reason:'一个人的角落，不催台，可以从下午坐到傍晚。',lng:116.4550,lat:39.9350,images:['images/stores/duyi-coffee-1.jpg','images/stores/duyi-coffee-2.jpg','images/stores/duyi-coffee-3.jpg','images/stores/duyi-coffee-4.jpg'],address:'东城区东四北大街22号',mock_x:45,mock_y:45},
'雨夜咖啡 · 窗边位':{id:'p-rainynight',name:'雨夜咖啡 · 窗边位',short:'雨夜咖啡 · 窗边位',category:'咖啡',rating:4.7,review_count:1208,avg_price:48,opening_hours:'10:00 - 23:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['安静','适合聊天','夜景好看','出片好看'],risk_tags:[],recommendation_reason:'窗边位看城市夜景，氛围感满分，约会首选。',lng:116.3350,lat:39.9050,images:['images/stores/rainy-night-cafe-1.jpg','images/stores/rainy-night-cafe-2.jpg','images/stores/rainy-night-cafe-3.jpg','images/stores/rainy-night-cafe-4.jpg'],address:'海淀区成府路28号',mock_x:70,mock_y:55},
'街角面包房':{id:'p-cornerbakery',name:'街角面包房',short:'街角面包房',category:'面包 / 简餐',rating:4.5,review_count:543,avg_price:25,opening_hours:'07:00 - 21:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['面包好吃','价格实惠','可外带'],risk_tags:[],recommendation_reason:'刚出炉的可颂配一杯美式，微散步的完美收尾。',lng:116.4400,lat:39.9380,images:['images/stores/corner-bakery-1.jpg','images/stores/corner-bakery-2.jpg','images/stores/corner-bakery-3.jpg','images/stores/corner-bakery-4.jpg'],address:'东城区鼓楼东大街18号',mock_x:25,mock_y:70},
'街角连锁咖啡':{id:'p-chaincafe',name:'街角连锁咖啡',short:'街角连锁咖啡',category:'咖啡 · 有座',rating:4.3,review_count:3201,avg_price:28,opening_hours:'07:00 - 22:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['有座','近','出餐快'],risk_tags:['晚间座位较紧张'],recommendation_reason:'走3分钟到，几乎一定有座，能讲事能等人。',lng:116.4100,lat:39.9080,images:['images/stores/corner-chain-cafe-1.jpg','images/stores/corner-chain-cafe-2.jpg','images/stores/corner-chain-cafe-3.jpg','images/stores/corner-chain-cafe-4.jpg'],address:'东城区东直门外大街12号',mock_x:50,mock_y:50},
'%Arabica 咖啡（三里屯）':{id:'p-arabica',name:'%Arabica 咖啡（三里屯店）',short:'%Arabica 咖啡（三里屯）',category:'咖啡',rating:4.5,review_count:2100,avg_price:40,opening_hours:'09:00 - 21:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['网红咖啡','拍照','拿铁','简约风'],risk_tags:[],recommendation_reason:'京都来的网红咖啡，西班牙拿铁配三里屯街景，出片满分。',lng:116.4540,lat:39.9325,images:['images/stores/arabica-coffee-1.jpg','images/stores/arabica-coffee-2.jpg','images/stores/arabica-coffee-3.jpg','images/stores/arabica-coffee-4.jpg'],address:'朝阳区三里屯太古里北区N6-10',mock_x:52,mock_y:36},
'Metal Hands 咖啡':{id:'p-metalhands',name:'Metal Hands 咖啡',short:'Metal Hands 咖啡',category:'咖啡',rating:4.6,review_count:1800,avg_price:38,opening_hours:'09:00 - 20:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['精品咖啡','胡同小院','安静','手冲'],risk_tags:[],recommendation_reason:'胡同里的精品咖啡，手冲水准北京前三，小院氛围极好。',lng:116.4020,lat:39.9360,images:['images/stores/metalhands-coffee-1.jpg','images/stores/metalhands-coffee-2.jpg','images/stores/metalhands-coffee-3.jpg','images/stores/metalhands-coffee-4.jpg'],address:'东城区南锣鼓巷板厂胡同20号',mock_x:38,mock_y:32},
'元古本店（甜品）':{id:'p-yuangu',name:'元古本店（甜品）',short:'元古本店（甜品）',category:'甜品',rating:4.7,review_count:2300,avg_price:80,opening_hours:'12:00 - 20:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'约5分钟',tags:['中式甜品','二十四节气','出片好看','安静'],risk_tags:['下午高峰期需等位'],recommendation_reason:'二十四节气主题甜品，每一道都是艺术品，舍不得吃。',lng:116.4060,lat:39.9350,images:['images/stores/yuangu-dessert-1.jpg','images/stores/yuangu-dessert-2.jpg','images/stores/yuangu-dessert-3.jpg','images/stores/yuangu-dessert-4.jpg'],address:'东城区箭厂胡同34号',mock_x:42,mock_y:32},
'大小咖啡（北锣鼓巷）':{id:'p-coffeehall',name:'大小咖啡（北锣鼓巷）',short:'大小咖啡（北锣鼓巷）',category:'咖啡',rating:4.5,review_count:1200,avg_price:30,opening_hours:'08:00 - 19:00',current_status:'当前营业中',current_status_short:'营业中',status_tone:'green',wait_time:'无需排队',tags:['精品咖啡','胡同','小空间','安静'],risk_tags:['关门较早'],recommendation_reason:'藏在北锣鼓巷的小小咖啡店，手冲水准高，适合一个人安静喝一杯。',lng:116.4060,lat:39.9420,images:['images/stores/bigsmall-coffee-1.jpg','images/stores/bigsmall-coffee-2.jpg','images/stores/bigsmall-coffee-3.jpg','images/stores/bigsmall-coffee-4.jpg'],address:'东城区北锣鼓巷82号',mock_x:40,mock_y:25},

// ═══════════════════════════════════════════════════════════════
// 北京 — 公园 / 户外 / 景点
// ═══════════════════════════════════════════════════════════════
'团结湖公园':{id:'p-tuanjiehu',name:'团结湖公园',short:'团结湖公园',category:'公园',rating:4.5,review_count:4502,avg_price:0,opening_hours:'06:00 - 22:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['免费','安静','散步','湖边'],risk_tags:[],recommendation_reason:'市中心免费公园，湖边长椅，节奏松散适合慢慢聊。',lng:116.4670,lat:39.9280,images:['images/stores/tuanjiehu-park-1.jpg','images/stores/tuanjiehu-park-2.jpg','images/stores/tuanjiehu-park-3.jpg','images/stores/tuanjiehu-park-4.jpg'],address:'朝阳区团结湖南里16号',mock_x:40,mock_y:60},
'园林公园':{id:'p-gardenpark',name:'园林公园',short:'园林公园',category:'公园',rating:4.6,review_count:3201,avg_price:5,opening_hours:'06:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['安静','园林景致','散步','出片好看'],risk_tags:[],recommendation_reason:'一步一景的古典园林，两个人慢慢走慢慢聊。',lng:116.4000,lat:39.9200,images:['images/stores/garden-park-1.jpg','images/stores/garden-park-2.jpg','images/stores/garden-park-3.jpg','images/stores/garden-park-4.jpg'],address:'东城区地坛公园东侧',mock_x:30,mock_y:55},
'社区公园':{id:'p-communitypark',name:'社区公园',short:'社区公园',category:'公园',rating:4.3,review_count:1567,avg_price:0,opening_hours:'全天开放',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['免费','近','有滑梯','有沙坑'],risk_tags:['雨天不建议'],recommendation_reason:'便宜、放电、就近吃饭，孩子状态崩了能很快回家。',lng:116.4850,lat:39.9350,images:['images/stores/community-park-1.jpg','images/stores/community-park-2.jpg','images/stores/community-park-3.jpg','images/stores/community-park-4.jpg'],address:'朝阳区惠新西街北口附近',mock_x:85,mock_y:45},
'运河步道':{id:'p-canal',name:'运河步道',short:'运河步道',category:'散步',rating:4.4,review_count:890,avg_price:0,opening_hours:'全天开放',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['免费','散步','安静','河边'],risk_tags:[],recommendation_reason:'想动一动但不想很累：走一段河边步道，吃点东西，回家。',lng:116.4200,lat:39.9500,images:['images/stores/canal-walkway-1.jpg','images/stores/canal-walkway-2.jpg','images/stores/canal-walkway-3.jpg','images/stores/canal-walkway-4.jpg'],address:'朝阳区亮马河沿岸',mock_x:20,mock_y:15},
'颐和园':{id:'p-yiheyuan',name:'颐和园',short:'颐和园',category:'景点',rating:4.7,review_count:45000,avg_price:30,opening_hours:'06:30 - 18:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'旺季排队约15分钟',tags:['世界遗产','皇家园林','划船','出片'],risk_tags:['面积大、走完需要体力'],recommendation_reason:'中国现存最大的皇家园林，昆明湖上划船看万寿山，绝了。',lng:116.2750,lat:39.9990,images:['images/stores/summer-palace-1.jpg','images/stores/summer-palace-2.jpg','images/stores/summer-palace-3.jpg','images/stores/summer-palace-4.jpg'],address:'海淀区新建宫门路19号',mock_x:8,mock_y:5},
'北海公园':{id:'p-beihai',name:'北海公园',short:'北海公园',category:'景点',rating:4.6,review_count:23000,avg_price:10,opening_hours:'06:30 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['白塔','划船','让我们荡起双桨','公园'],risk_tags:[],recommendation_reason:'让我们荡起双桨的地方，白塔倒影+小船=童年回忆。',lng:116.3890,lat:39.9240,images:['images/stores/beihai-park-1.jpg','images/stores/beihai-park-2.jpg','images/stores/beihai-park-3.jpg','images/stores/beihai-park-4.jpg'],address:'西城区文津街1号',mock_x:35,mock_y:28},
'景山公园':{id:'p-jingshan',name:'景山公园',short:'景山公园',category:'景点',rating:4.7,review_count:18000,avg_price:2,opening_hours:'06:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['俯瞰故宫','日落','中轴线','拍照'],risk_tags:[],recommendation_reason:'万春亭俯瞰故宫全景，日落时分的中轴线最美，门票只要2块。',lng:116.3960,lat:39.9220,images:['images/stores/jingshan-park-1.jpg','images/stores/jingshan-park-2.jpg','images/stores/jingshan-park-3.jpg','images/stores/jingshan-park-4.jpg'],address:'西城区景山西街44号',mock_x:36,mock_y:30},
'朝阳公园':{id:'p-chaoyangpark',name:'朝阳公园',short:'朝阳公园',category:'公园',rating:4.5,review_count:12000,avg_price:5,opening_hours:'06:00 - 22:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['大草坪','野餐','跑步','放风筝'],risk_tags:[],recommendation_reason:'北京四环内最大的城市公园，周末野餐放风筝的好去处。',lng:116.4770,lat:39.9420,images:['images/stores/chaoyang-park-1.jpg','images/stores/chaoyang-park-2.jpg','images/stores/chaoyang-park-3.jpg','images/stores/chaoyang-park-4.jpg'],address:'朝阳区朝阳公园南路1号',mock_x:60,mock_y:28},
'玉渊潭公园':{id:'p-yuyuantan',name:'玉渊潭公园',short:'玉渊潭公园',category:'公园',rating:4.6,review_count:15000,avg_price:2,opening_hours:'06:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'樱花季需排队',tags:['樱花','划船','中央电视塔','春游'],risk_tags:['樱花季人山人海'],recommendation_reason:'北京春日顶流，三月樱花季美如画，划船看中央电视塔。',lng:116.3160,lat:39.9140,images:['images/stores/yuyuantan-park-1.jpg','images/stores/yuyuantan-park-2.jpg','images/stores/yuyuantan-park-3.jpg','images/stores/yuyuantan-park-4.jpg'],address:'海淀区西三环中路10号',mock_x:14,mock_y:36},
'紫竹院公园':{id:'p-zizhuyuan',name:'紫竹院公园',short:'紫竹院公园',category:'公园',rating:4.5,review_count:5600,avg_price:0,opening_hours:'06:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['免费','竹林','划船','安静'],risk_tags:[],recommendation_reason:'以竹为魂的免费公园，夏天荷花满池，人少安静适合散步。',lng:116.3200,lat:39.9430,images:['images/stores/zizhuyuan-park-1.jpg','images/stores/zizhuyuan-park-2.jpg','images/stores/zizhuyuan-park-3.jpg','images/stores/zizhuyuan-park-4.jpg'],address:'海淀区中关村南大街35号',mock_x:16,mock_y:18},
'奥林匹克森林公园':{id:'p-olympicpark',name:'奥林匹克森林公园',short:'奥林匹克森林公园',category:'公园',rating:4.6,review_count:18000,avg_price:0,opening_hours:'06:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['跑步','骑行','野餐','免费'],risk_tags:[],recommendation_reason:'南园跑一圈5公里，北京跑步圣地，周末家庭野餐爆满。',lng:116.3900,lat:40.0200,images:['images/stores/olympic-forest-park-1.jpg','images/stores/olympic-forest-park-2.jpg','images/stores/olympic-forest-park-3.jpg','images/stores/olympic-forest-park-4.jpg'],address:'朝阳区科荟路33号',mock_x:38,mock_y:5},
'兴隆郊野公园':{id:'p-xinglong',name:'兴隆郊野公园',short:'兴隆郊野公园',category:'公园',rating:4.2,review_count:1200,avg_price:0,opening_hours:'06:00 - 21:00',current_status:'当前开放中',current_status_short:'开放中',status_tone:'green',wait_time:'无需排队',tags:['免费','野餐','人少','垂钓'],risk_tags:[],recommendation_reason:'人少景美的小众公园，有大片草坪可以野餐放风筝，周末也不挤。',lng:116.5500,lat:39.8800,images:['images/stores/xinglong-park-1.jpg','images/stores/xinglong-park-2.jpg','images/stores/xinglong-park-3.jpg','images/stores/xinglong-park-4.jpg'],address:'朝阳区高碑店乡兴隆庄甲8号',mock_x:80,mock_y:75},
