/**
 * 北京 POI Mock 数据 (120个)
 * 覆盖人群：游客、亲子、情侣、商务、老年人、学生、美食爱好者、文化爱好者
 */

const beijingPOIs = [
  // ===== 1-10: 经典必游 =====
  {
    id: 'bj-001', name: '故宫博物院', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '东城区', address: '景山前街4号',
    lat: 39.9163, lng: 116.3972, rating: 4.9, reviewCount: 128000, price: 60,
    openTime: '08:30-17:00', tags: ['世界遗产', '皇家建筑', '博物馆', '5A景区'],
    images: ['images/stores/photo-001-1.jpg'],
    description: '中国明清两代的皇家宫殿，世界上现存规模最大、保存最完整的木质结构古建筑之一',
    targetAudience: ['游客', '文化爱好者', '亲子', '老年人'], bestTime: '春秋两季', duration: '半天至一天',
  },
  {
    id: 'bj-002', name: '八达岭长城', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '延庆区', address: 'G6京藏高速58号出口',
    lat: 40.359, lng: 116.02, rating: 4.8, reviewCount: 156000, price: 40,
    openTime: '06:30-16:30', tags: ['世界遗产', '登山', '摄影', '5A景区'],
    images: ['images/stores/photo-002-1.jpg'],
    description: '万里长城的重要组成部分，地势险要，是明长城向游客开放最早的地段',
    targetAudience: ['游客', '户外爱好者', '摄影爱好者', '亲子'], bestTime: '秋季(9-10月)', duration: '半天',
  },
  {
    id: 'bj-003', name: '天坛公园', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '东城区', address: '天坛东里甲1号',
    lat: 39.8822, lng: 116.4066, rating: 4.7, reviewCount: 89000, price: 34,
    openTime: '06:00-22:00', tags: ['世界遗产', '公园', '古建筑', '5A景区'],
    images: ['images/stores/photo-003-1.jpg'],
    description: '明清两代皇帝祭天的场所，是中国现存最大的古代祭祀建筑群',
    targetAudience: ['游客', '老年人', '晨练者', '文化爱好者'], bestTime: '清晨或傍晚', duration: '2-3小时',
  },
  {
    id: 'bj-004', name: '颐和园', category: 'attraction', subcategory: '园林景观',
    city: '北京', district: '海淀区', address: '新建宫门路19号',
    lat: 39.99, lng: 116.275, rating: 4.8, reviewCount: 102000, price: 30,
    openTime: '06:00-20:00', tags: ['世界遗产', '皇家园林', '湖泊', '5A景区'],
    images: ['images/stores/photo-004-1.jpg'],
    description: '中国清朝时期皇家园林，保存最完整的一座皇家行宫御苑',
    targetAudience: ['游客', '亲子', '老年人', '摄影爱好者'], bestTime: '春夏秋三季', duration: '半天至一天',
  },
  {
    id: 'bj-005', name: '圆明园遗址公园', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '海淀区', address: '清华西路28号',
    lat: 40.008, lng: 116.298, rating: 4.6, reviewCount: 76000, price: 25,
    openTime: '07:00-19:00', tags: ['遗址', '爱国主义教育', '公园', '4A景区'],
    images: ['images/stores/photo-005-1.jpg'],
    description: '清代大型皇家园林遗址，见证了中国近代历史的重要场所',
    targetAudience: ['学生', '亲子', '历史爱好者', '游客'], bestTime: '夏季(荷花季)', duration: '2-3小时',
  },
  {
    id: 'bj-006', name: '北海公园', category: 'attraction', subcategory: '园林景观',
    city: '北京', district: '西城区', address: '文津街1号',
    lat: 39.924, lng: 116.389, rating: 4.6, reviewCount: 65000, price: 10,
    openTime: '06:00-21:00', tags: ['皇家园林', '湖泊', '白塔', '4A景区'],
    images: ['images/stores/photo-006-1.jpg'],
    description: '中国现存最古老、最完整、最具综合性和代表性的皇家园林之一',
    targetAudience: ['老年人', '亲子', '游客', '本地居民'], bestTime: '春夏秋三季', duration: '2-3小时',
  },
  {
    id: 'bj-007', name: '景山公园', category: 'attraction', subcategory: '公园',
    city: '北京', district: '西城区', address: '景山西街44号',
    lat: 39.9245, lng: 116.397, rating: 4.5, reviewCount: 58000, price: 2,
    openTime: '06:00-21:00', tags: ['俯瞰故宫', '日落', '登山', '4A景区'],
    images: ['images/stores/photo-007-1.jpg'],
    description: '北京内城的中心点，万春亭可俯瞰故宫全景和北京中轴线',
    targetAudience: ['摄影爱好者', '游客', '情侣', '历史爱好者'], bestTime: '傍晚(日落时分)', duration: '1-2小时',
  },
  {
    id: 'bj-008', name: '雍和宫', category: 'attraction', subcategory: '宗教场所',
    city: '北京', district: '东城区', address: '雍和宫大街12号',
    lat: 39.947, lng: 116.417, rating: 4.6, reviewCount: 72000, price: 25,
    openTime: '09:00-16:30', tags: ['藏传佛教', '祈福', '古建筑', '4A景区'],
    images: ['images/stores/photo-008-1.jpg'],
    description: '北京市内最大的藏传佛教寺院，原为清雍正帝府邸',
    targetAudience: ['信众', '文化爱好者', '游客', '祈福者'], bestTime: '节假日或初一十五', duration: '1-2小时',
  },
  {
    id: 'bj-009', name: '恭王府', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '西城区', address: '前海西街17号',
    lat: 39.937, lng: 116.386, rating: 4.6, reviewCount: 68000, price: 40,
    openTime: '08:30-17:00', tags: ['王府', '和珅故居', '园林', '5A景区'],
    images: ['images/stores/photo-009-1.jpg'],
    description: '清代规模最大的一座王府，曾为和珅宅邸，有"一座恭王府，半部清代史"之称',
    targetAudience: ['游客', '历史爱好者', '文化爱好者', '亲子'], bestTime: '春秋两季', duration: '2-3小时',
  },
  {
    id: 'bj-010', name: '明十三陵', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '昌平区', address: '十三陵镇',
    lat: 40.258, lng: 116.215, rating: 4.5, reviewCount: 45000, price: 65,
    openTime: '08:00-17:30', tags: ['世界遗产', '皇陵', '考古', '5A景区'],
    images: ['images/stores/photo-010-1.jpg'],
    description: '明朝十三位皇帝的陵墓建筑群，是中国乃至世界现存规模最大、帝后陵寝最多的一处皇陵建筑群',
    targetAudience: ['历史爱好者', '游客', '考古爱好者', '亲子'], bestTime: '春秋两季', duration: '半天',
  },

  // ===== 11-20: 现代地标 =====
  {
    id: 'bj-011', name: '国家体育场(鸟巢)', category: 'attraction', subcategory: '现代建筑',
    city: '北京', district: '朝阳区', address: '国家体育场南路1号',
    lat: 39.9929, lng: 116.3965, rating: 4.5, reviewCount: 98000, price: 50,
    openTime: '09:00-21:00', tags: ['奥运场馆', '地标建筑', '夜景', '5A景区'],
    images: ['images/stores/photo-011-1.jpg'],
    description: '2008年北京奥运会主体育场，以其独特的钢结构造型闻名世界',
    targetAudience: ['游客', '体育爱好者', '建筑爱好者', '亲子'], bestTime: '夜晚(灯光秀)', duration: '1-2小时',
  },
  {
    id: 'bj-012', name: '国家游泳中心(水立方)', category: 'attraction', subcategory: '现代建筑',
    city: '北京', district: '朝阳区', address: '天辰东路11号',
    lat: 39.991, lng: 116.384, rating: 4.4, reviewCount: 76000, price: 30,
    openTime: '09:00-20:00', tags: ['奥运场馆', '游泳馆', '夜景', '4A景区'],
    images: ['images/stores/photo-012-1.jpg'],
    description: '2008年北京奥运会游泳比赛场馆，外观如蓝色气泡般梦幻',
    targetAudience: ['游客', '亲子', '游泳爱好者', '建筑爱好者'], bestTime: '夜晚', duration: '1-2小时',
  },
  {
    id: 'bj-013', name: '中央电视台总部大楼', category: 'attraction', subcategory: '现代建筑',
    city: '北京', district: '朝阳区', address: '东三环中路32号',
    lat: 39.914, lng: 116.456, rating: 4.3, reviewCount: 42000, price: 0,
    openTime: '外观全天', tags: ['地标建筑', '建筑奇观', '拍照', '免费'],
    images: ['images/stores/photo-013-1.jpg'],
    description: '俗称"大裤衩"，是北京CBD最具标志性的现代建筑',
    targetAudience: ['建筑爱好者', '摄影爱好者', '游客', '商务人士'], bestTime: '傍晚或夜晚', duration: '30分钟',
  },
  {
    id: 'bj-014', name: '中国尊', category: 'attraction', subcategory: '现代建筑',
    city: '北京', district: '朝阳区', address: '光华路12号',
    lat: 39.908, lng: 116.448, rating: 4.4, reviewCount: 28000, price: 0,
    openTime: '外观全天', tags: ['最高建筑', '地标', '商务中心', '免费'],
    images: ['images/stores/photo-014-1.jpg'],
    description: '北京第一高楼，高528米，是中信集团总部大楼',
    targetAudience: ['商务人士', '建筑爱好者', '游客', '摄影爱好者'], bestTime: '夜晚', duration: '30分钟',
  },
  {
    id: 'bj-015', name: '北京大兴国际机场', category: 'attraction', subcategory: '交通枢纽',
    city: '北京', district: '大兴区', address: '大兴机场路',
    lat: 39.5098, lng: 116.4105, rating: 4.7, reviewCount: 56000, price: 0,
    openTime: '全天', tags: ['机场', '现代建筑', '交通枢纽', '免费'],
    images: ['images/stores/photo-015-1.jpg'],
    description: '世界最大的单体航站楼，由扎哈·哈迪德设计，被誉为"新世界七大奇迹"之首',
    targetAudience: ['旅客', '建筑爱好者', '游客', '商务人士'], bestTime: '白天', duration: '1-2小时',
  },
  {
    id: 'bj-016', name: '国家大剧院', category: 'attraction', subcategory: '文化场馆',
    city: '北京', district: '西城区', address: '西长安街2号',
    lat: 39.903, lng: 116.384, rating: 4.6, reviewCount: 48000, price: 30,
    openTime: '09:00-17:00', tags: ['剧院', '表演艺术', '地标建筑', '4A景区'],
    images: ['images/stores/photo-016-1.jpg'],
    description: '中国最高表演艺术中心，外形如一颗巨蛋静卧水面',
    targetAudience: ['艺术爱好者', '游客', '情侣', '文化爱好者'], bestTime: '有演出时', duration: '2-3小时',
  },
  {
    id: 'bj-017', name: '北京环球度假区', category: 'attraction', subcategory: '主题乐园',
    city: '北京', district: '通州区', address: '环球大道1号',
    lat: 39.849, lng: 116.68, rating: 4.6, reviewCount: 120000, price: 418,
    openTime: '09:00-21:00', tags: ['主题乐园', '哈利波特', '亲子', '娱乐'],
    images: ['images/stores/photo-017-1.jpg'],
    description: '亚洲第三座、全球第五座环球影城主题乐园',
    targetAudience: ['亲子', '年轻人', '电影爱好者', '情侣'], bestTime: '工作日避开高峰', duration: '一整天',
  },
  {
    id: 'bj-018', name: '北京欢乐谷', category: 'attraction', subcategory: '主题乐园',
    city: '北京', district: '朝阳区', address: '东四环小武基北路',
    lat: 39.865, lng: 116.495, rating: 4.4, reviewCount: 89000, price: 299,
    openTime: '09:00-22:00', tags: ['游乐园', '过山车', '亲子', '4A景区'],
    images: ['images/stores/photo-018-1.jpg'],
    description: '北京最大的现代主题公园，拥有七大文化主题区',
    targetAudience: ['年轻人', '亲子', '学生', '情侣'], bestTime: '节假日有活动时', duration: '一整天',
  },
  {
    id: 'bj-019', name: '三里屯太古里', category: 'attraction', subcategory: '商业街区',
    city: '北京', district: '朝阳区', address: '三里屯路19号',
    lat: 39.935, lng: 116.455, rating: 4.5, reviewCount: 105000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '潮流', '夜生活', '美食'],
    images: ['images/stores/photo-019-1.jpg'],
    description: '北京最时尚的购物休闲街区，潮流文化和夜生活的聚集地',
    targetAudience: ['年轻人', '时尚达人', '情侣', '商务人士'], bestTime: '傍晚至夜晚', duration: '2-4小时',
  },
  {
    id: 'bj-020', name: '王府井大街', category: 'attraction', subcategory: '商业街区',
    city: '北京', district: '东城区', address: '王府井大街',
    lat: 39.911, lng: 116.411, rating: 4.4, reviewCount: 98000, price: 0,
    openTime: '全天', tags: ['购物', '老字号', '美食街', '步行街'],
    images: ['images/stores/photo-020-1.jpg'],
    description: '北京最著名的商业街，有"中华第一商业街"之称',
    targetAudience: ['游客', '购物者', '美食爱好者', '家庭'], bestTime: '傍晚至夜晚', duration: '2-3小时',
  },

  // ===== 21-30: 文化场馆 =====
  {
    id: 'bj-021', name: '中国国家博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '东城区', address: '东长安街16号',
    lat: 39.905, lng: 116.397, rating: 4.8, reviewCount: 76000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['博物馆', '文物', '历史', '免费'],
    images: ['images/stores/photo-021-1.jpg'],
    description: '世界上建筑面积最大的博物馆，馆藏珍贵文物140余万件',
    targetAudience: ['学生', '历史爱好者', '亲子', '文化爱好者'], bestTime: '工作日', duration: '半天至一天',
  },
  {
    id: 'bj-022', name: '首都博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '西城区', address: '复兴门外大街16号',
    lat: 39.906, lng: 116.337, rating: 4.7, reviewCount: 32000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['博物馆', '北京历史', '文物', '免费'],
    images: ['images/stores/photo-022-1.jpg'],
    description: '北京地区大型综合性博物馆，展示北京三千年古城历史',
    targetAudience: ['文化爱好者', '学生', '亲子', '本地居民'], bestTime: '工作日', duration: '2-4小时',
  },
  {
    id: 'bj-023', name: '中国美术馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '东城区', address: '五四大街1号',
    lat: 39.924, lng: 116.407, rating: 4.6, reviewCount: 28000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['美术馆', '书画', '艺术', '免费'],
    images: ['images/stores/photo-023-1.jpg'],
    description: '中国唯一的国家造型艺术博物馆，收藏各类美术作品10万余件',
    targetAudience: ['艺术爱好者', '学生', '文化爱好者', '情侣'], bestTime: '工作日', duration: '2-3小时',
  },
  {
    id: 'bj-024', name: '北京自然博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '东城区', address: '天桥南大街126号',
    lat: 39.883, lng: 116.394, rating: 4.7, reviewCount: 45000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['自然', '恐龙', '亲子', '科普'],
    images: ['images/stores/photo-024-1.jpg'],
    description: '中国第一个大型自然历史博物馆，以恐龙化石闻名',
    targetAudience: ['亲子', '学生', '科普爱好者', '家庭'], bestTime: '周末', duration: '2-4小时',
  },
  {
    id: 'bj-025', name: '中国科技馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '朝阳区', address: '北辰东路5号',
    lat: 39.968, lng: 116.407, rating: 4.7, reviewCount: 52000, price: 30,
    openTime: '09:30-17:00(周一闭馆)', tags: ['科技', '互动', '亲子', '科普'],
    images: ['images/stores/photo-025-1.jpg'],
    description: '中国唯一的国家级综合性科技馆，设有五大主题展厅',
    targetAudience: ['亲子', '学生', '科技爱好者', '家庭'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'bj-026', name: '中国人民革命军事博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '海淀区', address: '复兴路9号',
    lat: 39.907, lng: 116.321, rating: 4.6, reviewCount: 38000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['军事', '历史', '武器', '免费'],
    images: ['images/stores/photo-026-1.jpg'],
    description: '中国第一个综合类军事博物馆，馆藏文物18万余件',
    targetAudience: ['军事爱好者', '学生', '亲子', '男性游客'], bestTime: '工作日', duration: '2-4小时',
  },
  {
    id: 'bj-027', name: '北京天文馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '西城区', address: '西直门外大街138号',
    lat: 39.938, lng: 116.338, rating: 4.5, reviewCount: 35000, price: 10,
    openTime: '09:00-16:30(周一闭馆)', tags: ['天文', '科普', '亲子', '4A景区'],
    images: ['images/stores/photo-027-1.jpg'],
    description: '中国第一座大型天文馆，拥有天象厅和天文展厅',
    targetAudience: ['亲子', '学生', '天文爱好者', '家庭'], bestTime: '周末', duration: '2-3小时',
  },
  {
    id: 'bj-028', name: '国家图书馆', category: 'attraction', subcategory: '文化场馆',
    city: '北京', district: '海淀区', address: '中关村南大街33号',
    lat: 39.943, lng: 116.325, rating: 4.7, reviewCount: 29000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['图书馆', '阅读', '学习', '免费'],
    images: ['images/stores/photo-028-1.jpg'],
    description: '亚洲规模最大的图书馆，馆藏文献超过4000万册',
    targetAudience: ['学生', '学者', '阅读爱好者', '自习者'], bestTime: '工作日', duration: '半天至一天',
  },
  {
    id: 'bj-029', name: '北京鲁迅博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '西城区', address: '阜成门内宫门口二条19号',
    lat: 39.923, lng: 116.366, rating: 4.4, reviewCount: 18000, price: 0,
    openTime: '09:00-16:00(周一闭馆)', tags: ['名人故居', '文学', '历史', '免费'],
    images: ['images/stores/photo-029-1.jpg'],
    description: '鲁迅在北京的故居，展示鲁迅生平及文学成就',
    targetAudience: ['文学爱好者', '学生', '文化爱好者', '游客'], bestTime: '工作日', duration: '1-2小时',
  },
  {
    id: 'bj-030', name: '老舍茶馆', category: 'attraction', subcategory: '文化体验',
    city: '北京', district: '西城区', address: '前门西大街正阳市场3号楼',
    lat: 39.899, lng: 116.395, rating: 4.3, reviewCount: 25000, price: 180,
    openTime: '10:00-22:00', tags: ['茶文化', '相声', '京剧', '老北京'],
    images: ['images/stores/photo-030-1.jpg'],
    description: '以人民艺术家老舍命名的茶馆，可品茶看表演',
    targetAudience: ['游客', '文化爱好者', '老年人', '家庭'], bestTime: '晚上有演出时', duration: '2-3小时',
  },

  // ===== 31-40: 公园自然 =====
  {
    id: 'bj-031', name: '香山公园', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '海淀区', address: '香山买卖街40号',
    lat: 39.992, lng: 116.188, rating: 4.5, reviewCount: 78000, price: 10,
    openTime: '06:00-18:00', tags: ['红叶', '登山', '皇家园林', '4A景区'],
    images: ['images/stores/photo-031-1.jpg'],
    description: '北京西郊的一座皇家园林，以秋季红叶闻名',
    targetAudience: ['登山爱好者', '摄影爱好者', '游客', '亲子'], bestTime: '秋季(10-11月)', duration: '半天',
  },
  {
    id: 'bj-032', name: '奥林匹克森林公园', category: 'attraction', subcategory: '公园',
    city: '北京', district: '朝阳区', address: '科荟路33号',
    lat: 40.01, lng: 116.391, rating: 4.6, reviewCount: 56000, price: 0,
    openTime: '06:00-21:00', tags: ['森林公园', '跑步', '骑行', '免费'],
    images: ['images/stores/photo-032-1.jpg'],
    description: '北京奥运会配套工程，北京最大的城市公园',
    targetAudience: ['跑步爱好者', '亲子', '骑行者', '本地居民'], bestTime: '清晨或傍晚', duration: '2-4小时',
  },
  {
    id: 'bj-033', name: '北京植物园', category: 'attraction', subcategory: '公园',
    city: '北京', district: '海淀区', address: '香山卧佛寺路',
    lat: 40.0, lng: 116.208, rating: 4.5, reviewCount: 42000, price: 10,
    openTime: '06:00-20:00', tags: ['植物园', '赏花', '温室', '4A景区'],
    images: ['images/stores/photo-033-1.jpg'],
    description: '中国北方最大的植物园，收集展示各类植物1万余种',
    targetAudience: ['亲子', '摄影爱好者', '植物爱好者', '情侣'], bestTime: '春季(赏花)', duration: '半天',
  },
  {
    id: 'bj-034', name: '玉渊潭公园', category: 'attraction', subcategory: '公园',
    city: '北京', district: '海淀区', address: '西三环中路10号',
    lat: 39.915, lng: 116.317, rating: 4.5, reviewCount: 48000, price: 2,
    openTime: '06:00-21:00', tags: ['樱花', '湖泊', '划船', '4A景区'],
    images: ['images/stores/photo-034-1.jpg'],
    description: '北京著名的赏樱胜地，每年春季樱花节吸引大量游客',
    targetAudience: ['情侣', '摄影爱好者', '亲子', '游客'], bestTime: '春季(3-4月)', duration: '2-3小时',
  },
  {
    id: 'bj-035', name: '朝阳公园', category: 'attraction', subcategory: '公园',
    city: '北京', district: '朝阳区', address: '朝阳公园南路1号',
    lat: 39.943, lng: 116.478, rating: 4.4, reviewCount: 38000, price: 0,
    openTime: '06:00-21:00', tags: ['城市公园', '游乐', '沙滩', '免费'],
    images: ['images/stores/photo-035-1.jpg'],
    description: '北京四环内最大的城市公园，设有沙滩浴场和游乐设施',
    targetAudience: ['亲子', '年轻人', '本地居民', '情侣'], bestTime: '夏季', duration: '2-4小时',
  },
  {
    id: 'bj-036', name: '慕田峪长城', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '怀柔区', address: '渤海镇慕田峪村',
    lat: 40.433, lng: 116.56, rating: 4.7, reviewCount: 52000, price: 45,
    openTime: '07:30-17:30', tags: ['长城', '登山', '风景', '5A景区'],
    images: ['images/stores/photo-036-1.jpg'],
    description: '长城精华段落之一，植被覆盖率高，游客相对较少',
    targetAudience: ['游客', '登山爱好者', '摄影爱好者', '亲子'], bestTime: '秋季', duration: '半天',
  },
  {
    id: 'bj-037', name: '十渡风景区', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '房山区', address: '十渡镇',
    lat: 39.65, lng: 115.57, rating: 4.3, reviewCount: 32000, price: 0,
    openTime: '全天', tags: ['峡谷', '漂流', '攀岩', '4A景区'],
    images: ['images/stores/photo-037-1.jpg'],
    description: '北方唯一一处大规模喀斯特岩溶地貌，有"北方桂林"之称',
    targetAudience: ['户外爱好者', '年轻人', '亲子', '团建'], bestTime: '夏季', duration: '1-2天',
  },
  {
    id: 'bj-038', name: '龙庆峡', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '延庆区', address: '旧县镇古城村北',
    lat: 40.55, lng: 116.05, rating: 4.4, reviewCount: 28000, price: 40,
    openTime: '08:00-17:00', tags: ['峡谷', '冰灯', '游船', '4A景区'],
    images: ['images/stores/photo-038-1.jpg'],
    description: '被誉为"塞外小漓江"，冬季有著名的冰灯节',
    targetAudience: ['游客', '摄影爱好者', '亲子', '情侣'], bestTime: '夏季或冬季', duration: '半天',
  },
  {
    id: 'bj-039', name: '北京动物园', category: 'attraction', subcategory: '动物园',
    city: '北京', district: '西城区', address: '西直门外大街137号',
    lat: 39.938, lng: 116.335, rating: 4.6, reviewCount: 85000, price: 15,
    openTime: '07:30-18:00', tags: ['动物园', '大熊猫', '亲子', '4A景区'],
    images: ['images/stores/photo-039-1.jpg'],
    description: '中国开放最早、饲养展出动物种类最多的动物园',
    targetAudience: ['亲子', '家庭', '学生', '动物爱好者'], bestTime: '上午(动物活跃)', duration: '半天',
  },
  {
    id: 'bj-040', name: '北京海洋馆', category: 'attraction', subcategory: '水族馆',
    city: '北京', district: '海淀区', address: '高粱桥斜街乙18号',
    lat: 39.942, lng: 116.338, rating: 4.5, reviewCount: 52000, price: 170,
    openTime: '09:00-17:30', tags: ['海洋馆', '海豚表演', '亲子', '4A景区'],
    images: ['images/stores/photo-040-1.jpg'],
    description: '亚洲第一、世界内陆最大、设施最先进的海洋馆',
    targetAudience: ['亲子', '家庭', '情侣', '学生'], bestTime: '周末', duration: '半天',
  },

  // ===== 41-50: 胡同老北京 =====
  {
    id: 'bj-041', name: '南锣鼓巷', category: 'attraction', subcategory: '历史街区',
    city: '北京', district: '东城区', address: '南锣鼓巷',
    lat: 39.932, lng: 116.401, rating: 4.3, reviewCount: 132000, price: 0,
    openTime: '全天', tags: ['胡同', '文创', '美食', '老北京'],
    images: ['images/stores/photo-041-1.jpg'],
    description: '北京最古老的街区之一，现为文创和美食聚集地',
    targetAudience: ['年轻人', '游客', '情侣', '美食爱好者'], bestTime: '傍晚至夜晚', duration: '2-3小时',
  },
  {
    id: 'bj-042', name: '什刹海', category: 'attraction', subcategory: '历史街区',
    city: '北京', district: '西城区', address: '什刹海',
    lat: 39.937, lng: 116.385, rating: 4.5, reviewCount: 98000, price: 0,
    openTime: '全天', tags: ['湖泊', '酒吧', '胡同', '夜景'],
    images: ['images/stores/photo-042-1.jpg'],
    description: '包括前海、后海、西海三片水域，老北京风貌保存最完好的地区',
    targetAudience: ['游客', '情侣', '年轻人', '摄影爱好者'], bestTime: '傍晚至夜晚', duration: '2-4小时',
  },
  {
    id: 'bj-043', name: '烟袋斜街', category: 'attraction', subcategory: '历史街区',
    city: '北京', district: '西城区', address: '烟袋斜街',
    lat: 39.938, lng: 116.39, rating: 4.2, reviewCount: 45000, price: 0,
    openTime: '全天', tags: ['胡同', '老字号', '小吃', '老北京'],
    images: ['images/stores/photo-043-1.jpg'],
    description: '北京最古老的商业街之一，连接鼓楼和银锭桥',
    targetAudience: ['游客', '美食爱好者', '文化爱好者', '情侣'], bestTime: '傍晚', duration: '1-2小时',
  },
  {
    id: 'bj-044', name: '五道营胡同', category: 'attraction', subcategory: '历史街区',
    city: '北京', district: '东城区', address: '五道营胡同',
    lat: 39.948, lng: 116.412, rating: 4.3, reviewCount: 28000, price: 0,
    openTime: '全天', tags: ['胡同', '文艺', '咖啡馆', '小店'],
    images: ['images/stores/photo-044-1.jpg'],
    description: '北京最文艺的胡同，聚集了许多特色小店和咖啡馆',
    targetAudience: ['年轻人', '文艺青年', '情侣', '游客'], bestTime: '下午至傍晚', duration: '1-2小时',
  },
  {
    id: 'bj-045', name: '国子监街', category: 'attraction', subcategory: '历史街区',
    city: '北京', district: '东城区', address: '国子监街',
    lat: 39.945, lng: 116.41, rating: 4.4, reviewCount: 22000, price: 0,
    openTime: '全天', tags: ['孔庙', '国子监', '古建筑', '文化'],
    images: ['images/stores/photo-045-1.jpg'],
    description: '北京唯一保存四座牌楼的街道，有孔庙和国子监',
    targetAudience: ['文化爱好者', '学生', '游客', '历史爱好者'], bestTime: '白天', duration: '1-2小时',
  },
  {
    id: 'bj-046', name: '前门大街', category: 'attraction', subcategory: '商业街区',
    city: '北京', district: '东城区', address: '前门大街',
    lat: 39.899, lng: 116.398, rating: 4.3, reviewCount: 76000, price: 0,
    openTime: '全天', tags: ['老字号', '步行街', '铛铛车', '老北京'],
    images: ['images/stores/photo-046-1.jpg'],
    description: '北京中轴线上的重要商业街，汇聚众多中华老字号',
    targetAudience: ['游客', '购物者', '美食爱好者', '家庭'], bestTime: '傍晚至夜晚', duration: '2-3小时',
  },
  {
    id: 'bj-047', name: '大栅栏', category: 'attraction', subcategory: '商业街区',
    city: '北京', district: '西城区', address: '大栅栏街',
    lat: 39.896, lng: 116.395, rating: 4.2, reviewCount: 58000, price: 0,
    openTime: '全天', tags: ['老字号', '商业街', '小吃', '老北京'],
    images: ['images/stores/photo-047-1.jpg'],
    description: '北京最古老的商业中心之一，有"京师之精华尽在于此"之称',
    targetAudience: ['游客', '美食爱好者', '购物者', '文化爱好者'], bestTime: '全天', duration: '1-2小时',
  },
  {
    id: 'bj-048', name: '琉璃厂文化街', category: 'attraction', subcategory: '商业街区',
    city: '北京', district: '西城区', address: '南新华街',
    lat: 39.895, lng: 116.382, rating: 4.2, reviewCount: 18000, price: 0,
    openTime: '全天', tags: ['文房四宝', '书画', '古玩', '文化'],
    images: ['images/stores/photo-048-1.jpg'],
    description: '北京著名的文化街，以经营文房四宝、书画古玩闻名',
    targetAudience: ['文化爱好者', '书画爱好者', '收藏者', '游客'], bestTime: '白天', duration: '1-2小时',
  },
  {
    id: 'bj-049', name: '钟鼓楼', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '东城区', address: '钟楼湾临字9号',
    lat: 39.94, lng: 116.39, rating: 4.3, reviewCount: 32000, price: 30,
    openTime: '09:00-17:00', tags: ['古建筑', '中轴线', '老北京', '4A景区'],
    images: ['images/stores/photo-049-1.jpg'],
    description: '北京中轴线的北端点，元明清三代的报时中心',
    targetAudience: ['历史爱好者', '游客', '文化爱好者', '摄影爱好者'], bestTime: '傍晚', duration: '1-2小时',
  },
  {
    id: 'bj-050', name: '北京坊', category: 'attraction', subcategory: '商业街区',
    city: '北京', district: '西城区', address: '煤市街廊房头条21号',
    lat: 39.9, lng: 116.397, rating: 4.3, reviewCount: 35000, price: 0,
    openTime: '10:00-22:00', tags: ['文化商业', '美食', '书店', '现代建筑'],
    images: ['images/stores/photo-050-1.jpg'],
    description: '前门地区的文化商业新地标，汇聚书店、餐饮、文创',
    targetAudience: ['年轻人', '文艺青年', '游客', '情侣'], bestTime: '傍晚至夜晚', duration: '2-3小时',
  },

  // ===== 51-60: 美食餐饮 =====
  {
    id: 'bj-051', name: '全聚德(前门店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '东城区', address: '前门大街30号',
    lat: 39.899, lng: 116.398, rating: 4.2, reviewCount: 45000, price: 200,
    openTime: '11:00-21:00', tags: ['烤鸭', '老字号', '宴请', '中华老字号'],
    images: ['images/stores/photo-051-1.jpg'],
    description: '创建于1864年，中华老字号，以挂炉烤鸭闻名中外',
    targetAudience: ['游客', '商务宴请', '家庭聚餐', '美食爱好者'], bestTime: '午餐或晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-052', name: '便宜坊(崇文门店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '东城区', address: '崇文门外大街16号',
    lat: 39.895, lng: 116.418, rating: 4.3, reviewCount: 28000, price: 150,
    openTime: '11:00-21:00', tags: ['烤鸭', '焖炉烤鸭', '老字号', '中华老字号'],
    images: ['images/stores/photo-052-1.jpg'],
    description: '创立于1416年，比全聚德还早400多年，以焖炉烤鸭著称',
    targetAudience: ['游客', '美食爱好者', '家庭聚餐', '商务宴请'], bestTime: '午餐或晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-053', name: '四季民福烤鸭店', category: 'food', subcategory: '北京菜',
    city: '北京', district: '东城区', address: '南池子大街11号',
    lat: 39.913, lng: 116.403, rating: 4.6, reviewCount: 56000, price: 160,
    openTime: '10:30-22:00', tags: ['烤鸭', '故宫景观', '网红店', '北京菜'],
    images: ['images/stores/photo-053-1.jpg'],
    description: '可边品尝烤鸭边欣赏故宫东华门景观的网红烤鸭店',
    targetAudience: ['游客', '情侣', '美食爱好者', '摄影爱好者'], bestTime: '晚餐(看夜景)', duration: '1.5-2小时',
    ugcTags: ['故宫景观绝美', '烤鸭正宗', '拍照出片', '景观位难抢', '排队太久', '节假日崩溃'],
    ugcSummary: '坐在窗边看着故宫角楼吃烤鸭的体验确实独一无二，烤鸭品质也过硬。但景观位需要早到2小时排队等号，节假日基本放弃幻想',
    riskTags: ['景观位排队2小时+', '节假日无法预约', '翻台率低等待时间长'],
  },
  {
    id: 'bj-054', name: '护国寺小吃(总店)', category: 'food', subcategory: '北京小吃',
    city: '北京', district: '西城区', address: '护国寺大街93号',
    lat: 39.929, lng: 116.368, rating: 4.2, reviewCount: 38000, price: 30,
    openTime: '06:00-21:00', tags: ['北京小吃', '豆汁', '焦圈', '老字号'],
    images: ['images/stores/photo-054-1.jpg'],
    description: '北京最具代表性的小吃店，可品尝豆汁、焦圈等地道北京小吃',
    targetAudience: ['游客', '美食爱好者', '本地居民', '老年人'], bestTime: '早餐', duration: '30分钟-1小时',
  },
  {
    id: 'bj-055', name: '庆丰包子铺(西单店)', category: 'food', subcategory: '北京小吃',
    city: '北京', district: '西城区', address: '西单北大街110号',
    lat: 39.91, lng: 116.372, rating: 4.0, reviewCount: 42000, price: 25,
    openTime: '06:00-21:00', tags: ['包子', '北京小吃', '快餐', '老字号'],
    images: ['images/stores/photo-055-1.jpg'],
    description: '北京著名包子连锁品牌，以猪肉大葱包闻名',
    targetAudience: ['游客', '上班族', '本地居民', '快餐需求者'], bestTime: '早餐或午餐', duration: '30分钟',
  },
  {
    id: 'bj-056', name: '海底捞火锅(王府井店)', category: 'food', subcategory: '火锅',
    city: '北京', district: '东城区', address: '王府井大街255号',
    lat: 39.912, lng: 116.41, rating: 4.5, reviewCount: 68000, price: 120,
    openTime: '09:00-07:00', tags: ['火锅', '服务', '24小时', '聚餐'],
    images: ['images/stores/photo-056-1.jpg'],
    description: '以服务著称的火锅连锁品牌，24小时营业',
    targetAudience: ['年轻人', '学生', '夜宵族', '聚餐'], bestTime: '晚餐或夜宵', duration: '2小时',
  },
  {
    id: 'bj-057', name: '东来顺饭庄(王府井店)', category: 'food', subcategory: '涮羊肉',
    city: '北京', district: '东城区', address: '王府井大街198号',
    lat: 39.911, lng: 116.41, rating: 4.2, reviewCount: 32000, price: 130,
    openTime: '10:00-22:00', tags: ['涮羊肉', '老字号', '清真', '中华老字号'],
    images: ['images/stores/photo-057-1.jpg'],
    description: '创立于1903年，中华老字号，以涮羊肉闻名',
    targetAudience: ['游客', '美食爱好者', '家庭聚餐', '商务宴请'], bestTime: '秋冬季节', duration: '1.5-2小时',
  },
  {
    id: 'bj-058', name: '花家怡园(四合院店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '东城区', address: '东直门内大街235号',
    lat: 39.936, lng: 116.428, rating: 4.4, reviewCount: 25000, price: 180,
    openTime: '11:00-22:00', tags: ['四合院', '京菜', '创意菜', '商务宴请'],
    images: ['images/stores/photo-058-1.jpg'],
    description: '在四合院中品尝新派北京菜，环境雅致',
    targetAudience: ['商务宴请', '情侣', '家庭聚餐', '游客'], bestTime: '午餐或晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-059', name: '姚记炒肝店(鼓楼店)', category: 'food', subcategory: '北京小吃',
    city: '北京', district: '东城区', address: '鼓楼东大街311号',
    lat: 39.94, lng: 116.39, rating: 4.1, reviewCount: 28000, price: 25,
    openTime: '06:00-22:00', tags: ['炒肝', '包子', '北京小吃', '老字号'],
    images: ['images/stores/photo-059-1.jpg'],
    description: '北京著名炒肝店，美国副总统拜登曾到访',
    targetAudience: ['游客', '美食爱好者', '本地居民', '早餐者'], bestTime: '早餐或午餐', duration: '30分钟-1小时',
  },
  {
    id: 'bj-060', name: '聚宝源(牛街总店)', category: 'food', subcategory: '涮羊肉',
    city: '北京', district: '西城区', address: '牛街5-2号',
    lat: 39.884, lng: 116.371, rating: 4.5, reviewCount: 45000, price: 110,
    openTime: '11:00-22:00', tags: ['涮羊肉', '清真', '老字号', '排队王'],
    images: ['images/stores/photo-060-1.jpg'],
    description: '牛街最著名的涮肉店，肉质鲜嫩，常年排队',
    targetAudience: ['美食爱好者', '本地居民', '游客', '聚餐'], bestTime: '晚餐', duration: '2小时',
  },

  // ===== 61-70: 更多景点 =====
  {
    id: 'bj-061', name: '北京798艺术区', category: 'attraction', subcategory: '艺术区',
    city: '北京', district: '朝阳区', address: '酒仙桥路4号',
    lat: 39.985, lng: 116.497, rating: 4.4, reviewCount: 89000, price: 0,
    openTime: '全天', tags: ['艺术', '画廊', '工业风', '拍照'],
    images: ['images/stores/photo-061-1.jpg'],
    description: '原国营798厂旧址改造的当代艺术区，北京文化创意地标',
    targetAudience: ['文艺青年', '摄影爱好者', '年轻人', '游客'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'bj-062', name: '红砖美术馆', category: 'attraction', subcategory: '美术馆',
    city: '北京', district: '朝阳区', address: '崔各庄乡何各庄村',
    lat: 40.02, lng: 116.49, rating: 4.5, reviewCount: 22000, price: 120,
    openTime: '10:00-17:30(周一闭馆)', tags: ['当代艺术', '建筑', '园林', '拍照'],
    images: ['images/stores/photo-062-1.jpg'],
    description: '由红砖建造的当代美术馆，建筑本身就是艺术品',
    targetAudience: ['艺术爱好者', '摄影爱好者', '文艺青年', '情侣'], bestTime: '晴朗白天', duration: '2-3小时',
  },
  {
    id: 'bj-063', name: '北京SKP', category: 'attraction', subcategory: '购物中心',
    city: '北京', district: '朝阳区', address: '建国路87号',
    lat: 39.91, lng: 116.475, rating: 4.5, reviewCount: 35000, price: 0,
    openTime: '10:00-22:00', tags: ['奢侈品', '购物', '高端', '商场'],
    images: ['images/stores/photo-063-1.jpg'],
    description: '北京最高端的购物中心，全球店王',
    targetAudience: ['高端消费者', '时尚达人', '商务人士', '游客'], bestTime: '全天', duration: '2-4小时',
  },
  {
    id: 'bj-064', name: '朝阳大悦城', category: 'attraction', subcategory: '购物中心',
    city: '北京', district: '朝阳区', address: '朝阳北路101号',
    lat: 39.923, lng: 116.518, rating: 4.4, reviewCount: 68000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '餐饮', '娱乐', '年轻'],
    images: ['images/stores/photo-064-1.jpg'],
    description: '北京东部最大的商业综合体，深受年轻人喜爱',
    targetAudience: ['年轻人', '学生', '家庭', '情侣'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'bj-065', name: '北京apm', category: 'attraction', subcategory: '购物中心',
    city: '北京', district: '东城区', address: '王府井大街138号',
    lat: 39.912, lng: 116.41, rating: 4.3, reviewCount: 42000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '王府井', '时尚', '餐饮'],
    images: ['images/stores/photo-065-1.jpg'],
    description: '王府井商圈的时尚购物中心，定位年轻潮流',
    targetAudience: ['年轻人', '游客', '购物者', '情侣'], bestTime: '傍晚至夜晚', duration: '2-3小时',
  },
  {
    id: 'bj-066', name: '五棵松华熙LIVE', category: 'attraction', subcategory: '商业街区',
    city: '北京', district: '海淀区', address: '复兴路69号',
    lat: 39.907, lng: 116.275, rating: 4.4, reviewCount: 45000, price: 0,
    openTime: '10:00-22:00', tags: ['夜生活', '餐饮', '娱乐', '音乐'],
    images: ['images/stores/photo-066-1.jpg'],
    description: '北京西部最活跃的夜生活聚集地，有众多餐厅和酒吧',
    targetAudience: ['年轻人', '夜生活爱好者', '情侣', '朋友聚会'], bestTime: '夜晚', duration: '2-4小时',
  },
  {
    id: 'bj-067', name: '北京野生动物园', category: 'attraction', subcategory: '动物园',
    city: '北京', district: '大兴区', address: '榆垡镇万亩森林',
    lat: 39.5, lng: 116.3, rating: 4.5, reviewCount: 38000, price: 150,
    openTime: '08:30-17:30', tags: ['野生动物', '自驾', '亲子', '4A景区'],
    images: ['images/stores/photo-067-1.jpg'],
    description: '可自驾游览的野生动物园，近距离接触各种动物',
    targetAudience: ['亲子', '家庭', '动物爱好者', '情侣'], bestTime: '周末', duration: '一整天',
  },
  {
    id: 'bj-068', name: '古北水镇', category: 'attraction', subcategory: '古镇',
    city: '北京', district: '密云区', address: '古北口镇司马台村',
    lat: 40.65, lng: 117.27, rating: 4.4, reviewCount: 52000, price: 140,
    openTime: '09:00-21:00', tags: ['古镇', '水乡', '夜景', '司马台长城'],
    images: ['images/stores/photo-068-1.jpg'],
    description: '北方罕见的山水城结合的旅游度假景区',
    targetAudience: ['情侣', '家庭', '摄影爱好者', '度假者'], bestTime: '夏季或秋季', duration: '1-2天',
  },
  {
    id: 'bj-069', name: '北京世园公园', category: 'attraction', subcategory: '公园',
    city: '北京', district: '延庆区', address: '延康路',
    lat: 40.44, lng: 115.88, rating: 4.3, reviewCount: 25000, price: 40,
    openTime: '09:00-17:00', tags: ['园艺', '花海', '摄影', '4A景区'],
    images: ['images/stores/photo-069-1.jpg'],
    description: '2019北京世园会会址，现为大型的生态公园',
    targetAudience: ['亲子', '摄影爱好者', '家庭', '园艺爱好者'], bestTime: '春夏两季', duration: '半天',
  },
  {
    id: 'bj-070', name: '北京园博园', category: 'attraction', subcategory: '公园',
    city: '北京', district: '丰台区', address: '射击场路15号',
    lat: 39.87, lng: 116.2, rating: 4.2, reviewCount: 28000, price: 20,
    openTime: '07:00-19:00', tags: ['园林', '赏花', '亲子', '4A景区'],
    images: ['images/stores/photo-070-1.jpg'],
    description: '第九届中国国际园林博览会举办地，汇集各地园林精华',
    targetAudience: ['亲子', '摄影爱好者', '本地居民', '游客'], bestTime: '春季', duration: '半天',
  },

  // ===== 71-80: 更多美食 =====
  {
    id: 'bj-071', name: '大董烤鸭店(王府井店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '东城区', address: '王府井大街301号',
    lat: 39.91, lng: 116.41, rating: 4.5, reviewCount: 22000, price: 300,
    openTime: '11:00-22:00', tags: ['烤鸭', '创意菜', '高端', '商务宴请'],
    images: ['images/stores/photo-071-1.jpg'],
    description: '大董创始人董振祥开创的"酥不腻"烤鸭，定位高端',
    targetAudience: ['商务宴请', '高端消费者', '美食爱好者', '情侣'], bestTime: '晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-072', name: '小吊梨汤(团结湖店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '朝阳区', address: '团结湖路7号',
    lat: 39.925, lng: 116.465, rating: 4.4, reviewCount: 32000, price: 90,
    openTime: '11:00-21:30', tags: ['京菜', '梨汤', '家常菜', '亲子'],
    images: ['images/stores/photo-072-1.jpg'],
    description: '以梨汤闻名的京菜馆，菜品精致，适合家庭聚餐',
    targetAudience: ['家庭', '亲子', '本地居民', '游客'], bestTime: '午餐或晚餐', duration: '1.5小时',
    ugcTags: ['梨汤好喝', '京味正宗', '老少皆宜', '排队久', '上菜慢', '停车难'],
    ugcSummary: '一壶小吊梨汤温润甘甜确实名不虚传，菜品也地道。但节假日排队太可怕了，周围停车也是个大问题',
    riskTags: ['节假日排队1小时+', '周边停车位极少', '上菜速度慢'],
  },
  {
    id: 'bj-073', name: '局气(德云社店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '西城区', address: '北纬路甲1号',
    lat: 39.883, lng: 116.39, rating: 4.3, reviewCount: 28000, price: 100,
    openTime: '11:00-22:00', tags: ['京菜', '创意', '德云社', '文化'],
    images: ['images/stores/photo-073-1.jpg'],
    description: '与德云社合作的京菜馆，装修充满老北京元素',
    targetAudience: ['年轻人', '德云社粉丝', '游客', '家庭'], bestTime: '晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-074', name: '西贝莜面村(王府井店)', category: 'food', subcategory: '西北菜',
    city: '北京', district: '东城区', address: '王府井大街255号',
    lat: 39.912, lng: 116.41, rating: 4.3, reviewCount: 35000, price: 90,
    openTime: '11:00-21:30', tags: ['西北菜', '莜面', '亲子', '家庭'],
    images: ['images/stores/photo-074-1.jpg'],
    description: '知名西北菜连锁品牌，以莜面和牛羊肉闻名',
    targetAudience: ['家庭', '亲子', '上班族', '游客'], bestTime: '午餐或晚餐', duration: '1小时',
  },
  {
    id: 'bj-075', name: '外婆家(朝阳大悦城店)', category: 'food', subcategory: '江浙菜',
    city: '北京', district: '朝阳区', address: '朝阳北路101号',
    lat: 39.923, lng: 116.518, rating: 4.2, reviewCount: 28000, price: 70,
    openTime: '10:30-21:30', tags: ['江浙菜', '性价比', '家庭', '商场'],
    images: ['images/stores/photo-075-1.jpg'],
    description: '知名江浙菜连锁，性价比高，适合家庭聚餐',
    targetAudience: ['家庭', '学生', '上班族', '情侣'], bestTime: '午餐或晚餐', duration: '1小时',
    ugcTags: ['性价比高', '上菜快', '适合家庭', '排队久', '环境一般', '味道普通'],
    ugcSummary: '性价比确实高，但周末排队至少40分钟，环境像大食堂比较嘈杂，菜品口味中规中矩没啥惊艳',
    riskTags: ['周末排队久', '环境嘈杂', '高峰时段限时就餐'],
  },
  {
    id: 'bj-076', name: '胡大饭馆(簋街总店)', category: 'food', subcategory: '川菜',
    city: '北京', district: '东城区', address: '东直门内大街233号',
    lat: 39.936, lng: 116.428, rating: 4.4, reviewCount: 52000, price: 120,
    openTime: '11:00-05:00', tags: ['小龙虾', '川菜', '夜宵', '排队王'],
    images: ['images/stores/photo-076-1.jpg'],
    description: '簋街最著名的龙虾店，北京夜宵文化的代表',
    targetAudience: ['年轻人', '夜宵族', '朋友聚会', '情侣'], bestTime: '晚餐或夜宵', duration: '2小时',
    ugcTags: ['麻小一绝', '深夜营业', '簋街地标', '排队吓人', '等号等到崩溃', '环境嘈杂'],
    ugcSummary: '北京的夜宵之王，麻辣小龙虾配啤酒是夏天标配，凌晨5点还营业太良心了。但排号200+是常态，建议工作日晚上10点后再来',
    riskTags: ['排队200+号', '深夜周边交通不便', '环境嘈杂卫生一般'],
  },
  {
    id: 'bj-077', name: '丰泽园饭庄(珠市口店)', category: 'food', subcategory: '鲁菜',
    city: '北京', district: '西城区', address: '珠市口西大街83号',
    lat: 39.885, lng: 116.39, rating: 4.3, reviewCount: 18000, price: 180,
    openTime: '11:00-21:00', tags: ['鲁菜', '老字号', '葱烧海参', '商务宴请'],
    images: ['images/stores/photo-077-1.jpg'],
    description: '中华老字号鲁菜馆，以葱烧海参闻名京城',
    targetAudience: ['商务宴请', '美食爱好者', '家庭聚餐', '游客'], bestTime: '午餐或晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-078', name: '鼎泰丰(国贸店)', category: 'food', subcategory: '台湾菜',
    city: '北京', district: '朝阳区', address: '建国路88号',
    lat: 39.908, lng: 116.455, rating: 4.5, reviewCount: 25000, price: 120,
    openTime: '10:00-22:00', tags: ['小笼包', '台湾菜', '精致', '米其林'],
    images: ['images/stores/photo-078-1.jpg'],
    description: '源自台湾的米其林星级餐厅，以小笼包闻名',
    targetAudience: ['美食爱好者', '商务人士', '情侣', '家庭'], bestTime: '午餐或晚餐', duration: '1.5小时',
    ugcTags: ['小笼包正宗', '服务优秀', '环境雅致', '适合约会', '上菜有序', '价格小贵'],
    ugcSummary: '18摺小笼包皮薄汤鲜名不虚传，服务生训练有素，环境安静雅致特别适合商务宴请和约会',
    riskTags: [],
  },
  {
    id: 'bj-079', name: 'Shake Shack(三里屯店)', category: 'food', subcategory: '西餐',
    city: '北京', district: '朝阳区', address: '三里屯路19号',
    lat: 39.935, lng: 116.455, rating: 4.2, reviewCount: 18000, price: 80,
    openTime: '10:00-22:00', tags: ['汉堡', '美式', '网红', '快餐'],
    images: ['images/stores/photo-079-1.jpg'],
    description: '来自纽约的网红汉堡店，北京首店',
    targetAudience: ['年轻人', '外国游客', '情侣', '快餐爱好者'], bestTime: '午餐或晚餐', duration: '1小时',
    ugcTags: ['汉堡好吃', '氛围轻松', '出片好看', '价格偏高', '排队太久', '座位难找'],
    ugcSummary: '牛肉汉堡确实比普通快餐好吃很多，但人均80买个汉堡还是有点肉疼，周末找座位像打仗',
    riskTags: ['周末排队超30分钟', '高峰无座需外带', '价格与份量不成正比'],
  },
  {
    id: 'bj-080', name: '京A Taproom(隆福寺店)', category: 'food', subcategory: '酒吧',
    city: '北京', district: '东城区', address: '隆福寺街95号',
    lat: 39.92, lng: 116.42, rating: 4.4, reviewCount: 15000, price: 100,
    openTime: '11:00-02:00', tags: ['精酿啤酒', '西餐', '夜生活', '社交'],
    images: ['images/stores/photo-080-1.jpg'],
    description: '北京本土精酿啤酒品牌，氛围轻松休闲',
    targetAudience: ['年轻人', '精酿爱好者', '外国游客', '朋友聚会'], bestTime: '傍晚至深夜', duration: '2-3小时',
  },

  // ===== 81-90: 补充景点 =====
  {
    id: 'bj-081', name: '北京大观园', category: 'attraction', subcategory: '园林景观',
    city: '北京', district: '西城区', address: '南菜园街12号',
    lat: 39.87, lng: 116.35, rating: 4.2, reviewCount: 28000, price: 40,
    openTime: '07:30-18:00', tags: ['红楼梦', '园林', '影视基地', '4A景区'],
    images: ['images/stores/photo-081-1.jpg'],
    description: '以《红楼梦》为蓝本建造的仿古园林',
    targetAudience: ['红楼梦粉丝', '游客', '摄影爱好者', '文化爱好者'], bestTime: '春季', duration: '2-3小时',
  },
  {
    id: 'bj-082', name: '北京汽车博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '丰台区', address: '南四环西路126号',
    lat: 39.83, lng: 116.28, rating: 4.4, reviewCount: 22000, price: 30,
    openTime: '09:00-17:00(周一闭馆)', tags: ['汽车', '科技', '亲子', '4A景区'],
    images: ['images/stores/photo-082-1.jpg'],
    description: '中国首家国家级汽车博物馆，展示汽车发展史',
    targetAudience: ['亲子', '汽车爱好者', '学生', '家庭'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'bj-083', name: '北京欢乐水魔方', category: 'attraction', subcategory: '水上乐园',
    city: '北京', district: '丰台区', address: '小屯路11号',
    lat: 39.865, lng: 116.25, rating: 4.3, reviewCount: 25000, price: 200,
    openTime: '10:00-18:00', tags: ['水上乐园', '亲子', '夏日', '刺激'],
    images: ['images/stores/photo-083-1.jpg'],
    description: '北京最大的户外水上乐园，夏季消暑好去处',
    targetAudience: ['亲子', '年轻人', '学生', '家庭'], bestTime: '夏季', duration: '一整天',
  },
  {
    id: 'bj-084', name: '北京西山国家森林公园', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '海淀区', address: '闵庄路与香山南路交叉口',
    lat: 39.98, lng: 116.2, rating: 4.4, reviewCount: 18000, price: 10,
    openTime: '07:00-18:00', tags: ['森林', '登山', '赏花', '4A景区'],
    images: ['images/stores/photo-084-1.jpg'],
    description: '北京最近的森林公园，有鬼笑石可俯瞰北京夜景',
    targetAudience: ['登山爱好者', '摄影爱好者', '本地居民', '情侣'], bestTime: '秋季', duration: '半天',
  },
  {
    id: 'bj-085', name: '北京中华民族园', category: 'attraction', subcategory: '文化景区',
    city: '北京', district: '朝阳区', address: '民族园路1号',
    lat: 39.98, lng: 116.39, rating: 4.1, reviewCount: 15000, price: 90,
    openTime: '08:30-17:00', tags: ['民族文化', '建筑', '亲子', '4A景区'],
    images: ['images/stores/photo-085-1.jpg'],
    description: '展示中国56个民族的建筑、文化和风俗',
    targetAudience: ['亲子', '学生', '文化爱好者', '游客'], bestTime: '春夏两季', duration: '半天',
  },
  {
    id: 'bj-086', name: '北京天文馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '西城区', address: '西直门外大街138号',
    lat: 39.938, lng: 116.338, rating: 4.5, reviewCount: 35000, price: 10,
    openTime: '09:00-16:30(周一闭馆)', tags: ['天文', '科普', '亲子', '4A景区'],
    images: ['images/stores/photo-086-1.jpg'],
    description: '中国第一座大型天文馆，拥有天象厅和天文展厅',
    targetAudience: ['亲子', '学生', '天文爱好者', '家庭'], bestTime: '周末', duration: '2-3小时',
  },
  {
    id: 'bj-087', name: '北京海洋馆', category: 'attraction', subcategory: '水族馆',
    city: '北京', district: '海淀区', address: '高粱桥斜街乙18号',
    lat: 39.942, lng: 116.338, rating: 4.5, reviewCount: 52000, price: 170,
    openTime: '09:00-17:30', tags: ['海洋馆', '海豚表演', '亲子', '4A景区'],
    images: ['images/stores/photo-087-1.jpg'],
    description: '亚洲第一、世界内陆最大、设施最先进的海洋馆',
    targetAudience: ['亲子', '家庭', '情侣', '学生'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'bj-088', name: '北京世界公园', category: 'attraction', subcategory: '主题公园',
    city: '北京', district: '丰台区', address: '花乡大葆台158号',
    lat: 39.81, lng: 116.28, rating: 4.0, reviewCount: 22000, price: 100,
    openTime: '08:30-17:30', tags: ['微缩景观', '世界名胜', '亲子', '4A景区'],
    images: ['images/stores/photo-088-1.jpg'],
    description: '展示世界各地著名景观的微缩主题公园',
    targetAudience: ['亲子', '学生', '游客', '家庭'], bestTime: '春夏两季', duration: '半天',
  },
  {
    id: 'bj-089', name: '北京植物园温室', category: 'attraction', subcategory: '公园',
    city: '北京', district: '海淀区', address: '香山卧佛寺路',
    lat: 40.0, lng: 116.208, rating: 4.4, reviewCount: 18000, price: 50,
    openTime: '08:00-16:30', tags: ['温室', '热带植物', '科普', '亲子'],
    images: ['images/stores/photo-089-1.jpg'],
    description: '亚洲最大的植物展览温室，展示热带和亚热带植物',
    targetAudience: ['亲子', '植物爱好者', '学生', '摄影爱好者'], bestTime: '冬季', duration: '2小时',
  },
  {
    id: 'bj-090', name: '北京凤凰岭', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '海淀区', address: '苏家坨镇凤凰岭路',
    lat: 40.08, lng: 116.08, rating: 4.3, reviewCount: 15000, price: 25,
    openTime: '07:00-17:30', tags: ['登山', '道教', '自然', '4A景区'],
    images: ['images/stores/photo-090-1.jpg'],
    description: '有"京西小黄山"之称，以奇峰、怪石、林海、神泉闻名',
    targetAudience: ['登山爱好者', '道教信众', '摄影爱好者', '本地居民'], bestTime: '秋季', duration: '半天',
  },

  // ===== 91-100: 补充美食 =====
  {
    id: 'bj-091', name: '稻香村(第零营业部)', category: 'food', subcategory: '糕点',
    city: '北京', district: '东城区', address: '东直门内大街19号',
    lat: 39.936, lng: 116.428, rating: 4.5, reviewCount: 38000, price: 50,
    openTime: '08:30-20:00', tags: ['糕点', '老字号', '伴手礼', '北京特产'],
    images: ['images/stores/photo-091-1.jpg'],
    description: '中华老字号，北京最著名的糕点品牌，必买伴手礼',
    targetAudience: ['游客', '本地居民', '送礼者', '老年人'], bestTime: '全天', duration: '30分钟',
  },
  {
    id: 'bj-092', name: '吴裕泰茶庄(前门大街店)', category: 'food', subcategory: '茶饮',
    city: '北京', district: '东城区', address: '前门大街42号',
    lat: 39.899, lng: 116.398, rating: 4.4, reviewCount: 22000, price: 30,
    openTime: '08:30-21:00', tags: ['茶叶', '花茶', '老字号', '冰淇淋'],
    images: ['images/stores/photo-092-1.jpg'],
    description: '百年茶庄，以茉莉花茶闻名，也卖网红花茶冰淇淋',
    targetAudience: ['游客', '茶文化爱好者', '年轻人', '本地居民'], bestTime: '全天', duration: '30分钟',
  },
  {
    id: 'bj-093', name: '北新桥卤煮老店', category: 'food', subcategory: '北京小吃',
    city: '北京', district: '东城区', address: '东四北大街141号',
    lat: 39.935, lng: 116.415, rating: 4.2, reviewCount: 18000, price: 30,
    openTime: '10:00-22:00', tags: ['卤煮', '北京小吃', '老字号', '夜宵'],
    images: ['images/stores/photo-093-1.jpg'],
    description: '北京最著名的卤煮店之一，地道的北京风味',
    targetAudience: ['美食爱好者', '本地居民', '游客', '夜宵族'], bestTime: '晚餐或夜宵', duration: '30分钟-1小时',
  },
  {
    id: 'bj-094', name: '文宇奶酪店(南锣鼓巷店)', category: 'food', subcategory: '甜品',
    city: '北京', district: '东城区', address: '南锣鼓巷49号',
    lat: 39.932, lng: 116.401, rating: 4.3, reviewCount: 25000, price: 20,
    openTime: '09:00-22:00', tags: ['奶酪', '宫廷奶酪', '甜品', '网红'],
    images: ['images/stores/photo-094-1.jpg'],
    description: '南锣鼓巷网红甜品店，以宫廷奶酪闻名',
    targetAudience: ['年轻人', '游客', '情侣', '甜品爱好者'], bestTime: '下午', duration: '30分钟',
  },
  {
    id: 'bj-095', name: '海碗居(增光路店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '海淀区', address: '增光路11号',
    lat: 39.923, lng: 116.337, rating: 4.2, reviewCount: 22000, price: 60,
    openTime: '10:30-21:30', tags: ['炸酱面', '北京菜', '老字号', '家常'],
    images: ['images/stores/photo-095-1.jpg'],
    description: '以正宗老北京炸酱面闻名的老字号餐馆',
    targetAudience: ['游客', '本地居民', '美食爱好者', '家庭'], bestTime: '午餐或晚餐', duration: '1小时',
    ugcTags: ['炸酱面地道', '量大实惠', '老北京味道', '服务冷淡', '环境老旧', '不能手机点单'],
    ugcSummary: '炸酱面的酱是现炸的，面条筋道配菜也全，一碗下去超满足。但服务员都是阿姨级别的，态度比较冷淡，环境也是老派装修',
    riskTags: [],
  },
  {
    id: 'bj-096', name: '眉州东坡(王府井店)', category: 'food', subcategory: '川菜',
    city: '北京', district: '东城区', address: '王府井大街88号',
    lat: 39.912, lng: 116.41, rating: 4.3, reviewCount: 28000, price: 110,
    openTime: '11:00-22:00', tags: ['川菜', '东坡肉', '商务', '家庭'],
    images: ['images/stores/photo-096-1.jpg'],
    description: '知名川菜连锁品牌，以东坡系列菜品闻名',
    targetAudience: ['商务宴请', '家庭聚餐', '美食爱好者', '游客'], bestTime: '午餐或晚餐', duration: '1.5小时',
  },
  {
    id: 'bj-097', name: '和府捞面(国贸店)', category: 'food', subcategory: '面食',
    city: '北京', district: '朝阳区', address: '建国路88号',
    lat: 39.908, lng: 116.455, rating: 4.2, reviewCount: 15000, price: 40,
    openTime: '10:00-22:00', tags: ['面食', '书房', '快餐', '一人食'],
    images: ['images/stores/photo-097-1.jpg'],
    description: '以"书房里的养生面"为特色的面食连锁品牌',
    targetAudience: ['上班族', '学生', '一人食', '快餐需求者'], bestTime: '午餐或晚餐', duration: '30分钟-1小时',
    ugcTags: ['一人食友好', '面汤浓郁', '环境安静', '份量偏少', '价格偏高', '品类单一'],
    ugcSummary: '书房环境确实安静舒服，一个人来吃很自在，但40块一碗面国贸上班族也喊贵，而且份量对男生来说不太够',
    riskTags: [],
  },
  {
    id: 'bj-098', name: '喜茶(三里屯店)', category: 'food', subcategory: '茶饮',
    city: '北京', district: '朝阳区', address: '三里屯路19号',
    lat: 39.935, lng: 116.455, rating: 4.2, reviewCount: 22000, price: 30,
    openTime: '10:00-22:00', tags: ['奶茶', '网红', '排队', '社交'],
    images: ['images/stores/photo-098-1.jpg'],
    description: '知名新式茶饮品牌，以芝士茶闻名',
    targetAudience: ['年轻人', '学生', '情侣', '白领'], bestTime: '下午', duration: '30分钟',
    ugcTags: ['多肉葡萄好喝', '出杯快', '小程序方便', '排队久', '太吵', '座位少'],
    ugcSummary: '小程序提前下单能省不少时间，但店里永远人山人海吵得像菜市场，想找个座位坐下来喝基本不可能',
    riskTags: ['店内无座', '高峰出杯慢'],
  },
  {
    id: 'bj-099', name: '星巴克臻选(北京坊店)', category: 'food', subcategory: '咖啡',
    city: '北京', district: '西城区', address: '煤市街廊房头条21号',
    lat: 39.9, lng: 116.397, rating: 4.4, reviewCount: 18000, price: 50,
    openTime: '07:00-23:00', tags: ['咖啡', '臻选', '第三空间', '商务'],
    images: ['images/stores/photo-099-1.jpg'],
    description: '星巴克臻选旗舰店，提供高品质咖啡体验',
    targetAudience: ['商务人士', '咖啡爱好者', '游客', '白领'], bestTime: '上午或下午', duration: '1-2小时',
  },
  {
    id: 'bj-100', name: '悠唐购物中心', category: 'attraction', subcategory: '购物中心',
    city: '北京', district: '朝阳区', address: '三丰北里2号',
    lat: 39.92, lng: 116.435, rating: 4.2, reviewCount: 28000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '餐饮', '娱乐', '亲子'],
    images: ['images/stores/photo-100-1.jpg'],
    description: '朝阳门商圈的大型购物中心，定位年轻时尚',
    targetAudience: ['年轻人', '家庭', '购物者', '情侣'], bestTime: '周末', duration: '半天',
  },

  // ===== 101-110: 更多景点补充 =====
  {
    id: 'bj-101', name: '北京雁栖湖', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '怀柔区', address: '怀北镇雁水路3号',
    lat: 40.4, lng: 116.65, rating: 4.3, reviewCount: 20000, price: 45,
    openTime: '08:00-17:00', tags: ['湖泊', 'APEC会址', '水上项目', '4A景区'],
    images: ['images/stores/photo-101-1.jpg'],
    description: 'APEC峰会举办地，湖光山色，可体验水上项目',
    targetAudience: ['家庭', '亲子', '游客', '团建'], bestTime: '夏季', duration: '半天',
  },
  {
    id: 'bj-102', name: '北京青龙峡', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '怀柔区', address: '怀北镇大水峪村',
    lat: 40.45, lng: 116.68, rating: 4.3, reviewCount: 18000, price: 54,
    openTime: '08:00-17:00', tags: ['峡谷', '蹦极', '长城', '4A景区'],
    images: ['images/stores/photo-102-1.jpg'],
    description: '集青山、绿水、古长城于一体的自然风景区',
    targetAudience: ['户外爱好者', '年轻人', '亲子', '摄影爱好者'], bestTime: '夏季', duration: '半天',
  },
  {
    id: 'bj-103', name: '北京潭柘寺', category: 'attraction', subcategory: '宗教场所',
    city: '北京', district: '门头沟区', address: '潭柘寺镇',
    lat: 39.9, lng: 116.02, rating: 4.5, reviewCount: 25000, price: 55,
    openTime: '08:00-16:30', tags: ['佛教', '古刹', '祈福', '4A景区'],
    images: ['images/stores/photo-103-1.jpg'],
    description: '北京最古老的寺庙，有"先有潭柘寺，后有北京城"之说',
    targetAudience: ['信众', '文化爱好者', '游客', '祈福者'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'bj-104', name: '北京戒台寺', category: 'attraction', subcategory: '宗教场所',
    city: '北京', district: '门头沟区', address: '马鞍山麓',
    lat: 39.88, lng: 116.0, rating: 4.4, reviewCount: 15000, price: 45,
    openTime: '08:00-17:00', tags: ['佛教', '古刹', '牡丹', '4A景区'],
    images: ['images/stores/photo-104-1.jpg'],
    description: '以戒坛和古松闻名，春季牡丹盛开',
    targetAudience: ['信众', '摄影爱好者', '文化爱好者', '游客'], bestTime: '春季(牡丹季)', duration: '2-3小时',
  },
  {
    id: 'bj-105', name: '北京银山塔林', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '昌平区', address: '延寿镇西湖村',
    lat: 40.25, lng: 116.35, rating: 4.3, reviewCount: 12000, price: 20,
    openTime: '08:00-16:30', tags: ['古塔', '登山', '历史', '4A景区'],
    images: ['images/stores/photo-105-1.jpg'],
    description: '保存最完好的金代塔群，有"银山宝塔数不尽"之说',
    targetAudience: ['历史爱好者', '登山爱好者', '摄影爱好者', '游客'], bestTime: '秋季', duration: '半天',
  },
  {
    id: 'bj-106', name: '北京居庸关长城', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '昌平区', address: '南口镇居庸关村',
    lat: 40.29, lng: 116.07, rating: 4.5, reviewCount: 35000, price: 40,
    openTime: '08:30-16:30', tags: ['长城', '云台', '花海', '4A景区'],
    images: ['images/stores/photo-106-1.jpg'],
    description: '长城重要关隘，春季山花烂漫，有"居庸叠翠"之称',
    targetAudience: ['游客', '摄影爱好者', '登山爱好者', '历史爱好者'], bestTime: '春季', duration: '半天',
  },
  {
    id: 'bj-107', name: '北京黄花城水长城', category: 'attraction', subcategory: '历史古迹',
    city: '北京', district: '怀柔区', address: '九渡河镇西水峪村',
    lat: 40.45, lng: 116.35, rating: 4.4, reviewCount: 18000, price: 60,
    openTime: '08:00-17:00', tags: ['长城', '水上长城', '赏花', '4A景区'],
    images: ['images/stores/photo-107-1.jpg'],
    description: '长城入水的奇特景观，可划船游览',
    targetAudience: ['游客', '摄影爱好者', '亲子', '情侣'], bestTime: '春夏两季', duration: '半天',
  },
  {
    id: 'bj-108', name: '北京坡峰岭', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '房山区', address: '周口店镇黄山店村',
    lat: 39.7, lng: 115.95, rating: 4.3, reviewCount: 15000, price: 50,
    openTime: '08:00-17:00', tags: ['红叶', '登山', '乡村', '4A景区'],
    images: ['images/stores/photo-108-1.jpg'],
    description: '以红叶闻名的山村景区，秋季景色绝美',
    targetAudience: ['摄影爱好者', '登山爱好者', '亲子', '游客'], bestTime: '秋季', duration: '半天',
  },
  {
    id: 'bj-109', name: '北京金海湖', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '平谷区', address: '韩庄镇海子村',
    lat: 40.2, lng: 117.3, rating: 4.2, reviewCount: 15000, price: 40,
    openTime: '08:00-17:00', tags: ['湖泊', '水上运动', '露营', '4A景区'],
    images: ['images/stores/photo-109-1.jpg'],
    description: '北京第三大水库，可体验帆船、皮划艇等水上运动',
    targetAudience: ['户外爱好者', '亲子', '年轻人', '团建'], bestTime: '夏季', duration: '半天至一天',
  },
  {
    id: 'bj-110', name: '北京石林峡', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '平谷区', address: '黄松峪乡雕窝村',
    lat: 40.25, lng: 117.25, rating: 4.3, reviewCount: 18000, price: 78,
    openTime: '07:30-17:00', tags: ['峡谷', '玻璃栈道', '瀑布', '4A景区'],
    images: ['images/stores/photo-110-1.jpg'],
    description: '以石林和UFO玻璃观景台闻名的峡谷景区',
    targetAudience: ['年轻人', '亲子', '摄影爱好者', '户外爱好者'], bestTime: '夏季', duration: '半天',
  },

  // ===== 111-120: 最后补充 =====
  {
    id: 'bj-111', name: '北京周口店遗址', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '房山区', address: '周口店镇龙骨山',
    lat: 39.68, lng: 115.93, rating: 4.2, reviewCount: 12000, price: 30,
    openTime: '09:00-16:30(周一闭馆)', tags: ['世界遗产', '古人类', '考古', '科普'],
    images: ['images/stores/photo-111-1.jpg'],
    description: '北京人遗址，世界文化遗产',
    targetAudience: ['学生', '历史爱好者', '亲子', '科普爱好者'], bestTime: '工作日', duration: '2-3小时',
  },
  {
    id: 'bj-112', name: '北京云居寺', category: 'attraction', subcategory: '宗教场所',
    city: '北京', district: '房山区', address: '南尚乐村水头村',
    lat: 39.6, lng: 115.85, rating: 4.3, reviewCount: 10000, price: 40,
    openTime: '08:30-16:30', tags: ['佛教', '石经', '古刹', '4A景区'],
    images: ['images/stores/photo-112-1.jpg'],
    description: '以珍藏石刻佛教大藏经闻名于世',
    targetAudience: ['信众', '文化爱好者', '历史爱好者', '游客'], bestTime: '春秋两季', duration: '2-3小时',
  },
  {
    id: 'bj-113', name: '北京白草畔', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '房山区', address: '霞云岭乡四马台村',
    lat: 39.75, lng: 115.7, rating: 4.2, reviewCount: 8000, price: 40,
    openTime: '08:00-17:00', tags: ['高山草甸', '避暑', '云海', '4A景区'],
    images: ['images/stores/photo-113-1.jpg'],
    description: '北京第三高峰，夏季避暑胜地',
    targetAudience: ['登山爱好者', '摄影爱好者', '避暑者', '户外爱好者'], bestTime: '夏季', duration: '半天',
  },
  {
    id: 'bj-114', name: '北京百花山', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '门头沟区', address: '清水镇',
    lat: 39.85, lng: 115.6, rating: 4.3, reviewCount: 10000, price: 40,
    openTime: '08:00-17:00', tags: ['高山草甸', '野花', '避暑', '4A景区'],
    images: ['images/stores/photo-114-1.jpg'],
    description: '以高山草甸和野花闻名的自然保护区',
    targetAudience: ['登山爱好者', '摄影爱好者', '避暑者', '亲子'], bestTime: '夏季', duration: '半天',
  },
  {
    id: 'bj-115', name: '北京妙峰山', category: 'attraction', subcategory: '宗教场所',
    city: '北京', district: '门头沟区', address: '涧沟村',
    lat: 39.95, lng: 116.0, rating: 4.3, reviewCount: 15000, price: 40,
    openTime: '08:00-17:00', tags: ['道教', '娘娘庙', '庙会', '登山'],
    images: ['images/stores/photo-115-1.jpg'],
    description: '以娘娘庙和庙会闻名，春季有传统庙会',
    targetAudience: ['信众', '文化爱好者', '登山爱好者', '游客'], bestTime: '春季(庙会期间)', duration: '半天',
  },
  {
    id: 'bj-116', name: '北京圣莲山', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '房山区', address: '史家营乡柳林水村',
    lat: 39.85, lng: 115.75, rating: 4.2, reviewCount: 8000, price: 60,
    openTime: '08:00-17:00', tags: ['道教', '登山', '道观', '4A景区'],
    images: ['images/stores/photo-116-1.jpg'],
    description: '道教名山，有"京西小五岳"之称',
    targetAudience: ['道教信众', '登山爱好者', '摄影爱好者', '游客'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'bj-117', name: '北京野鸭湖', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '延庆区', address: '康庄镇刘浩营村西',
    lat: 40.38, lng: 115.88, rating: 4.2, reviewCount: 10000, price: 50,
    openTime: '08:30-17:00', tags: ['湿地', '观鸟', '摄影', '4A景区'],
    images: ['images/stores/photo-117-1.jpg'],
    description: '北京最大的湿地自然保护区，候鸟栖息地',
    targetAudience: ['观鸟爱好者', '摄影爱好者', '亲子', '自然爱好者'], bestTime: '春秋两季(候鸟迁徙)', duration: '半天',
  },
  {
    id: 'bj-118', name: '北京松山', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '延庆区', address: '张山营镇',
    lat: 40.5, lng: 115.8, rating: 4.3, reviewCount: 10000, price: 50,
    openTime: '08:00-17:00', tags: ['森林', '温泉', '避暑', '4A景区'],
    images: ['images/stores/photo-118-1.jpg'],
    description: '以天然油松林和温泉闻名的自然保护区',
    targetAudience: ['避暑者', '登山爱好者', '亲子', '自然爱好者'], bestTime: '夏季', duration: '半天至一天',
  },
  {
    id: 'bj-119', name: '北京碓臼峪', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '昌平区', address: '长陵镇碓臼峪村',
    lat: 40.3, lng: 116.25, rating: 4.1, reviewCount: 5000, price: 20,
    openTime: '08:00-17:00', tags: ['峡谷', '溪流', '避暑', '3A景区'],
    images: ['images/stores/photo-119-1.jpg'],
    description: '以峡谷溪流和怪石闻名的自然风景区',
    targetAudience: ['避暑者', '亲子', '本地居民', '户外爱好者'], bestTime: '夏季', duration: '半天',
  },
  {
    id: 'bj-120', name: '北京七渡花果山', category: 'attraction', subcategory: '主题乐园',
    city: '北京', district: '房山区', address: '十渡镇七渡村',
    lat: 39.65, lng: 115.55, rating: 4.0, reviewCount: 8000, price: 45,
    openTime: '08:00-17:00', tags: ['猕猴', '自然', '亲子', '3A景区'],
    images: ['images/stores/photo-120-1.jpg'],
    description: '以野生猕猴群闻名的自然景区',
    targetAudience: ['亲子', '家庭', '动物爱好者', '游客'], bestTime: '春夏两季', duration: '半天',
  },
  // ═══════════════════════════════════════════
  // 新增 80 POI (bj-121 ~ bj-200): 40 美食 + 40 景点
  // ═══════════════════════════════════════════
  // ── 美食 (bj-121 ~ bj-160) ──
  {
    id: 'bj-121', name: '将太无二(蓝色港湾店)', category: 'food', subcategory: '日料',
    city: '北京', district: '朝阳区', address: '朝阳公园路6号蓝色港湾',
    lat: 39.951, lng: 116.475, rating: 4.6, reviewCount: 8500, price: 160,
    openTime: '11:00-22:00', tags: ['日料', '寿司', '刺身', '约会', '品质'],
    images: ['images/stores/photo-121-1.jpg'],
    description: '北京知名日料品牌，食材新鲜，环境优雅，适合约会和商务宴请',
    targetAudience: ['商务人士', '情侣', '日料爱好者', '朋友聚会'], bestTime: '午餐或晚餐', duration: '1-2小时',
    ugcTags: ['刺身新鲜', '环境安静', '服务周到', '适合约会', '价格偏高', '份量偏小'],
    ugcSummary: '秋天的童话卷确实惊艳，刺身新鲜度在京城算一流。环境私密安静，约会选这里不会翻车，就是价格对普通打工人不太友好',
    riskTags: [],
  },
  {
    id: 'bj-122', name: '姜虎东白丁烤肉(三里屯店)', category: 'food', subcategory: '韩餐',
    city: '北京', district: '朝阳区', address: '三里屯路19号太古里南区',
    lat: 39.933, lng: 116.456, rating: 4.5, reviewCount: 12000, price: 130,
    openTime: '11:00-23:00', tags: ['韩餐', '烤肉', '韩流', '聚会', '网红'],
    images: ['images/stores/photo-122-1.jpg'],
    description: '韩国人气烤肉品牌，正宗韩式风味，年轻人聚会首选',
    targetAudience: ['年轻人', '韩流粉丝', '朋友聚会', '情侣'], bestTime: '晚餐', duration: '1.5-2小时',
    ugcTags: ['烤肉好吃', '氛围热闹', '小菜无限续', '适合聚会', '排队久', '油烟味大', '太吵'],
    ugcSummary: '五花肉烤得滋滋冒油太满足了，小菜无限续很良心，氛围超适合朋友聚会。但油烟味真的很重吃完一身味，而且永远在排队',
    riskTags: ['油烟味重', '排队时间长', '环境嘈杂不适合安静约会'],
  },
  {
    id: 'bj-123', name: '很久以前羊肉串(簋街店)', category: 'food', subcategory: '烧烤',
    city: '北京', district: '东城区', address: '东直门内大街181号',
    lat: 39.939, lng: 116.426, rating: 4.4, reviewCount: 20000, price: 90,
    openTime: '11:00-02:00', tags: ['烧烤', '羊肉串', '深夜食堂', '聚会', '人气'],
    images: ['images/stores/photo-123-1.jpg'],
    description: '北京人气烧烤连锁店，呼伦贝尔草原羊肉，营业到凌晨',
    targetAudience: ['年轻人', '朋友聚会', '夜宵爱好者', '游客'], bestTime: '晚餐或夜宵', duration: '1-2小时',
  },
  {
    id: 'bj-124', name: '火烧云傣家菜(蓝色港湾店)', category: 'food', subcategory: '云南菜',
    city: '北京', district: '朝阳区', address: '朝阳公园路6号蓝色港湾',
    lat: 39.949, lng: 116.474, rating: 4.7, reviewCount: 15000, price: 100,
    openTime: '11:00-22:00', tags: ['云南菜', '傣味', '酸辣', '网红', '排队'],
    images: ['images/stores/photo-124-1.jpg'],
    description: '京城最火的云南菜馆，铜锅油焖鸡是招牌，常年排队',
    targetAudience: ['年轻人', '美食爱好者', '朋友聚会', '情侣'], bestTime: '晚餐', duration: '1-1.5小时',
    ugcTags: ['油焖鸡一绝', '酸辣开胃', '拍照好看', '排队太久', '服务一般', '不能预约'],
    ugcSummary: '铜锅油焖鸡配米饭绝了，酸辣口味太上头。但排队真的太可怕了，下午4点去拿号都要等2小时，而且不能预约只能现场排',
    riskTags: ['排队2小时+', '不能预约', '不接受6人以上聚餐'],
  },
  {
    id: 'bj-125', name: '费大厨辣椒炒肉(朝阳大悦城店)', category: 'food', subcategory: '湘菜',
    city: '北京', district: '朝阳区', address: '朝阳北路101号朝阳大悦城',
    lat: 39.923, lng: 116.518, rating: 4.5, reviewCount: 9000, price: 80,
    openTime: '10:00-22:00', tags: ['湘菜', '辣椒炒肉', '下饭', '性价比'],
    images: ['images/stores/photo-125-1.jpg'],
    description: '湖南人气湘菜品牌，招牌辣椒炒肉配东北大米饭',
    targetAudience: ['上班族', '学生', '美食爱好者', '家庭'], bestTime: '午餐或晚餐', duration: '1小时',
    ugcTags: ['下饭神器', '辣椒炒肉正宗', '性价比高', '上菜快', '太辣', '油烟味'],
    ugcSummary: '辣椒炒肉真的绝了，一碗能干三碗饭，价格也很亲民。但吃不了辣的朋友慎重，微辣都已经很上头了',
    riskTags: ['辣度较高不适合所有人'],
  },
  {
    id: 'bj-126', name: '云海肴(王府井店)', category: 'food', subcategory: '云南菜',
    city: '北京', district: '东城区', address: '王府井大街138号',
    lat: 39.915, lng: 116.411, rating: 4.4, reviewCount: 7000, price: 95,
    openTime: '10:30-22:00', tags: ['云南菜', '汽锅鸡', '米线', '连锁', '口碑'],
    images: ['images/stores/photo-126-1.jpg'],
    description: '连锁云南菜品牌，汽锅鸡和过桥米线是特色',
    targetAudience: ['游客', '家庭', '上班族', '美食爱好者'], bestTime: '午餐或晚餐', duration: '1-1.5小时',
  },
  {
    id: 'bj-127', name: '莫斯科餐厅(展览馆店)', category: 'food', subcategory: '西餐',
    city: '北京', district: '西城区', address: '西直门外大街135号',
    lat: 39.943, lng: 116.342, rating: 4.3, reviewCount: 5000, price: 180,
    openTime: '11:00-22:00', tags: ['西餐', '俄式', '怀旧', '老字号', '建筑'],
    images: ['images/stores/photo-127-1.jpg'],
    description: '北京老牌俄式西餐厅，1954年开业，经典的红菜汤和罐焖牛肉',
    targetAudience: ['中老年人', '怀旧', '商务人士', '家庭'], bestTime: '午餐或晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-128', name: '京兆尹(雍和宫店)', category: 'food', subcategory: '素食',
    city: '北京', district: '东城区', address: '五道营胡同2号',
    lat: 39.947, lng: 116.417, rating: 4.8, reviewCount: 3500, price: 350,
    openTime: '11:30-14:00,17:30-21:30', tags: ['素食', '米其林', '四合院', '高端', '精致'],
    images: ['images/stores/photo-128-1.jpg'],
    description: '米其林三星素食餐厅，坐落在四合院内，将素食做到极致',
    targetAudience: ['商务人士', '素食爱好者', '高端消费', '情侣'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'bj-129', name: '烤肉宛(南礼士路店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '西城区', address: '南礼士路58号',
    lat: 39.912, lng: 116.352, rating: 4.4, reviewCount: 4500, price: 110,
    openTime: '11:00-22:00', tags: ['北京菜', '烤肉', '老字号', '清真', '传统'],
    images: ['images/stores/photo-129-1.jpg'],
    description: '北京烤肉老字号，与烤肉季齐名，传统炙子烤肉风味',
    targetAudience: ['中老年人', '家庭', '游客', '美食爱好者'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'bj-130', name: '呷哺呷哺(通州万达店)', category: 'food', subcategory: '火锅',
    city: '北京', district: '通州区', address: '新华西街58号万达广场',
    lat: 39.902, lng: 116.657, rating: 4.2, reviewCount: 10000, price: 75,
    openTime: '10:30-22:00', tags: ['火锅', '小火锅', '一人食', '性价比', '连锁'],
    images: ['images/stores/photo-130-1.jpg'],
    description: '台式小火锅连锁品牌，一人一锅，性价比高',
    targetAudience: ['上班族', '学生', '一人食', '朋友聚会'], bestTime: '午餐或晚餐', duration: '1小时',
  },
  {
    id: 'bj-131', name: '真功夫(中关村店)', category: 'food', subcategory: '快餐',
    city: '北京', district: '海淀区', address: '中关村大街15号',
    lat: 39.984, lng: 116.316, rating: 4.0, reviewCount: 6000, price: 35,
    openTime: '07:00-21:00', tags: ['快餐', '中式快餐', '蒸菜', '健康', '连锁'],
    images: ['images/stores/photo-131-1.jpg'],
    description: '中式快餐连锁品牌，原盅蒸饭和原盅蒸汤是特色',
    targetAudience: ['上班族', '学生', '快餐', '一人食'], bestTime: '午餐', duration: '30分钟',
  },
  {
    id: 'bj-132', name: '丰泽园饭庄(丰台店)', category: 'food', subcategory: '海鲜',
    city: '北京', district: '丰台区', address: '丰台南路118号',
    lat: 39.845, lng: 116.337, rating: 4.3, reviewCount: 3200, price: 200,
    openTime: '11:00-14:00,17:00-21:00', tags: ['海鲜', '鲁菜', '宴请', '品质', '老字号'],
    images: ['images/stores/photo-132-1.jpg'],
    description: '北京鲁菜老字号，葱烧海参是招牌菜，适合商务宴请',
    targetAudience: ['商务人士', '家庭聚会', '宴请', '中老年人'], bestTime: '午餐或晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-133', name: '眉州东坡(丰台万达店)', category: 'food', subcategory: '川菜',
    city: '北京', district: '丰台区', address: '丰科路6号万达广场',
    lat: 39.818, lng: 116.298, rating: 4.3, reviewCount: 8000, price: 90,
    openTime: '10:30-22:00', tags: ['川菜', '东坡肉', '连锁', '性价比', '家庭'],
    images: ['images/stores/photo-133-1.jpg'],
    description: '知名川菜连锁品牌，东坡肉和担担面是招牌',
    targetAudience: ['家庭', '朋友聚会', '上班族', '美食爱好者'], bestTime: '午餐或晚餐', duration: '1-1.5小时',
  },
  {
    id: 'bj-134', name: '兰州拉面(石景山万达店)', category: 'food', subcategory: '西北菜',
    city: '北京', district: '石景山区', address: '石景山路乙18号万达广场',
    lat: 39.907, lng: 116.228, rating: 4.1, reviewCount: 5000, price: 30,
    openTime: '07:00-21:30', tags: ['西北菜', '拉面', '清真', '性价比', '快餐'],
    images: ['images/stores/photo-134-1.jpg'],
    description: '正宗兰州牛肉拉面，汤清面筋，经济实惠',
    targetAudience: ['上班族', '学生', '一人食', '快餐'], bestTime: '午餐', duration: '30分钟',
  },
  {
    id: 'bj-135', name: '铁木真自助烤肉(大兴店)', category: 'food', subcategory: '自助餐',
    city: '北京', district: '大兴区', address: '黄村镇兴华大街2号',
    lat: 39.726, lng: 116.338, rating: 4.0, reviewCount: 6500, price: 80,
    openTime: '11:00-22:00', tags: ['自助餐', '烤肉', '性价比', '聚会', '大胃王'],
    images: ['images/stores/photo-135-1.jpg'],
    description: '自助烤肉连锁，品种丰富价格实惠，适合大胃王',
    targetAudience: ['学生', '年轻人', '朋友聚会', '家庭'], bestTime: '晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-136', name: '羊蝎子火锅(昌平店)', category: 'food', subcategory: '火锅',
    city: '北京', district: '昌平区', address: '府学路26号',
    lat: 40.221, lng: 116.237, rating: 4.2, reviewCount: 4000, price: 70,
    openTime: '10:00-23:00', tags: ['火锅', '羊蝎子', '老北京', '冬日', '滋补'],
    images: ['images/stores/photo-136-1.jpg'],
    description: '老北京羊蝎子火锅，汤浓肉烂，冬天暖身首选',
    targetAudience: ['朋友聚会', '家庭', '中老年人', '美食爱好者'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'bj-137', name: '密云水库鱼馆(密云店)', category: 'food', subcategory: '农家菜',
    city: '北京', district: '密云区', address: '密云水库南岸',
    lat: 40.489, lng: 116.883, rating: 4.3, reviewCount: 3200, price: 100,
    openTime: '10:00-21:00', tags: ['农家菜', '水库鱼', '原生态', '乡村', '自然'],
    images: ['images/stores/photo-137-1.jpg'],
    description: '密云水库边的农家鱼馆，现捞现做，鱼鲜汤美',
    targetAudience: ['游客', '家庭', '自驾游', '美食爱好者'], bestTime: '午餐', duration: '1-1.5小时',
  },
  {
    id: 'bj-138', name: '平谷农家大桃宴(平谷店)', category: 'food', subcategory: '农家菜',
    city: '北京', district: '平谷区', address: '平谷镇文化南街15号',
    lat: 40.144, lng: 117.111, rating: 4.1, reviewCount: 2500, price: 60,
    openTime: '09:00-21:00', tags: ['农家菜', '桃宴', '乡村', '土特产', '亲子'],
    images: ['images/stores/photo-138-1.jpg'],
    description: '平谷大桃之乡的特色农家菜，以桃入菜别有一番风味',
    targetAudience: ['游客', '亲子', '家庭', '自驾游'], bestTime: '午餐', duration: '1小时',
  },
  {
    id: 'bj-139', name: '汉拿山(大兴龙湖天街店)', category: 'food', subcategory: '韩餐',
    city: '北京', district: '大兴区', address: '永兴路7号龙湖天街',
    lat: 39.698, lng: 116.331, rating: 4.2, reviewCount: 7000, price: 100,
    openTime: '11:00-22:00', tags: ['韩餐', '烤肉', '石锅拌饭', '连锁', '家庭'],
    images: ['images/stores/photo-139-1.jpg'],
    description: '韩式烤肉连锁品牌，小菜丰富，石锅拌饭和冷面是必点',
    targetAudience: ['家庭', '朋友聚会', '年轻人', '韩餐爱好者'], bestTime: '晚餐', duration: '1-1.5小时',
  },
  {
    id: 'bj-140', name: '木屋烧烤(回龙观店)', category: 'food', subcategory: '烧烤',
    city: '北京', district: '昌平区', address: '回龙观西大街35号',
    lat: 40.082, lng: 116.328, rating: 4.3, reviewCount: 11000, price: 75,
    openTime: '17:00-02:00', tags: ['烧烤', '夜宵', '聚会', '啤酒', '人气'],
    images: ['images/stores/photo-140-1.jpg'],
    description: '深圳起家的烧烤连锁，环境好氛围佳，适合朋友聚会',
    targetAudience: ['年轻人', '朋友聚会', '夜宵爱好者', '上班族'], bestTime: '晚餐或夜宵', duration: '1-2小时',
  },
  {
    id: 'bj-141', name: '将太无二(中关村店)', category: 'food', subcategory: '日料',
    city: '北京', district: '海淀区', address: '中关村大街19号新中关购物中心',
    lat: 39.982, lng: 116.315, rating: 4.5, reviewCount: 6500, price: 150,
    openTime: '11:00-22:00', tags: ['日料', '寿司', '创意', '约会', '品质'],
    images: ['images/stores/photo-141-1.jpg'],
    description: '将太无二海淀分店，招牌秋天的童话寿司卷深受欢迎',
    targetAudience: ['上班族', '学生', '情侣', '日料爱好者'], bestTime: '午餐或晚餐', duration: '1-1.5小时',
    ugcTags: ['寿司好吃', '环境雅致', '适合约会', '工作日人少', '价格偏高', '份量偏小'],
    ugcSummary: '中关村附近难得的品质日料，秋天的童话卷每次必点。工作日晚餐不用排队太幸福了，就是卷类份量偏小胃口大的得多点几份',
    riskTags: [],
  },
  {
    id: 'bj-142', name: '胡大饭馆(方庄店)', category: 'food', subcategory: '川菜',
    city: '北京', district: '丰台区', address: '方庄芳群路1号',
    lat: 39.866, lng: 116.423, rating: 4.4, reviewCount: 5500, price: 100,
    openTime: '11:00-23:00', tags: ['川菜', '小龙虾', '麻小', '聚餐', '人气'],
    images: ['images/stores/photo-142-1.jpg'],
    description: '胡大麻小在方庄的分店，小龙虾品质稳定不用排队太久',
    targetAudience: ['朋友聚会', '年轻人', '美食爱好者'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'bj-143', name: '满恒记火锅(海淀店)', category: 'food', subcategory: '火锅',
    city: '北京', district: '海淀区', address: '成府路28号五道口购物中心',
    lat: 39.993, lng: 116.338, rating: 4.4, reviewCount: 8500, price: 90,
    openTime: '11:00-23:00', tags: ['火锅', '铜锅', '涮羊肉', '老北京', '冬天'],
    images: ['images/stores/photo-143-1.jpg'],
    description: '老北京铜锅涮肉，手切鲜羊肉是招牌，麻酱调料一绝',
    targetAudience: ['朋友聚会', '家庭', '中老年人', '游客'], bestTime: '晚餐', duration: '1.5小时',
    ugcTags: ['羊肉鲜嫩', '麻酱一绝', '冬天首选', '排队严重', '环境一般', '服务员少'],
    ugcSummary: '手切鲜羊肉立盘不倒，麻酱韭菜花配糖蒜就是老北京的冬天味道。但海淀店实在太小了，晚上6点后等位40分钟起步',
    riskTags: ['晚餐排队久', '店面小座位紧张'],
  },
  {
    id: 'bj-144', name: '大董烤鸭(工体店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '朝阳区', address: '工人体育场北路1号',
    lat: 39.935, lng: 116.447, rating: 4.7, reviewCount: 12000, price: 300,
    openTime: '11:00-22:00', tags: ['北京菜', '烤鸭', '高端', '宴请', '创意'],
    images: ['images/stores/photo-144-1.jpg'],
    description: '大董烤鸭工体旗舰店，酥不腻烤鸭和意境菜是京城一绝',
    targetAudience: ['商务人士', '宴请', '游客', '美食爱好者'], bestTime: '晚餐', duration: '2小时',
    ugcTags: ['烤鸭顶级', '意境菜惊艳', '环境高级', '服务一流', '价格昂贵', '需要预约'],
    ugcSummary: '酥不腻烤鸭确实名不虚传，鸭皮蘸白糖入口即化，意境菜的摆盘也像艺术品。人均300+但请客倍有面子，建议提前一周预约包间',
    riskTags: ['人均消费高', '包间需提前一周预约'],
  },
  {
    id: 'bj-145', name: '江边城外烤全鱼(通州店)', category: 'food', subcategory: '川菜',
    city: '北京', district: '通州区', address: '新华西街万达广场',
    lat: 39.904, lng: 116.659, rating: 4.3, reviewCount: 9000, price: 85,
    openTime: '11:00-22:00', tags: ['川菜', '烤鱼', '麻辣', '聚会', '连锁'],
    images: ['images/stores/photo-145-1.jpg'],
    description: '人气烤鱼连锁品牌，活鱼现杀现烤，香辣味最受欢迎',
    targetAudience: ['朋友聚会', '年轻人', '家庭', '学生'], bestTime: '晚餐', duration: '1-1.5小时',
  },
  {
    id: 'bj-146', name: '新荣记(金融街店)', category: 'food', subcategory: '粤菜',
    city: '北京', district: '西城区', address: '金融大街11号金融街购物中心',
    lat: 39.915, lng: 116.361, rating: 4.8, reviewCount: 2500, price: 500,
    openTime: '11:30-14:00,17:00-21:30', tags: ['粤菜', '米其林', '高端', '海鲜', '宴请'],
    images: ['images/stores/photo-146-1.jpg'],
    description: '米其林三星粤菜馆，东海海鲜和台州菜系，京城顶级中餐',
    targetAudience: ['商务人士', '高端消费', '宴请', '美食家'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'bj-147', name: '望京小腰(望京总店)', category: 'food', subcategory: '烧烤',
    city: '北京', district: '朝阳区', address: '望京街9号望京国际商业中心',
    lat: 39.996, lng: 116.484, rating: 4.1, reviewCount: 18000, price: 60,
    openTime: '17:00-02:00', tags: ['烧烤', '烤腰子', '大排档', '深夜', '人气'],
    images: ['images/stores/photo-147-1.jpg'],
    description: '北京传奇烧烤摊，因烤腰子而出名，望京深夜食堂代表',
    targetAudience: ['年轻人', '夜宵爱好者', '朋友聚会'], bestTime: '夜宵', duration: '1小时',
    ugcTags: ['深夜食堂', '烤腰子一绝', '烟火气足', '价格实惠', '环境简陋', '卫生一般', '太吵'],
    ugcSummary: '凌晨两点还人声鼎沸的传奇烤串摊，腰子处理得干净没有怪味。但环境就是路边摊水平，介意的慎来，适合喝啤酒撸串不讲究的朋友',
    riskTags: ['卫生条件一般', '深夜吵闹', '周边停车困难'],
  },
  {
    id: 'bj-148', name: '京味斋(东直门店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '东城区', address: '东直门内大街5号',
    lat: 39.938, lng: 116.433, rating: 4.3, reviewCount: 4000, price: 100,
    openTime: '11:00-22:00', tags: ['北京菜', '炸酱面', '小吃', '胡同', '传统'],
    images: ['images/stores/photo-148-1.jpg'],
    description: '北京传统小吃集合店，炸酱面、豆汁焦圈、卤煮火烧一应俱全',
    targetAudience: ['游客', '中老年人', '美食爱好者', '家庭'], bestTime: '午餐或晚餐', duration: '1小时',
  },
  {
    id: 'bj-149', name: '太二酸菜鱼(西单大悦城店)', category: 'food', subcategory: '川菜',
    city: '北京', district: '西城区', address: '西单北大街131号大悦城',
    lat: 39.914, lng: 116.374, rating: 4.5, reviewCount: 15000, price: 90,
    openTime: '11:00-22:00', tags: ['川菜', '酸菜鱼', '网红', '年轻人', '排队'],
    images: ['images/stores/photo-149-1.jpg'],
    description: '网红酸菜鱼品牌，老坛子酸菜鱼酸爽过瘾，超过4人不接待',
    targetAudience: ['年轻人', '朋友聚会', '网红打卡', '学生'], bestTime: '午餐或晚餐', duration: '1小时',
  },
  {
    id: 'bj-150', name: '蚝英雄(石景山店)', category: 'food', subcategory: '海鲜',
    city: '北京', district: '石景山区', address: '石景山路31号',
    lat: 39.906, lng: 116.215, rating: 4.2, reviewCount: 4000, price: 120,
    openTime: '11:00-22:00', tags: ['海鲜', '生蚝', '自助', '烧烤', '啤酒'],
    images: ['images/stores/photo-150-1.jpg'],
    description: '生蚝主题海鲜餐厅，蒜蓉烤生蚝是招牌，品种丰富',
    targetAudience: ['年轻人', '朋友聚会', '海鲜爱好者', '家庭'], bestTime: '晚餐', duration: '1-1.5小时',
  },
  {
    id: 'bj-151', name: '鼎泰丰(王府井APM店)', category: 'food', subcategory: '台湾菜',
    city: '北京', district: '东城区', address: '王府井大街138号APM',
    lat: 39.914, lng: 116.413, rating: 4.5, reviewCount: 7000, price: 150,
    openTime: '11:00-22:00', tags: ['台湾菜', '小笼包', '米其林', '精致', '连锁'],
    images: ['images/stores/photo-151-1.jpg'],
    description: '台湾小笼包名店，18摺小笼包皮薄汤鲜，世界级水准',
    targetAudience: ['游客', '家庭', '商务人士', '美食爱好者'], bestTime: '午餐或晚餐', duration: '1小时',
  },
  {
    id: 'bj-152', name: '顺峰海鲜(丰台店)', category: 'food', subcategory: '海鲜',
    city: '北京', district: '丰台区', address: '丰台北路18号',
    lat: 39.865, lng: 116.305, rating: 4.3, reviewCount: 3500, price: 250,
    openTime: '11:00-22:00', tags: ['海鲜', '粤菜', '宴请', '品质', '老字号'],
    images: ['images/stores/photo-152-1.jpg'],
    description: '北京老牌海鲜酒楼，海鲜池现捞现做，粤式烹饪手法',
    targetAudience: ['商务人士', '家庭聚会', '宴请', '中老年人'], bestTime: '晚餐', duration: '1.5-2小时',
  },
  {
    id: 'bj-153', name: '姚记肚儿(东四店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '东城区', address: '东四北大街220号',
    lat: 39.927, lng: 116.420, rating: 4.2, reviewCount: 3500, price: 40,
    openTime: '06:00-14:00', tags: ['北京菜', '炒肝', '包子', '早餐', '卤煮'],
    images: ['images/stores/photo-153-1.jpg'],
    description: '东四胡同里的老北京早餐店，炒肝和猪肉大葱包子是经典',
    targetAudience: ['本地居民', '中老年人', '游客', '美食爱好者'], bestTime: '早餐', duration: '30分钟',
  },
  {
    id: 'bj-154', name: '星巴克臻选(三里屯太古里店)', category: 'food', subcategory: '咖啡',
    city: '北京', district: '朝阳区', address: '三里屯路19号太古里',
    lat: 39.934, lng: 116.455, rating: 4.4, reviewCount: 8000, price: 55,
    openTime: '07:00-23:00', tags: ['咖啡', '臻选', '约会', '办公', '休闲'],
    images: ['images/stores/photo-154-1.jpg'],
    description: '星巴克臻选门店，三层独栋设计，有手冲吧台和特调饮品',
    targetAudience: ['年轻人', '上班族', '情侣', '咖啡爱好者'], bestTime: '下午茶', duration: '1小时',
    ugcTags: ['三层独栋好看', '手冲专业', '适合办公', '拍照出片', '周末人多', '插座少'],
    ugcSummary: '三里屯最美的星巴克，三层独栋工业风设计很出片，臻选手冲比普通店好喝不少。但周末基本找不到座位，带电脑办公的话插座太难找了',
    riskTags: ['周末无座', '插座不足不适合长时间办公'],
  },
  {
    id: 'bj-155', name: '紫光园(通州店)', category: 'food', subcategory: '北京菜',
    city: '北京', district: '通州区', address: '梨园镇云景东路1号',
    lat: 39.883, lng: 116.667, rating: 4.3, reviewCount: 5000, price: 70,
    openTime: '06:00-22:00', tags: ['北京菜', '清真', '小吃', '早餐', '性价比'],
    images: ['images/stores/photo-155-1.jpg'],
    description: '北京清真老字号，糖火烧和牛肉包子是招牌，价格亲民',
    targetAudience: ['家庭', '中老年人', '本地居民', '游客'], bestTime: '早餐或午餐', duration: '45分钟',
  },
  {
    id: 'bj-156', name: '南门涮肉(天坛店)', category: 'food', subcategory: '火锅',
    city: '北京', district: '东城区', address: '天坛东路6号',
    lat: 39.886, lng: 116.411, rating: 4.5, reviewCount: 10000, price: 100,
    openTime: '11:00-23:00', tags: ['火锅', '铜锅', '涮羊肉', '老北京', '口碑'],
    images: ['images/stores/photo-156-1.jpg'],
    description: '北京铜锅涮肉的代表，手切鲜羊肉和烧饼是标配',
    targetAudience: ['游客', '家庭', '朋友聚会', '美食爱好者'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'bj-157', name: '绿茶餐厅(大兴龙湖店)', category: 'food', subcategory: '创意菜',
    city: '北京', district: '大兴区', address: '永兴路7号龙湖天街',
    lat: 39.699, lng: 116.332, rating: 4.2, reviewCount: 9000, price: 65,
    openTime: '11:00-22:00', tags: ['创意菜', '江南', '性价比', '环境', '连锁'],
    images: ['images/stores/photo-157-1.jpg'],
    description: '江南主题创意菜馆，环境雅致价格实惠，面包诱惑是招牌',
    targetAudience: ['年轻人', '情侣', '家庭', '学生'], bestTime: '午餐或晚餐', duration: '1小时',
  },
  {
    id: 'bj-158', name: '苏帮袁(海淀万柳店)', category: 'food', subcategory: '江浙菜',
    city: '北京', district: '海淀区', address: '万柳中路29号万柳购物中心',
    lat: 39.968, lng: 116.296, rating: 4.5, reviewCount: 4000, price: 130,
    openTime: '11:00-22:00', tags: ['江浙菜', '淮扬菜', '精致', '环境', '宴请'],
    images: ['images/stores/photo-158-1.jpg'],
    description: '精致江南菜馆，松鼠桂鱼和东坡肉地道正宗',
    targetAudience: ['商务人士', '家庭', '情侣', '美食爱好者'], bestTime: '晚餐', duration: '1.5小时',
    ugcTags: ['环境雅致', '松鼠桂鱼正宗', '服务贴心', '适合家宴', '价格偏高', '上菜偏慢'],
    ugcSummary: '万柳附近家庭聚餐首选，江南庭院风装修很有格调，松鼠桂鱼酸甜适中老少都爱。价格比一般商场餐厅高一些但物有所值',
    riskTags: [],
  },
  {
    id: 'bj-159', name: '悦食悦香(朝阳大悦城店)', category: 'food', subcategory: '自助餐',
    city: '北京', district: '朝阳区', address: '朝阳北路101号朝阳大悦城',
    lat: 39.922, lng: 116.517, rating: 4.1, reviewCount: 6000, price: 120,
    openTime: '11:00-22:00', tags: ['自助餐', '海鲜', '日料', '聚餐', '家庭'],
    images: ['images/stores/photo-159-1.jpg'],
    description: '大型自助餐厅，海鲜日料中餐西餐品类齐全',
    targetAudience: ['家庭', '朋友聚会', '学生', '大胃王'], bestTime: '晚餐', duration: '2小时',
    ugcTags: ['品种丰富', '海鲜新鲜', '性价比不错', '补菜慢', '环境嘈杂', '限时2小时'],
    ugcSummary: '种类确实多，三文鱼和甜虾补货还算及时。但热菜区补得慢，高峰期生蚝要排队拿。限时两小时有点赶，聊天聚餐不太尽兴',
    riskTags: ['限时2小时', '高峰补菜慢', '海鲜排队'],
  },
  {
    id: 'bj-160', name: '陕西面馆(中关村店)', category: 'food', subcategory: '西北菜',
    city: '北京', district: '海淀区', address: '中关村大街27号中关村广场',
    lat: 39.985, lng: 116.317, rating: 4.3, reviewCount: 10000, price: 35,
    openTime: '10:00-21:30', tags: ['西北菜', '面食', '肉夹馍', '性价比', '快手'],
    images: ['images/stores/photo-160-1.jpg'],
    description: '正宗陕西面馆，油泼面和肉夹馍是标配，午饭排队王',
    targetAudience: ['上班族', '学生', '一人食', '快餐'], bestTime: '午餐', duration: '30分钟',
    ugcTags: ['油泼面正宗', '肉夹馍好吃', '性价比极高', '出餐快', '中午排队', '座位少'],
    ugcSummary: '中关村打工人的午间食堂，油泼面香辣够劲肉夹馍外酥里嫩，35块吃到撑性价比无敌。但中午12点人山人海，建议11点半之前来',
    riskTags: ['午间排队严重', '座位紧张需拼桌'],
  },
  // ── 景点 (bj-161 ~ bj-200) ──
  {
    id: 'bj-161', name: '今日美术馆', category: 'attraction', subcategory: '美术馆',
    city: '北京', district: '朝阳区', address: '百子湾路32号苹果社区',
    lat: 39.906, lng: 116.470, rating: 4.4, reviewCount: 5000, price: 50,
    openTime: '10:00-18:00(周一闭馆)', tags: ['美术馆', '当代艺术', '展览', '拍照', '文艺'],
    images: ['images/stores/photo-161-1.jpg'],
    description: '中国第一家民营非企业公益性美术馆，当代艺术展览频繁',
    targetAudience: ['文艺青年', '艺术爱好者', '拍照', '学生'], bestTime: '周末', duration: '1-2小时',
  },
  {
    id: 'bj-162', name: '尤伦斯当代艺术中心(UCCA)', category: 'attraction', subcategory: '美术馆',
    city: '北京', district: '朝阳区', address: '酒仙桥路4号798艺术区',
    lat: 39.984, lng: 116.497, rating: 4.6, reviewCount: 9000, price: 100,
    openTime: '10:00-19:00(周一闭馆)', tags: ['美术馆', '当代艺术', '国际', '798', '展览'],
    images: ['images/stores/photo-162-1.jpg'],
    description: '798艺术区的核心机构，国际顶级的中国当代艺术平台',
    targetAudience: ['艺术爱好者', '文艺青年', '国际游客', '拍照'], bestTime: '周末', duration: '1.5-2小时',
  },
  {
    id: 'bj-163', name: '朗园Vintage', category: 'attraction', subcategory: '文创园',
    city: '北京', district: '朝阳区', address: '通惠河北路郎家园6号',
    lat: 39.910, lng: 116.470, rating: 4.3, reviewCount: 4500, price: 0,
    openTime: '全天', tags: ['文创园', '拍照', '市集', '咖啡', '文艺'],
    images: ['images/stores/photo-163-1.jpg'],
    description: '前身是北京万东医疗设备厂，现在是最火的文化创意园区',
    targetAudience: ['文艺青年', '拍照', '年轻人', '咖啡爱好者'], bestTime: '周末', duration: '1-2小时',
  },
  {
    id: 'bj-164', name: '清华大学', category: 'attraction', subcategory: '大学校园',
    city: '北京', district: '海淀区', address: '双清路30号',
    lat: 40.001, lng: 116.326, rating: 4.8, reviewCount: 25000, price: 0,
    openTime: '全天(需预约)', tags: ['大学', '名校', '园林', '建筑', '文化'],
    images: ['images/stores/photo-164-1.jpg'],
    description: '中国最高学府，清华园和二校门是打卡地标，需提前预约',
    targetAudience: ['学生', '游客', '文化爱好者', '亲子', '摄影爱好者'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'bj-165', name: '北京大学', category: 'attraction', subcategory: '大学校园',
    city: '北京', district: '海淀区', address: '颐和园路5号',
    lat: 39.993, lng: 116.310, rating: 4.8, reviewCount: 20000, price: 0,
    openTime: '全天(需预约)', tags: ['大学', '名校', '未名湖', '博雅塔', '文化'],
    images: ['images/stores/photo-165-1.jpg'],
    description: '中国著名学府，未名湖和博雅塔是经典打卡地',
    targetAudience: ['学生', '游客', '文化爱好者', '亲子', '摄影爱好者'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'bj-166', name: '中关村创业大街', category: 'attraction', subcategory: '科技园区',
    city: '北京', district: '海淀区', address: '海淀西大街48号',
    lat: 39.983, lng: 116.311, rating: 4.1, reviewCount: 3500, price: 0,
    openTime: '全天', tags: ['科技', '创业', '互联网', '创新', '地标'],
    images: ['images/stores/photo-166-1.jpg'],
    description: '中国硅谷的核心地带，车库咖啡和3W咖啡是创业者聚集地',
    targetAudience: ['创业者', '科技爱好者', '年轻人', '上班族'], bestTime: '工作日', duration: '1小时',
  },
  {
    id: 'bj-167', name: '梅兰芳故居', category: 'attraction', subcategory: '名人故居',
    city: '北京', district: '西城区', address: '护国寺街9号',
    lat: 39.936, lng: 116.372, rating: 4.3, reviewCount: 2000, price: 20,
    openTime: '09:00-16:30(周一闭馆)', tags: ['名人故居', '京剧', '梅兰芳', '文化', '四合院'],
    images: ['images/stores/photo-167-1.jpg'],
    description: '京剧大师梅兰芳生前最后的居所，四合院内陈列生平事迹',
    targetAudience: ['文化爱好者', '中老年人', '京剧迷', '游客'], bestTime: '上午', duration: '1小时',
  },
  {
    id: 'bj-168', name: '郭沫若故居', category: 'attraction', subcategory: '名人故居',
    city: '北京', district: '西城区', address: '前海西街18号',
    lat: 39.936, lng: 116.389, rating: 4.2, reviewCount: 1800, price: 20,
    openTime: '09:00-16:30(周一闭馆)', tags: ['名人故居', '文学', '郭沫若', '什刹海', '文化'],
    images: ['images/stores/photo-168-1.jpg'],
    description: '郭沫若晚年居所，位于什刹海畔的四合院，院内海棠依旧',
    targetAudience: ['文化爱好者', '中老年人', '文学爱好者', '游客'], bestTime: '春季(海棠花开)', duration: '1小时',
  },
  {
    id: 'bj-169', name: '杨梅竹斜街', category: 'attraction', subcategory: '胡同',
    city: '北京', district: '西城区', address: '杨梅竹斜街',
    lat: 39.894, lng: 116.393, rating: 4.5, reviewCount: 6000, price: 0,
    openTime: '全天', tags: ['胡同', '文艺', '设计', '书店', '小众'],
    images: ['images/stores/photo-169-1.jpg'],
    description: '前门附近的文艺胡同，独立书店和设计师店铺云集',
    targetAudience: ['文艺青年', '拍照', '游客', '设计师'], bestTime: '下午', duration: '1-2小时',
  },
  {
    id: 'bj-170', name: 'PageOne书店(北京坊店)', category: 'attraction', subcategory: '书店',
    city: '北京', district: '西城区', address: '廊房头条13号北京坊',
    lat: 39.896, lng: 116.396, rating: 4.6, reviewCount: 8000, price: 0,
    openTime: '10:00-22:00', tags: ['书店', '设计', '文艺', '正阳门', '建筑'],
    images: ['images/stores/photo-170-1.jpg'],
    description: '正阳门下的最美书店，三层空间设计感极强，24小时营业区',
    targetAudience: ['文艺青年', '书虫', '拍照', '游客', '学生'], bestTime: '下午或晚上', duration: '1小时',
  },
  {
    id: 'bj-171', name: '三联韬奋书店(美术馆店)', category: 'attraction', subcategory: '书店',
    city: '北京', district: '东城区', address: '美术馆东街22号',
    lat: 39.928, lng: 116.411, rating: 4.5, reviewCount: 6000, price: 0,
    openTime: '09:00-21:00', tags: ['书店', '文化', '学术', '阅读', '老字号'],
    images: ['images/stores/photo-171-1.jpg'],
    description: '北京文化地标性书店，学术人文类书籍最全，读书人的精神家园',
    targetAudience: ['文化爱好者', '学生', '学者', '书虫'], bestTime: '任何时候', duration: '1-2小时',
  },
  {
    id: 'bj-172', name: '史家胡同博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '东城区', address: '史家胡同24号',
    lat: 39.919, lng: 116.426, rating: 4.5, reviewCount: 3500, price: 0,
    openTime: '09:00-16:30(周一闭馆)', tags: ['博物馆', '胡同', '历史', '四合院', '小众'],
    images: ['images/stores/photo-172-1.jpg'],
    description: '北京第一家胡同博物馆，藏在四合院里讲述胡同故事',
    targetAudience: ['文化爱好者', '游客', '学生', '亲子'], bestTime: '上午', duration: '1小时',
  },
  {
    id: 'bj-173', name: '世界花卉大观园', category: 'attraction', subcategory: '植物园',
    city: '北京', district: '丰台区', address: '南四环中路235号',
    lat: 39.840, lng: 116.372, rating: 4.3, reviewCount: 8000, price: 60,
    openTime: '08:00-17:30', tags: ['植物园', '花卉', '温室', '亲子', '拍照'],
    images: ['images/stores/photo-173-1.jpg'],
    description: '北京最大的花卉主题公园，七大温室展示世界奇花异草',
    targetAudience: ['亲子', '家庭', '摄影爱好者', '植物爱好者'], bestTime: '春季', duration: '半天',
  },
  {
    id: 'bj-174', name: '莲花池公园', category: 'attraction', subcategory: '园林景观',
    city: '北京', district: '丰台区', address: '广安门外莲花池路48号',
    lat: 39.894, lng: 116.334, rating: 4.2, reviewCount: 5000, price: 2,
    openTime: '06:00-21:00', tags: ['公园', '荷花', '历史', '休闲', '亲民'],
    images: ['images/stores/photo-174-1.jpg'],
    description: '北京城的发源地之一，夏季荷花盛开美不胜收',
    targetAudience: ['本地居民', '中老年人', '亲子', '摄影爱好者'], bestTime: '夏季(荷花季)', duration: '1-2小时',
  },
  {
    id: 'bj-175', name: '大运河森林公园', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '通州区', address: '宋梁路北运河畔',
    lat: 39.885, lng: 116.728, rating: 4.3, reviewCount: 6000, price: 0,
    openTime: '06:00-22:00', tags: ['公园', '运河', '骑行', '露营', '亲子'],
    images: ['images/stores/photo-175-1.jpg'],
    description: '京杭大运河北起点的滨水森林公园，适合骑行和露营',
    targetAudience: ['亲子', '骑行爱好者', '家庭', '户外运动'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'bj-176', name: '通州运河公园', category: 'attraction', subcategory: '园林景观',
    city: '北京', district: '通州区', address: '通胡大街70号',
    lat: 39.901, lng: 116.692, rating: 4.1, reviewCount: 4000, price: 0,
    openTime: '全天', tags: ['公园', '运河', '跑步', '休闲', '夜景'],
    images: ['images/stores/photo-176-1.jpg'],
    description: '运河商务区旁的滨水公园，夜景灯光秀是亮点',
    targetAudience: ['本地居民', '跑步', '散步', '家庭'], bestTime: '傍晚', duration: '1小时',
  },
  {
    id: 'bj-177', name: '石花洞', category: 'attraction', subcategory: '地质地貌',
    city: '北京', district: '房山区', address: '河北镇南车营村',
    lat: 39.789, lng: 115.936, rating: 4.3, reviewCount: 5000, price: 70,
    openTime: '08:30-16:30', tags: ['溶洞', '喀斯特', '地质', '自然', '4A景区'],
    images: ['images/stores/photo-177-1.jpg'],
    description: '华北最大的岩溶洞穴群，洞内钟乳石千姿百态',
    targetAudience: ['游客', '亲子', '地质爱好者', '探险'], bestTime: '夏季(洞内凉爽)', duration: '2小时',
  },
  {
    id: 'bj-178', name: '银狐洞', category: 'attraction', subcategory: '地质地貌',
    city: '北京', district: '房山区', address: '佛子庄乡下英水村',
    lat: 39.823, lng: 115.881, rating: 4.2, reviewCount: 3000, price: 65,
    openTime: '08:30-16:30', tags: ['溶洞', '钟乳石', '地下河', '自然', '小众'],
    images: ['images/stores/photo-178-1.jpg'],
    description: '以"银狐"钟乳石闻名，还有地下暗河可乘船游览',
    targetAudience: ['游客', '亲子', '探险', '自然爱好者'], bestTime: '夏季', duration: '2小时',
  },
  {
    id: 'bj-179', name: '爨底下村', category: 'attraction', subcategory: '古村落',
    city: '北京', district: '门头沟区', address: '斋堂镇爨底下村',
    lat: 40.005, lng: 115.638, rating: 4.5, reviewCount: 8000, price: 35,
    openTime: '全天', tags: ['古村落', '明清建筑', '摄影', '写生', '历史文化名村'],
    images: ['images/stores/photo-179-1.jpg'],
    description: '保存完好的明清古村落，依山而建的500多间四合院',
    targetAudience: ['摄影爱好者', '游客', '写生', '文化爱好者'], bestTime: '秋季', duration: '半天',
  },
  {
    id: 'bj-180', name: '灵山自然风景区', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '门头沟区', address: '清水镇洪水口村',
    lat: 40.046, lng: 115.456, rating: 4.4, reviewCount: 6000, price: 45,
    openTime: '08:00-17:00', tags: ['高山', '草甸', '登山', '露营', '星空'],
    images: ['images/stores/photo-180-1.jpg'],
    description: '北京最高峰(2303米)，高山草甸风景壮美，可露营观星',
    targetAudience: ['登山爱好者', '露营', '摄影爱好者', '户外运动'], bestTime: '夏季', duration: '一整天',
  },
  {
    id: 'bj-181', name: '石京龙滑雪场', category: 'attraction', subcategory: '滑雪场',
    city: '北京', district: '延庆区', address: '张山营镇中羊坊村',
    lat: 40.506, lng: 115.871, rating: 4.1, reviewCount: 5000, price: 200,
    openTime: '08:30-17:00(冬季开放)', tags: ['滑雪', '冬季', '运动', '亲子', '冰雪'],
    images: ['images/stores/photo-181-1.jpg'],
    description: '北京周边老牌滑雪场，初中高级雪道齐全，适合家庭',
    targetAudience: ['滑雪爱好者', '亲子', '年轻人', '运动'], bestTime: '冬季', duration: '一整天',
  },
  {
    id: 'bj-182', name: '野鸭湖国家湿地公园', category: 'attraction', subcategory: '湿地',
    city: '北京', district: '延庆区', address: '康庄镇刘浩营村西',
    lat: 40.421, lng: 115.867, rating: 4.3, reviewCount: 4000, price: 50,
    openTime: '08:30-17:00', tags: ['湿地', '观鸟', '候鸟', '摄影', '自然'],
    images: ['images/stores/photo-182-1.jpg'],
    description: '华北最大的湿地鸟类自然保护区，春秋候鸟迁徙季壮观',
    targetAudience: ['摄影爱好者', '观鸟', '亲子', '自然爱好者'], bestTime: '春秋候鸟季', duration: '半天',
  },
  {
    id: 'bj-183', name: '星美今晟影视城', category: 'attraction', subcategory: '主题乐园',
    city: '北京', district: '怀柔区', address: '杨宋镇怀杨路',
    lat: 40.280, lng: 116.690, rating: 4.0, reviewCount: 3000, price: 80,
    openTime: '09:00-17:00', tags: ['影视城', '影视基地', '拍照', '主题乐园', '怀柔'],
    images: ['images/stores/photo-183-1.jpg'],
    description: '华北最大的影视拍摄基地之一，可参观片场和影视布景',
    targetAudience: ['影视爱好者', '游客', '拍照', '亲子'], bestTime: '任何季节', duration: '半天',
  },
  {
    id: 'bj-184', name: '怀柔采摘园', category: 'attraction', subcategory: '农家体验',
    city: '北京', district: '怀柔区', address: '怀柔镇大中富乐村',
    lat: 40.316, lng: 116.638, rating: 4.1, reviewCount: 2500, price: 40,
    openTime: '08:00-18:00(季节开放)', tags: ['采摘', '农家', '亲子', '草莓', '樱桃'],
    images: ['images/stores/photo-184-1.jpg'],
    description: '怀柔特色采摘园，草莓樱桃苹果随季节轮换采摘',
    targetAudience: ['亲子', '家庭', '自驾游', '本地居民'], bestTime: '春夏两季', duration: '半天',
  },
  {
    id: 'bj-185', name: '潭柘寺', category: 'attraction', subcategory: '寺庙',
    city: '北京', district: '门头沟区', address: '潭柘寺镇',
    lat: 39.903, lng: 116.024, rating: 4.6, reviewCount: 12000, price: 55,
    openTime: '08:00-17:00', tags: ['寺庙', '古刹', '银杏', '佛教', '历史'],
    images: ['images/stores/photo-185-1.jpg'],
    description: '"先有潭柘寺，后有北京城"，千年古刹配千年银杏',
    targetAudience: ['游客', '文化爱好者', '摄影爱好者', '信徒'], bestTime: '秋季(银杏金黄)', duration: '半天',
  },
  {
    id: 'bj-186', name: '戒台寺', category: 'attraction', subcategory: '寺庙',
    city: '北京', district: '门头沟区', address: '永定镇戒台寺',
    lat: 39.874, lng: 116.081, rating: 4.4, reviewCount: 5000, price: 45,
    openTime: '08:00-17:00', tags: ['寺庙', '古松', '佛教', '清静', '历史'],
    images: ['images/stores/photo-186-1.jpg'],
    description: '以五大名松闻名的千年古寺，比潭柘寺更清幽宁静',
    targetAudience: ['游客', '信众', '文化爱好者', '寻求清静'], bestTime: '任何季节', duration: '2小时',
  },
  {
    id: 'bj-187', name: '北京野生动物园', category: 'attraction', subcategory: '动物园',
    city: '北京', district: '大兴区', address: '榆垡镇万亩森林',
    lat: 39.541, lng: 116.337, rating: 4.5, reviewCount: 15000, price: 150,
    openTime: '08:30-17:30', tags: ['动物园', '野生动物', '自驾', '亲子', '互动'],
    images: ['images/stores/photo-187-1.jpg'],
    description: '可以自驾穿越的野生动物园，猛兽区和萌宠区都受欢迎',
    targetAudience: ['亲子', '家庭', '动物爱好者', '自驾游'], bestTime: '春秋两季', duration: '一整天',
  },
  {
    id: 'bj-188', name: '北京汽车博物馆', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '丰台区', address: '南四环西路126号',
    lat: 39.833, lng: 116.310, rating: 4.4, reviewCount: 8000, price: 30,
    openTime: '09:00-17:00(周一闭馆)', tags: ['博物馆', '汽车', '互动', '科技', '亲子'],
    images: ['images/stores/photo-188-1.jpg'],
    description: '中国最大的汽车博物馆，从老爷车到概念车一应俱全',
    targetAudience: ['亲子', '汽车爱好者', '学生', '科技爱好者'], bestTime: '任何季节', duration: '2-3小时',
  },
  {
    id: 'bj-189', name: '北京世界公园', category: 'attraction', subcategory: '主题乐园',
    city: '北京', district: '丰台区', address: '花乡丰葆路158号',
    lat: 39.810, lng: 116.292, rating: 4.0, reviewCount: 10000, price: 100,
    openTime: '08:00-17:30', tags: ['主题乐园', '微缩景观', '世界名胜', '亲子', '拍照'],
    images: ['images/stores/photo-189-1.jpg'],
    description: '汇集世界50多个国家100多处名胜的微缩景观公园',
    targetAudience: ['亲子', '游客', '学生', '家庭'], bestTime: '春秋两季', duration: '半天至一天',
  },
  {
    id: 'bj-190', name: '西山国家森林公园', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '海淀区', address: '闵庄路与香山南路交叉口',
    lat: 39.978, lng: 116.215, rating: 4.4, reviewCount: 9000, price: 10,
    openTime: '06:00-20:00', tags: ['森林公园', '登山', '红叶', '野趣', '城市绿肺'],
    images: ['images/stores/photo-190-1.jpg'],
    description: '距市区最近的国家森林公园，秋天红叶不输香山',
    targetAudience: ['登山爱好者', '本地居民', '摄影爱好者', '家庭'], bestTime: '秋季(红叶)', duration: '半天',
  },
  {
    id: 'bj-191', name: '中华民族园', category: 'attraction', subcategory: '文化景点',
    city: '北京', district: '朝阳区', address: '民族园路2号',
    lat: 39.980, lng: 116.393, rating: 4.2, reviewCount: 6000, price: 90,
    openTime: '08:30-17:00', tags: ['民族文化', '博物馆', '建筑', '亲子', '风情'],
    images: ['images/stores/photo-191-1.jpg'],
    description: '集中展示中国56个民族建筑和文化的主题公园',
    targetAudience: ['游客', '亲子', '文化爱好者', '摄影爱好者'], bestTime: '春夏两季', duration: '半天',
  },
  {
    id: 'bj-192', name: '凤凰岭自然风景区', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '海淀区', address: '苏家坨镇凤凰岭路19号',
    lat: 40.096, lng: 116.097, rating: 4.3, reviewCount: 7000, price: 25,
    openTime: '07:00-17:00', tags: ['登山', '奇石', '龙泉寺', '自然', '徒步'],
    images: ['images/stores/photo-192-1.jpg'],
    description: '京西小黄山，奇峰怪石和龙泉寺是两大看点',
    targetAudience: ['登山爱好者', '游客', '信众', '户外运动'], bestTime: '春秋两季', duration: '半天至一天',
  },
  {
    id: 'bj-193', name: '北京大观园', category: 'attraction', subcategory: '文化景点',
    city: '北京', district: '西城区', address: '南菜园街12号',
    lat: 39.875, lng: 116.357, rating: 4.2, reviewCount: 5000, price: 40,
    openTime: '08:00-17:00', tags: ['红楼梦', '园林', '文化', '87版电视剧', '拍照'],
    images: ['images/stores/photo-193-1.jpg'],
    description: '为87版红楼梦电视剧而建的仿古园林，再现大观园景致',
    targetAudience: ['红楼梦爱好者', '游客', '拍照', '文化爱好者'], bestTime: '春季', duration: '2-3小时',
  },
  {
    id: 'bj-194', name: '雁栖湖', category: 'attraction', subcategory: '湖泊',
    city: '北京', district: '怀柔区', address: '雁栖镇',
    lat: 40.399, lng: 116.683, rating: 4.6, reviewCount: 15000, price: 45,
    openTime: '08:00-17:30', tags: ['湖泊', '游船', 'APEC', '度假', '水上运动'],
    images: ['images/stores/photo-194-1.jpg'],
    description: 'APEC会议举办地，湖光山色美不胜收，可乘船游湖',
    targetAudience: ['游客', '情侣', '家庭', '摄影爱好者'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'bj-195', name: '青龙峡', category: 'attraction', subcategory: '峡谷',
    city: '北京', district: '怀柔区', address: '怀北镇大水峪村',
    lat: 40.431, lng: 116.662, rating: 4.3, reviewCount: 5000, price: 55,
    openTime: '08:00-17:00', tags: ['峡谷', '水库', '蹦极', '登山', '自然'],
    images: ['images/stores/photo-195-1.jpg'],
    description: '集水库峡谷于一体的自然景区，有蹦极和滑索等刺激项目',
    targetAudience: ['年轻人', '户外运动', '亲子', '游客'], bestTime: '夏季', duration: '半天至一天',
  },
  {
    id: 'bj-196', name: '金海湖', category: 'attraction', subcategory: '湖泊',
    city: '北京', district: '平谷区', address: '金海湖镇',
    lat: 40.186, lng: 117.310, rating: 4.2, reviewCount: 5000, price: 40,
    openTime: '08:00-17:00', tags: ['湖泊', '水上运动', '露营', '度假', '坝体彩绘'],
    images: ['images/stores/photo-196-1.jpg'],
    description: '北京最大的综合性水上乐园，大坝彩绘是世界最大坝体彩绘',
    targetAudience: ['家庭', '亲子', '水上运动', '露营'], bestTime: '夏季', duration: '一整天',
  },
  {
    id: 'bj-197', name: '北京后花园(白虎涧)', category: 'attraction', subcategory: '自然景区',
    city: '北京', district: '昌平区', address: '阳坊镇',
    lat: 40.114, lng: 116.098, rating: 4.1, reviewCount: 4000, price: 40,
    openTime: '08:00-17:00', tags: ['登山', '奇石', '桃花', '徒步', '小众'],
    images: ['images/stores/photo-197-1.jpg'],
    description: '北京后花园风景区，春天桃花满山，奇石林立',
    targetAudience: ['登山爱好者', '摄影爱好者', '户外运动'], bestTime: '春季(桃花)', duration: '半天',
  },
  {
    id: 'bj-198', name: '十渡拒马乐园', category: 'attraction', subcategory: '主题乐园',
    city: '北京', district: '房山区', address: '十渡镇',
    lat: 39.637, lng: 115.583, rating: 4.1, reviewCount: 8000, price: 80,
    openTime: '08:00-17:00', tags: ['漂流', '蹦极', '竹筏', '亲子', '水上'],
    images: ['images/stores/photo-198-1.jpg'],
    description: '十渡核心游乐区，蹦极跳台是勇敢者的挑战',
    targetAudience: ['年轻人', '亲子', '户外运动', '游客'], bestTime: '夏季', duration: '一整天',
  },
  {
    id: 'bj-199', name: '中国铁道博物馆(东郊馆)', category: 'attraction', subcategory: '博物馆',
    city: '北京', district: '朝阳区', address: '酒仙桥北路1号院北侧',
    lat: 39.969, lng: 116.505, rating: 4.5, reviewCount: 7000, price: 20,
    openTime: '09:00-16:30(周一闭馆)', tags: ['博物馆', '火车', '铁路', '亲子', '工业'],
    images: ['images/stores/photo-199-1.jpg'],
    description: '中国最大的铁路机车车辆博物馆，毛泽东号和朱德号等历史机车',
    targetAudience: ['亲子', '火车迷', '学生', '工业爱好者'], bestTime: '任何季节', duration: '2-3小时',
  },
  {
    id: 'bj-200', name: '首钢园', category: 'attraction', subcategory: '文创园',
    city: '北京', district: '石景山区', address: '石景山路68号',
    lat: 39.913, lng: 116.164, rating: 4.4, reviewCount: 10000, price: 0,
    openTime: '全天', tags: ['工业遗址', '冬奥', '大跳台', '文创', '拍照'],
    images: ['images/stores/photo-200-1.jpg'],
    description: '冬奥会大跳台所在地，工业遗存与现代设计的融合典范',
    targetAudience: ['年轻人', '拍照', '文艺青年', '冬奥粉丝', '游客'], bestTime: '傍晚', duration: '半天',
  },
];

// 挂载到全局，兼容 Babel standalone（不支持 ES module）
window.beijingPOIs = beijingPOIs;
