/**
 * 上海 POI Mock 数据 (100个)
 * 覆盖人群：游客、亲子、情侣、商务、老年人、学生、美食爱好者、文化爱好者
 */

const shanghaiPOIs = [
  // ===== 1-10: 经典必游 =====
  {
    id: 'sh-001', name: '外滩', category: 'attraction', subcategory: '历史街区',
    city: '上海', district: '黄浦区', address: '中山东一路',
    lat: 31.2397, lng: 121.4998, rating: 4.8, reviewCount: 156000, price: 0,
    openTime: '全天', tags: ['万国建筑', '夜景', '黄浦江', '地标'],
    images: ['images/stores/photo-201-1.jpg'],
    description: '上海最著名的地标，52栋万国建筑博览群与浦东天际线隔江相望',
    targetAudience: ['游客', '摄影爱好者', '情侣', '历史爱好者'], bestTime: '傍晚至夜晚', duration: '1-2小时',
  },
  {
    id: 'sh-002', name: '东方明珠广播电视塔', category: 'attraction', subcategory: '现代建筑',
    city: '上海', district: '浦东新区', address: '世纪大道1号',
    lat: 31.2397, lng: 121.4998, rating: 4.5, reviewCount: 132000, price: 199,
    openTime: '09:00-21:00', tags: ['地标', '观光', '旋转餐厅', '5A景区'],
    images: ['images/stores/photo-202-1.jpg'],
    description: '上海标志性建筑，高468米，可俯瞰全城',
    targetAudience: ['游客', '亲子', '情侣', '摄影爱好者'], bestTime: '傍晚(看日落和夜景)', duration: '2-3小时',
  },
  {
    id: 'sh-003', name: '上海迪士尼乐园', category: 'attraction', subcategory: '主题乐园',
    city: '上海', district: '浦东新区', address: '川沙新镇黄赵路310号',
    lat: 31.1413, lng: 121.6617, rating: 4.7, reviewCount: 180000, price: 475,
    openTime: '08:30-21:30', tags: ['迪士尼', '亲子', '童话', '娱乐'],
    images: ['images/stores/photo-203-1.jpg'],
    description: '中国大陆首座迪士尼主题乐园，拥有全球最高城堡',
    targetAudience: ['亲子', '年轻人', '情侣', '迪士尼粉丝'], bestTime: '工作日避开高峰', duration: '一整天',
  },
  {
    id: 'sh-004', name: '豫园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '黄浦区', address: '安仁街137号',
    lat: 31.227, lng: 121.492, rating: 4.5, reviewCount: 98000, price: 40,
    openTime: '09:00-16:30', tags: ['江南园林', '明代', '古建筑', '4A景区'],
    images: ['images/stores/photo-204-1.jpg'],
    description: '明代私人园林，江南古典园林的代表作',
    targetAudience: ['游客', '文化爱好者', '摄影爱好者', '老年人'], bestTime: '上午', duration: '1-2小时',
  },
  {
    id: 'sh-005', name: '城隍庙', category: 'attraction', subcategory: '宗教场所',
    city: '上海', district: '黄浦区', address: '方浜中路249号',
    lat: 31.225, lng: 121.492, rating: 4.3, reviewCount: 85000, price: 10,
    openTime: '08:30-16:30', tags: ['道教', '祈福', '小吃', '老字号'],
    images: ['images/stores/photo-205-1.jpg'],
    description: '上海地区重要的道教宫观，周边是著名的小吃街',
    targetAudience: ['游客', '信众', '美食爱好者', '文化爱好者'], bestTime: '上午或傍晚', duration: '1-2小时',
  },
  {
    id: 'sh-006', name: '南京路步行街', category: 'attraction', subcategory: '商业街区',
    city: '上海', district: '黄浦区', address: '南京东路',
    lat: 31.235, lng: 121.475, rating: 4.4, reviewCount: 120000, price: 0,
    openTime: '全天', tags: ['购物', '老字号', '步行街', '地标'],
    images: ['images/stores/photo-206-1.jpg'],
    description: '中华商业第一街，汇集众多老字号和商场',
    targetAudience: ['游客', '购物者', '家庭', '年轻人'], bestTime: '傍晚至夜晚', duration: '2-3小时',
  },
  {
    id: 'sh-007', name: '上海中心大厦', category: 'attraction', subcategory: '现代建筑',
    city: '上海', district: '浦东新区', address: '银城中路501号',
    lat: 31.2335, lng: 121.5056, rating: 4.6, reviewCount: 65000, price: 180,
    openTime: '08:30-22:00', tags: ['最高建筑', '观光', '陆家嘴', '地标'],
    images: ['images/stores/photo-207-1.jpg'],
    description: '中国第一、世界第二高楼，高632米',
    targetAudience: ['游客', '商务人士', '摄影爱好者', '建筑爱好者'], bestTime: '傍晚(看日落)', duration: '1-2小时',
  },
  {
    id: 'sh-008', name: '田子坊', category: 'attraction', subcategory: '艺术区',
    city: '上海', district: '黄浦区', address: '泰康路210弄',
    lat: 31.215, lng: 121.47, rating: 4.2, reviewCount: 98000, price: 0,
    openTime: '全天', tags: ['石库门', '文创', '艺术', '小资'],
    images: ['images/stores/photo-208-1.jpg'],
    description: '上海石库门里弄改造的艺术街区，充满创意小店',
    targetAudience: ['年轻人', '文艺青年', '游客', '情侣'], bestTime: '下午至傍晚', duration: '2-3小时',
  },
  {
    id: 'sh-009', name: '新天地', category: 'attraction', subcategory: '商业街区',
    city: '上海', district: '黄浦区', address: '太仓路181弄',
    lat: 31.222, lng: 121.473, rating: 4.4, reviewCount: 76000, price: 0,
    openTime: '全天', tags: ['石库门', '酒吧', '时尚', '餐饮'],
    images: ['images/stores/photo-209-1.jpg'],
    description: '石库门建筑改造的时尚休闲区，中西合璧',
    targetAudience: ['年轻人', '商务人士', '情侣', '外国游客'], bestTime: '傍晚至深夜', duration: '2-4小时',
  },
  {
    id: 'sh-010', name: '上海博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '黄浦区', address: '人民大道201号',
    lat: 31.23, lng: 121.445, rating: 4.7, reviewCount: 52000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['博物馆', '文物', '青铜', '陶瓷'],
    images: ['images/stores/photo-210-1.jpg'],
    description: '中国四大博物馆之一，馆藏珍贵文物102万余件',
    targetAudience: ['文化爱好者', '学生', '亲子', '游客'], bestTime: '工作日', duration: '半天至一天',
  },

  // ===== 11-20: 现代地标 =====
  {
    id: 'sh-011', name: '上海环球金融中心', category: 'attraction', subcategory: '现代建筑',
    city: '上海', district: '浦东新区', address: '世纪大道100号',
    lat: 31.234, lng: 121.508, rating: 4.5, reviewCount: 45000, price: 150,
    openTime: '08:00-22:00', tags: ['观光', '陆家嘴', '高空', '地标'],
    images: ['images/stores/photo-211-1.jpg'],
    description: '高492米，拥有世界最高观光厅',
    targetAudience: ['游客', '摄影爱好者', '商务人士', '情侣'], bestTime: '傍晚', duration: '1-2小时',
  },
  {
    id: 'sh-012', name: '金茂大厦88层观光厅', category: 'attraction', subcategory: '现代建筑',
    city: '上海', district: '浦东新区', address: '世纪大道88号',
    lat: 31.237, lng: 121.501, rating: 4.4, reviewCount: 38000, price: 120,
    openTime: '08:30-21:30', tags: ['观光', '陆家嘴', '高空', '地标'],
    images: ['images/stores/photo-212-1.jpg'],
    description: '高420.5米，可360度俯瞰上海全景',
    targetAudience: ['游客', '摄影爱好者', '情侣', '家庭'], bestTime: '傍晚', duration: '1-2小时',
  },
  {
    id: 'sh-013', name: '陆家嘴金融区', category: 'attraction', subcategory: '现代建筑',
    city: '上海', district: '浦东新区', address: '陆家嘴',
    lat: 31.24, lng: 121.5, rating: 4.5, reviewCount: 56000, price: 0,
    openTime: '全天', tags: ['金融区', '摩天大楼', '夜景', '地标'],
    images: ['images/stores/photo-213-1.jpg'],
    description: '中国最重要的金融中心，高楼林立',
    targetAudience: ['商务人士', '游客', '建筑爱好者', '摄影爱好者'], bestTime: '夜晚', duration: '1-2小时',
  },
  {
    id: 'sh-014', name: '上海世博公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '浦东新区', address: '世博大道',
    lat: 31.19, lng: 121.47, rating: 4.3, reviewCount: 32000, price: 0,
    openTime: '全天', tags: ['世博', '公园', '黄浦江', '免费'],
    images: ['images/stores/photo-214-1.jpg'],
    description: '2010世博会会址改造的滨江公园',
    targetAudience: ['亲子', '本地居民', '游客', '骑行者'], bestTime: '傍晚', duration: '2-3小时',
  },
  {
    id: 'sh-015', name: '中华艺术宫', category: 'attraction', subcategory: '美术馆',
    city: '上海', district: '浦东新区', address: '上南路205号',
    lat: 31.185, lng: 121.475, rating: 4.4, reviewCount: 28000, price: 0,
    openTime: '10:00-18:00(周一闭馆)', tags: ['美术馆', '世博中国馆', '艺术', '免费'],
    images: ['images/stores/photo-215-1.jpg'],
    description: '原世博会中国馆，现为中国最重要的美术馆之一',
    targetAudience: ['艺术爱好者', '学生', '亲子', '文化爱好者'], bestTime: '工作日', duration: '2-4小时',
  },
  {
    id: 'sh-016', name: '上海科技馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '浦东新区', address: '世纪大道2000号',
    lat: 31.22, lng: 121.535, rating: 4.5, reviewCount: 52000, price: 60,
    openTime: '09:00-17:15(周一闭馆)', tags: ['科技', '互动', '亲子', '科普'],
    images: ['images/stores/photo-216-1.jpg'],
    description: '中国首家通过ISO9000认证的国家科技馆',
    targetAudience: ['亲子', '学生', '科技爱好者', '家庭'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'sh-017', name: '上海自然博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '静安区', address: '北京西路510号',
    lat: 31.235, lng: 121.46, rating: 4.6, reviewCount: 45000, price: 30,
    openTime: '09:00-17:15(周一闭馆)', tags: ['自然', '恐龙', '亲子', '科普'],
    images: ['images/stores/photo-217-1.jpg'],
    description: '中国规模最大的自然博物馆之一',
    targetAudience: ['亲子', '学生', '科普爱好者', '家庭'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'sh-018', name: '上海野生动物园', category: 'attraction', subcategory: '动物园',
    city: '上海', district: '浦东新区', address: '南六公路178号',
    lat: 31.055, lng: 121.72, rating: 4.5, reviewCount: 48000, price: 130,
    openTime: '09:00-17:00', tags: ['野生动物', '大熊猫', '亲子', '5A景区'],
    images: ['images/stores/photo-218-1.jpg'],
    description: '中国首座国家级野生动物园',
    targetAudience: ['亲子', '家庭', '动物爱好者', '学生'], bestTime: '周末', duration: '一整天',
  },
  {
    id: 'sh-019', name: '上海海昌海洋公园', category: 'attraction', subcategory: '主题乐园',
    city: '上海', district: '浦东新区', address: '南汇新城镇银飞路166号',
    lat: 30.93, lng: 121.92, rating: 4.4, reviewCount: 35000, price: 399,
    openTime: '09:30-17:30', tags: ['海洋公园', '虎鲸', '亲子', '娱乐'],
    images: ['images/stores/photo-219-1.jpg'],
    description: '中国首个世界级旗舰式海洋公园',
    targetAudience: ['亲子', '家庭', '情侣', '海洋爱好者'], bestTime: '周末', duration: '一整天',
  },
  {
    id: 'sh-020', name: '上海欢乐谷', category: 'attraction', subcategory: '主题乐园',
    city: '上海', district: '松江区', address: '林湖路888号',
    lat: 31.1, lng: 121.22, rating: 4.3, reviewCount: 52000, price: 260,
    openTime: '09:30-21:00', tags: ['游乐园', '过山车', '亲子', '4A景区'],
    images: ['images/stores/photo-220-1.jpg'],
    description: '上海最大的主题公园之一，拥有众多刺激项目',
    targetAudience: ['年轻人', '亲子', '学生', '情侣'], bestTime: '节假日有活动时', duration: '一整天',
  },

  // ===== 21-30: 文化历史 =====
  {
    id: 'sh-021', name: '上海历史博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '黄浦区', address: '南京西路325号',
    lat: 31.23, lng: 121.465, rating: 4.5, reviewCount: 22000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['历史', '文物', '上海故事', '免费'],
    images: ['images/stores/photo-221-1.jpg'],
    description: '全面展示上海从古代到近代的历史变迁',
    targetAudience: ['文化爱好者', '学生', '游客', '本地居民'], bestTime: '工作日', duration: '2-3小时',
  },
  {
    id: 'sh-022', name: '中共一大会址', category: 'attraction', subcategory: '纪念馆',
    city: '上海', district: '黄浦区', address: '兴业路76号',
    lat: 31.22, lng: 121.47, rating: 4.6, reviewCount: 35000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['红色旅游', '历史', '纪念馆', '免费'],
    images: ['images/stores/photo-222-1.jpg'],
    description: '中国共产党第一次全国代表大会会址',
    targetAudience: ['学生', '党员', '历史爱好者', '游客'], bestTime: '工作日', duration: '1-2小时',
  },
  {
    id: 'sh-023', name: '鲁迅故居', category: 'attraction', subcategory: '名人故居',
    city: '上海', district: '虹口区', address: '山阴路132弄9号',
    lat: 31.265, lng: 121.48, rating: 4.4, reviewCount: 18000, price: 0,
    openTime: '09:00-16:00(周一闭馆)', tags: ['名人故居', '文学', '历史', '免费'],
    images: ['images/stores/photo-223-1.jpg'],
    description: '鲁迅在上海的故居，展示鲁迅生平',
    targetAudience: ['文学爱好者', '学生', '文化爱好者', '游客'], bestTime: '工作日', duration: '1小时',
  },
  {
    id: 'sh-024', name: '宋庆龄故居', category: 'attraction', subcategory: '名人故居',
    city: '上海', district: '徐汇区', address: '淮海中路1843号',
    lat: 31.215, lng: 121.445, rating: 4.4, reviewCount: 15000, price: 20,
    openTime: '09:00-16:30(周一闭馆)', tags: ['名人故居', '历史', '建筑', '4A景区'],
    images: ['images/stores/photo-224-1.jpg'],
    description: '宋庆龄长期居住和从事国务活动的地方',
    targetAudience: ['历史爱好者', '学生', '文化爱好者', '游客'], bestTime: '工作日', duration: '1-2小时',
  },
  {
    id: 'sh-025', name: '上海大剧院', category: 'attraction', subcategory: '文化场馆',
    city: '上海', district: '黄浦区', address: '人民大道300号',
    lat: 31.23, lng: 121.465, rating: 4.5, reviewCount: 18000, price: 50,
    openTime: '09:00-17:00', tags: ['剧院', '歌剧', '芭蕾', '建筑'],
    images: ['images/stores/photo-225-1.jpg'],
    description: '上海最重要的表演艺术场所之一',
    targetAudience: ['艺术爱好者', '情侣', '商务人士', '文化爱好者'], bestTime: '有演出时', duration: '2-3小时',
  },
  {
    id: 'sh-026', name: '上海音乐厅', category: 'attraction', subcategory: '文化场馆',
    city: '上海', district: '黄浦区', address: '延安东路523号',
    lat: 31.235, lng: 121.48, rating: 4.5, reviewCount: 15000, price: 50,
    openTime: '09:00-17:00', tags: ['音乐厅', '古典音乐', '建筑', '演出'],
    images: ['images/stores/photo-226-1.jpg'],
    description: '中国第一座音乐厅，欧式古典建筑风格',
    targetAudience: ['古典音乐爱好者', '情侣', '文化爱好者', '游客'], bestTime: '有演出时', duration: '2小时',
  },
  {
    id: 'sh-027', name: '上海琉璃艺术博物馆', category: 'attraction', subcategory: '美术馆',
    city: '上海', district: '黄浦区', address: '泰康路25号',
    lat: 31.215, lng: 121.47, rating: 4.3, reviewCount: 12000, price: 45,
    openTime: '10:00-17:00(周一闭馆)', tags: ['琉璃', '艺术', '博物馆', '小众'],
    images: ['images/stores/photo-227-1.jpg'],
    description: '中国首家琉璃艺术博物馆',
    targetAudience: ['艺术爱好者', '文艺青年', '情侣', '游客'], bestTime: '周末', duration: '1-2小时',
  },
  {
    id: 'sh-028', name: '上海邮政博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '虹口区', address: '天潼路395号',
    lat: 31.245, lng: 121.485, rating: 4.3, reviewCount: 12000, price: 0,
    openTime: '09:00-17:00(周一闭馆)', tags: ['邮政', '历史', '建筑', '免费'],
    images: ['images/stores/photo-228-1.jpg'],
    description: '中国第一家省级邮政博物馆',
    targetAudience: ['集邮爱好者', '历史爱好者', '学生', '游客'], bestTime: '工作日', duration: '1-2小时',
  },
  {
    id: 'sh-029', name: '四行仓库抗战纪念馆', category: 'attraction', subcategory: '纪念馆',
    city: '上海', district: '静安区', address: '光复路21号',
    lat: 31.24, lng: 121.465, rating: 4.6, reviewCount: 28000, price: 0,
    openTime: '09:00-16:30(周一闭馆)', tags: ['抗战', '历史', '纪念馆', '免费'],
    images: ['images/stores/photo-229-1.jpg'],
    description: '淞沪会战四行仓库保卫战遗址',
    targetAudience: ['学生', '历史爱好者', '游客', '家庭'], bestTime: '工作日', duration: '1-2小时',
  },
  {
    id: 'sh-030', name: '上海犹太难民纪念馆', category: 'attraction', subcategory: '纪念馆',
    city: '上海', district: '虹口区', address: '长阳路62号',
    lat: 31.26, lng: 121.505, rating: 4.4, reviewCount: 10000, price: 20,
    openTime: '09:00-17:00(周一闭馆)', tags: ['二战', '犹太难民', '历史', '4A景区'],
    images: ['images/stores/photo-230-1.jpg'],
    description: '纪念二战期间上海接纳犹太难民的历史',
    targetAudience: ['历史爱好者', '学生', '游客', '文化爱好者'], bestTime: '工作日', duration: '1-2小时',
  },

  // ===== 31-40: 公园自然 =====
  {
    id: 'sh-031', name: '世纪公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '浦东新区', address: '锦绣路1001号',
    lat: 31.215, lng: 121.545, rating: 4.5, reviewCount: 45000, price: 0,
    openTime: '05:00-21:00', tags: ['城市公园', '湖泊', '赏花', '免费'],
    images: ['images/stores/photo-231-1.jpg'],
    description: '上海最大的城市公园，有"假日之园"的美称',
    targetAudience: ['亲子', '本地居民', '游客', '情侣'], bestTime: '春季(赏花)', duration: '半天',
  },
  {
    id: 'sh-032', name: '上海植物园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '徐汇区', address: '龙吴路997号',
    lat: 31.145, lng: 121.445, rating: 4.4, reviewCount: 28000, price: 0,
    openTime: '06:00-18:00', tags: ['植物园', '温室', '赏花', '4A景区'],
    images: ['images/stores/photo-232-1.jpg'],
    description: '上海市内最大的植物园，收集展示各类植物',
    targetAudience: ['亲子', '摄影爱好者', '植物爱好者', '情侣'], bestTime: '春季', duration: '半天',
  },
  {
    id: 'sh-033', name: '辰山植物园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '松江区', address: '辰花公路3888号',
    lat: 31.08, lng: 121.18, rating: 4.5, reviewCount: 25000, price: 60,
    openTime: '08:00-17:00', tags: ['植物园', '矿坑花园', '温室', '4A景区'],
    images: ['images/stores/photo-233-1.jpg'],
    description: '华东地区规模最大的植物园，有独特的矿坑花园',
    targetAudience: ['亲子', '摄影爱好者', '植物爱好者', '家庭'], bestTime: '春季', duration: '半天',
  },
  {
    id: 'sh-034', name: '顾村公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '宝山区', address: '沪太路4788号',
    lat: 31.33, lng: 121.4, rating: 4.3, reviewCount: 35000, price: 20,
    openTime: '06:00-18:00', tags: ['樱花', '烧烤', '亲子', '4A景区'],
    images: ['images/stores/photo-234-1.jpg'],
    description: '上海最著名的赏樱胜地，每年樱花节吸引大量游客',
    targetAudience: ['情侣', '摄影爱好者', '亲子', '游客'], bestTime: '春季(3-4月)', duration: '半天',
  },
  {
    id: 'sh-035', name: '共青森林公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '杨浦区', address: '军工路2000号',
    lat: 31.32, lng: 121.535, rating: 4.4, reviewCount: 28000, price: 0,
    openTime: '06:00-17:00', tags: ['森林', '烧烤', '骑行', '免费'],
    images: ['images/stores/photo-235-1.jpg'],
    description: '上海中心城区面积最大的森林公园',
    targetAudience: ['亲子', '本地居民', '户外爱好者', '情侣'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-036', name: '滨江森林公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '浦东新区', address: '高桥镇凌桥高沙滩3号',
    lat: 31.35, lng: 121.5, rating: 4.3, reviewCount: 18000, price: 0,
    openTime: '08:00-17:00', tags: ['滨江', '森林', '赏花', '免费'],
    images: ['images/stores/photo-236-1.jpg'],
    description: '上海森林覆盖率最高的郊野公园',
    targetAudience: ['亲子', '本地居民', '摄影爱好者', '情侣'], bestTime: '春季', duration: '半天',
  },
  {
    id: 'sh-037', name: '上海动物园', category: 'attraction', subcategory: '动物园',
    city: '上海', district: '长宁区', address: '虹桥路2381号',
    lat: 31.195, lng: 121.365, rating: 4.4, reviewCount: 38000, price: 40,
    openTime: '08:00-17:00', tags: ['动物园', '大熊猫', '亲子', '4A景区'],
    images: ['images/stores/photo-237-1.jpg'],
    description: '中国第二大城市动物园',
    targetAudience: ['亲子', '家庭', '学生', '动物爱好者'], bestTime: '上午', duration: '半天',
  },
  {
    id: 'sh-038', name: '上海海洋水族馆', category: 'attraction', subcategory: '水族馆',
    city: '上海', district: '浦东新区', address: '陆家嘴环路1388号',
    lat: 31.24, lng: 121.495, rating: 4.4, reviewCount: 32000, price: 160,
    openTime: '09:00-18:00', tags: ['海洋馆', '海底隧道', '亲子', '4A景区'],
    images: ['images/stores/photo-238-1.jpg'],
    description: '世界上最大的人造海水水族馆之一',
    targetAudience: ['亲子', '家庭', '情侣', '学生'], bestTime: '周末', duration: '2-3小时',
  },
  {
    id: 'sh-039', name: '上海长风海洋世界', category: 'attraction', subcategory: '水族馆',
    city: '上海', district: '普陀区', address: '大渡河路451号',
    lat: 31.225, lng: 121.395, rating: 4.2, reviewCount: 25000, price: 180,
    openTime: '08:30-17:00', tags: ['海洋馆', '白鲸', '亲子', '4A景区'],
    images: ['images/stores/photo-239-1.jpg'],
    description: '集大型海洋动物表演与水族馆展览于一体',
    targetAudience: ['亲子', '家庭', '情侣', '学生'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'sh-040', name: '上海东平国家森林公园', category: 'attraction', subcategory: '自然景区',
    city: '上海', district: '崇明区', address: '北沿公路2188号',
    lat: 31.68, lng: 121.48, rating: 4.3, reviewCount: 18000, price: 70,
    openTime: '08:00-17:00', tags: ['森林', '露营', '骑行', '4A景区'],
    images: ['images/stores/photo-240-1.jpg'],
    description: '华东地区最大的人造平原森林',
    targetAudience: ['亲子', '户外爱好者', '本地居民', '家庭'], bestTime: '春秋两季', duration: '半天至一天',
  },

  // ===== 41-50: 老上海风情 =====
  {
    id: 'sh-041', name: '武康路', category: 'attraction', subcategory: '历史街区',
    city: '上海', district: '徐汇区', address: '武康路',
    lat: 31.21, lng: 121.435, rating: 4.5, reviewCount: 52000, price: 0,
    openTime: '全天', tags: ['历史建筑', '梧桐', '文艺', '拍照'],
    images: ['images/stores/photo-241-1.jpg'],
    description: '上海最具代表性的历史风貌街道，名人故居云集',
    targetAudience: ['文艺青年', '摄影爱好者', '游客', '情侣'], bestTime: '下午', duration: '2-3小时',
  },
  {
    id: 'sh-042', name: '思南路', category: 'attraction', subcategory: '历史街区',
    city: '上海', district: '黄浦区', address: '思南路',
    lat: 31.215, lng: 121.465, rating: 4.4, reviewCount: 28000, price: 0,
    openTime: '全天', tags: ['老洋房', '梧桐', '文艺', '拍照'],
    images: ['images/stores/photo-242-1.jpg'],
    description: '上海最文艺的马路之一，两侧是花园洋房',
    targetAudience: ['文艺青年', '摄影爱好者', '情侣', '游客'], bestTime: '下午', duration: '1-2小时',
  },
  {
    id: 'sh-043', name: '多伦路文化名人街', category: 'attraction', subcategory: '历史街区',
    city: '上海', district: '虹口区', address: '多伦路',
    lat: 31.265, lng: 121.48, rating: 4.2, reviewCount: 18000, price: 0,
    openTime: '全天', tags: ['名人故居', '文化', '老建筑', '免费'],
    images: ['images/stores/photo-243-1.jpg'],
    description: '中国近代文化名人的聚集地',
    targetAudience: ['文化爱好者', '学生', '游客', '历史爱好者'], bestTime: '白天', duration: '1-2小时',
  },
  {
    id: 'sh-044', name: '甜爱路', category: 'attraction', subcategory: '历史街区',
    city: '上海', district: '虹口区', address: '甜爱路',
    lat: 31.265, lng: 121.475, rating: 4.1, reviewCount: 22000, price: 0,
    openTime: '全天', tags: ['爱情', '涂鸦', '浪漫', '免费'],
    images: ['images/stores/photo-244-1.jpg'],
    description: '上海最浪漫的马路，被称为"上海最甜蜜的马路"',
    targetAudience: ['情侣', '年轻人', '游客', '摄影爱好者'], bestTime: '傍晚', duration: '1小时',
  },
  {
    id: 'sh-045', name: '上海老码头', category: 'attraction', subcategory: '商业街区',
    city: '上海', district: '黄浦区', address: '中山南路505号',
    lat: 31.225, lng: 121.495, rating: 4.2, reviewCount: 15000, price: 0,
    openTime: '全天', tags: ['码头', '餐饮', '夜景', '文化'],
    images: ['images/stores/photo-245-1.jpg'],
    description: '由老码头仓库改造的创意园区',
    targetAudience: ['年轻人', '商务人士', '情侣', '游客'], bestTime: '傍晚至夜晚', duration: '2-3小时',
  },
  {
    id: 'sh-046', name: '1933老场坊', category: 'attraction', subcategory: '艺术区',
    city: '上海', district: '虹口区', address: '溧阳路611号',
    lat: 31.255, lng: 121.485, rating: 4.2, reviewCount: 25000, price: 0,
    openTime: '09:00-22:00', tags: ['工业风', '创意', '拍照', '建筑'],
    images: ['images/stores/photo-246-1.jpg'],
    description: '原上海屠宰场改造的创意园区，建筑独特',
    targetAudience: ['年轻人', '摄影爱好者', '文艺青年', '游客'], bestTime: '下午', duration: '1-2小时',
  },
  {
    id: 'sh-047', name: 'M50创意园', category: 'attraction', subcategory: '艺术区',
    city: '上海', district: '普陀区', address: '莫干山路50号',
    lat: 31.245, lng: 121.445, rating: 4.2, reviewCount: 18000, price: 0,
    openTime: '10:00-18:00', tags: ['艺术', '画廊', '工业风', '免费'],
    images: ['images/stores/photo-247-1.jpg'],
    description: '上海最早的创意园区之一，聚集众多艺术家工作室',
    targetAudience: ['艺术爱好者', '文艺青年', '摄影爱好者', '游客'], bestTime: '周末', duration: '2小时',
  },
  {
    id: 'sh-048', name: '上海音乐谷', category: 'attraction', subcategory: '艺术区',
    city: '上海', district: '虹口区', address: '溧阳路649号',
    lat: 31.255, lng: 121.485, rating: 4.1, reviewCount: 8000, price: 0,
    openTime: '全天', tags: ['音乐', '创意', '老建筑', '免费'],
    images: ['images/stores/photo-248-1.jpg'],
    description: '以音乐为主题的创意文化街区',
    targetAudience: ['音乐爱好者', '年轻人', '文艺青年', '游客'], bestTime: '傍晚', duration: '1-2小时',
  },
  {
    id: 'sh-049', name: '张园', category: 'attraction', subcategory: '历史街区',
    city: '上海', district: '静安区', address: '威海路590号',
    lat: 31.225, lng: 121.455, rating: 4.3, reviewCount: 12000, price: 0,
    openTime: '10:00-22:00', tags: ['石库门', '商业', '历史', '时尚'],
    images: ['images/stores/photo-249-1.jpg'],
    description: '上海现存最大的石库门建筑群，现改造为商业区',
    targetAudience: ['游客', '购物者', '文化爱好者', '年轻人'], bestTime: '傍晚', duration: '2小时',
  },
  {
    id: 'sh-050', name: '上海大世界', category: 'attraction', subcategory: '文化体验',
    city: '上海', district: '黄浦区', address: '西藏南路1号',
    lat: 31.235, lng: 121.475, rating: 4.0, reviewCount: 22000, price: 60,
    openTime: '09:00-17:00', tags: ['杂技', '非遗', '老上海', '4A景区'],
    images: ['images/stores/photo-250-1.jpg'],
    description: '上海百年娱乐场所，有杂技和非遗表演',
    targetAudience: ['游客', '家庭', '老年人', '文化爱好者'], bestTime: '下午', duration: '2-3小时',
  },

  // ===== 51-60: 美食餐饮 =====
  {
    id: 'sh-051', name: '南翔馒头店(豫园店)', category: 'food', subcategory: '上海小吃',
    city: '上海', district: '黄浦区', address: '豫园路85号',
    lat: 31.227, lng: 121.492, rating: 4.2, reviewCount: 45000, price: 50,
    openTime: '08:00-20:00', tags: ['小笼包', '老字号', '豫园', '上海菜'],
    images: ['images/stores/photo-251-1.jpg'],
    description: '上海最著名的小笼包店，创建于1900年',
    targetAudience: ['游客', '美食爱好者', '家庭', '老年人'], bestTime: '午餐', duration: '1小时',
    ugcTags: ['小笼包正宗', '百年老店', '游客必打卡', '游客太多', '排队夸张', '服务一般'],
    ugcSummary: '百年老店的名头确实响亮，小笼包皮薄汤多。但游客实在太多了，排队半小时吃10分钟，二楼堂食有最低消费感觉被宰，更适合外卖窗口带走',
    riskTags: ['游客扎堆', '二楼最低消费', '排队时间长'],
  },
  {
    id: 'sh-052', name: '绿波廊(豫园店)', category: 'food', subcategory: '上海菜',
    city: '上海', district: '黄浦区', address: '豫园路131号',
    lat: 31.227, lng: 121.492, rating: 4.3, reviewCount: 22000, price: 150,
    openTime: '11:00-21:00', tags: ['上海菜', '老字号', '宴请', '豫园'],
    images: ['images/stores/photo-252-1.jpg'],
    description: '上海著名本帮菜馆，接待过众多外国元首',
    targetAudience: ['商务宴请', '游客', '家庭聚餐', '美食爱好者'], bestTime: '午餐或晚餐', duration: '1.5-2小时',
    ugcTags: ['元首同款', '本帮菜正宗', '环境雅致', '宴请首选', '游客偏多', '价格偏高'],
    ugcSummary: '接待过克林顿的国宴级本帮菜馆，桂花拉糕和蟹粉小笼是必点。但游客一多用餐体验就打折扣，靠窗看九曲桥的位置要提前很久订',
    riskTags: ['靠窗位难订', '游客过多影响体验'],
  },
  {
    id: 'sh-053', name: '老正兴菜馆(福州路店)', category: 'food', subcategory: '上海菜',
    city: '上海', district: '黄浦区', address: '福州路556号',
    lat: 31.235, lng: 121.475, rating: 4.2, reviewCount: 18000, price: 120,
    openTime: '11:00-21:00', tags: ['本帮菜', '老字号', '河鲜', '中华老字号'],
    images: ['images/stores/photo-253-1.jpg'],
    description: '创建于1862年，上海最古老的本帮菜馆',
    targetAudience: ['游客', '美食爱好者', '家庭聚餐', '商务宴请'], bestTime: '午餐或晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-054', name: '德兴馆(广东路店)', category: 'food', subcategory: '上海菜',
    city: '上海', district: '黄浦区', address: '广东路471号',
    lat: 31.235, lng: 121.485, rating: 4.1, reviewCount: 15000, price: 80,
    openTime: '06:00-21:00', tags: ['本帮菜', '面馆', '老字号', '早餐'],
    images: ['images/stores/photo-254-1.jpg'],
    description: '上海著名老字号，以焖蹄面和鲜肉月饼闻名',
    targetAudience: ['本地居民', '游客', '美食爱好者', '早餐者'], bestTime: '早餐或午餐', duration: '1小时',
  },
  {
    id: 'sh-055', name: '鲜得来排骨年糕(云南路店)', category: 'food', subcategory: '上海小吃',
    city: '上海', district: '黄浦区', address: '云南南路46号',
    lat: 31.23, lng: 121.48, rating: 4.2, reviewCount: 22000, price: 30,
    openTime: '10:00-21:00', tags: ['排骨年糕', '上海小吃', '老字号', '快餐'],
    images: ['images/stores/photo-255-1.jpg'],
    description: '上海著名小吃店，以排骨年糕闻名',
    targetAudience: ['游客', '本地居民', '美食爱好者', '学生'], bestTime: '午餐', duration: '30分钟-1小时',
  },
  {
    id: 'sh-056', name: '海底捞火锅(南京东路店)', category: 'food', subcategory: '火锅',
    city: '上海', district: '黄浦区', address: '南京东路299号',
    lat: 31.235, lng: 121.475, rating: 4.5, reviewCount: 52000, price: 120,
    openTime: '09:00-07:00', tags: ['火锅', '服务', '24小时', '聚餐'],
    images: ['images/stores/photo-256-1.jpg'],
    description: '以服务著称的火锅连锁品牌，24小时营业',
    targetAudience: ['年轻人', '学生', '夜宵族', '聚餐'], bestTime: '晚餐或夜宵', duration: '2小时',
    ugcTags: ['服务无敌', '深夜首选', '免费美甲', '等位太久', '价格偏高', '太吵'],
    ugcSummary: '海底捞的服务确实没话说，等位时免费美甲小吃不断，凌晨三点还能吃火锅太幸福。但南京路店永远在排队，人均120吃火锅也不算便宜了',
    riskTags: ['排队时间长', '高峰等位2小时+'],
  },
  {
    id: 'sh-057', name: '鼎泰丰(新天地店)', category: 'food', subcategory: '台湾菜',
    city: '上海', district: '黄浦区', address: '太仓路181弄',
    lat: 31.222, lng: 121.473, rating: 4.5, reviewCount: 28000, price: 120,
    openTime: '10:00-22:00', tags: ['小笼包', '台湾菜', '精致', '米其林'],
    images: ['images/stores/photo-257-1.jpg'],
    description: '源自台湾的米其林星级餐厅，以小笼包闻名',
    targetAudience: ['美食爱好者', '商务人士', '情侣', '家庭'], bestTime: '午餐或晚餐', duration: '1.5小时',
    ugcTags: ['小笼包精致', '服务专业', '环境干净', '适合约会', '价格偏高', '份量偏小'],
    ugcSummary: '新天地逛累了来笼小笼包很惬意，每个18摺精致得像艺术品。但价格确实贵，两个大人轻松吃掉300+，更适合偶尔小资一下',
    riskTags: [],
  },
  {
    id: 'sh-058', name: '外滩茂悦大酒店·香荟', category: 'food', subcategory: '自助餐',
    city: '上海', district: '虹口区', address: '黄浦路199号',
    lat: 31.245, lng: 121.485, rating: 4.4, reviewCount: 15000, price: 300,
    openTime: '06:30-22:00', tags: ['自助餐', '外滩景观', '高端', '海鲜'],
    images: ['images/stores/photo-258-1.jpg'],
    description: '可俯瞰外滩和陆家嘴的豪华自助餐厅',
    targetAudience: ['商务人士', '情侣', '高端消费者', '游客'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'sh-059', name: '星巴克臻选(上海烘焙工坊)', category: 'food', subcategory: '咖啡',
    city: '上海', district: '静安区', address: '南京西路789号',
    lat: 31.23, lng: 121.455, rating: 4.5, reviewCount: 35000, price: 60,
    openTime: '07:00-23:00', tags: ['咖啡', '臻选', '烘焙', '体验'],
    images: ['images/stores/photo-259-1.jpg'],
    description: '星巴克海外首家臻选烘焙工坊',
    targetAudience: ['咖啡爱好者', '商务人士', '游客', '年轻人'], bestTime: '上午或下午', duration: '1-2小时',
    ugcTags: ['咖啡体验棒', '烘焙生产线震撼', '拍照出片', '游客太多', '排队进店', '价格贵'],
    ugcSummary: '全球最大的星巴克确实震撼，看着咖啡豆从烘焙到出杯的全过程很有意思。但游客实在太多了像个景点不像咖啡馆，一杯手冲卖60+也只能说是体验价了',
    riskTags: ['游客过多体验差', '周末需排队进店'],
  },
  {
    id: 'sh-060', name: '喜茶(来福士店)', category: 'food', subcategory: '茶饮',
    city: '上海', district: '黄浦区', address: '西藏中路268号',
    lat: 31.235, lng: 121.475, rating: 4.2, reviewCount: 25000, price: 30,
    openTime: '10:00-22:00', tags: ['奶茶', '网红', '排队', '社交'],
    images: ['images/stores/photo-260-1.jpg'],
    description: '知名新式茶饮品牌，以芝士茶闻名',
    targetAudience: ['年轻人', '学生', '情侣', '白领'], bestTime: '下午', duration: '30分钟',
  },

  // ===== 61-70: 更多景点 =====
  {
    id: 'sh-061', name: '上海迪士尼小镇', category: 'attraction', subcategory: '商业街区',
    city: '上海', district: '浦东新区', address: '申迪西路255弄',
    lat: 31.14, lng: 121.66, rating: 4.4, reviewCount: 28000, price: 0,
    openTime: '10:00-22:00', tags: ['迪士尼', '购物', '餐饮', '免费'],
    images: ['images/stores/photo-261-1.jpg'],
    description: '迪士尼主题乐园外的免费购物餐饮区',
    targetAudience: ['亲子', '年轻人', '游客', '情侣'], bestTime: '傍晚', duration: '2-3小时',
  },
  {
    id: 'sh-062', name: '上海奕欧来奥特莱斯', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '浦东新区', address: '申迪东路88号',
    lat: 31.14, lng: 121.67, rating: 4.3, reviewCount: 18000, price: 0,
    openTime: '10:00-21:00', tags: ['奥特莱斯', '购物', '欧式', '折扣'],
    images: ['images/stores/photo-262-1.jpg'],
    description: '欧式风格的奥特莱斯购物村',
    targetAudience: ['购物者', '游客', '家庭', '年轻人'], bestTime: '全天', duration: '半天',
  },
  {
    id: 'sh-063', name: '上海佛罗伦萨小镇', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '浦东新区', address: '卓耀路58弄',
    lat: 31.15, lng: 121.68, rating: 4.2, reviewCount: 15000, price: 0,
    openTime: '10:00-21:00', tags: ['奥特莱斯', '意大利', '购物', '拍照'],
    images: ['images/stores/photo-263-1.jpg'],
    description: '意大利风格的奥特莱斯购物小镇',
    targetAudience: ['购物者', '游客', '家庭', '摄影爱好者'], bestTime: '全天', duration: '半天',
  },
  {
    id: 'sh-064', name: '上海ifc商场', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '浦东新区', address: '世纪大道8号',
    lat: 31.235, lng: 121.5, rating: 4.5, reviewCount: 22000, price: 0,
    openTime: '10:00-22:00', tags: ['奢侈品', '购物', '陆家嘴', '高端'],
    images: ['images/stores/photo-264-1.jpg'],
    description: '陆家嘴高端购物中心，汇聚国际奢侈品牌',
    targetAudience: ['高端消费者', '商务人士', '游客', '时尚达人'], bestTime: '全天', duration: '2-4小时',
  },
  {
    id: 'sh-065', name: '上海恒隆广场', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '静安区', address: '南京西路1266号',
    lat: 31.23, lng: 121.45, rating: 4.4, reviewCount: 18000, price: 0,
    openTime: '10:00-22:00', tags: ['奢侈品', '购物', '南京西路', '高端'],
    images: ['images/stores/photo-265-1.jpg'],
    description: '上海高端购物地标之一',
    targetAudience: ['高端消费者', '商务人士', '游客', '时尚达人'], bestTime: '全天', duration: '2-3小时',
  },
  {
    id: 'sh-066', name: '上海K11购物艺术中心', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '黄浦区', address: '淮海中路300号',
    lat: 31.22, lng: 121.47, rating: 4.3, reviewCount: 22000, price: 0,
    openTime: '10:00-22:00', tags: ['艺术', '购物', '潮流', '年轻'],
    images: ['images/stores/photo-266-1.jpg'],
    description: '将艺术融入购物的体验式商场',
    targetAudience: ['年轻人', '艺术爱好者', '潮流达人', '游客'], bestTime: '全天', duration: '2-3小时',
  },
  {
    id: 'sh-067', name: '上海来福士广场', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '黄浦区', address: '西藏中路268号',
    lat: 31.235, lng: 121.475, rating: 4.2, reviewCount: 32000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '餐饮', '年轻', '潮流'],
    images: ['images/stores/photo-267-1.jpg'],
    description: '人民广场商圈的潮流购物中心',
    targetAudience: ['年轻人', '学生', '游客', '购物者'], bestTime: '全天', duration: '2-3小时',
  },
  {
    id: 'sh-068', name: '上海静安嘉里中心', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '静安区', address: '南京西路1515号',
    lat: 31.225, lng: 121.445, rating: 4.4, reviewCount: 18000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '餐饮', '商务', '高端'],
    images: ['images/stores/photo-268-1.jpg'],
    description: '静安寺商圈的高端商业综合体',
    targetAudience: ['商务人士', '高端消费者', '游客', '白领'], bestTime: '全天', duration: '2-3小时',
  },
  {
    id: 'sh-069', name: '上海月星环球港', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '普陀区', address: '中山北路3300号',
    lat: 31.235, lng: 121.41, rating: 4.2, reviewCount: 28000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '餐饮', '娱乐', '亲子'],
    images: ['images/stores/photo-269-1.jpg'],
    description: '上海中心城区最大的商业综合体',
    targetAudience: ['家庭', '亲子', '年轻人', '购物者'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'sh-070', name: '上海日月光中心', category: 'attraction', subcategory: '购物中心',
    city: '上海', district: '黄浦区', address: '徐家汇路618号',
    lat: 31.205, lng: 121.465, rating: 4.2, reviewCount: 35000, price: 0,
    openTime: '10:00-22:00', tags: ['购物', '餐饮', '年轻', '地铁上盖'],
    images: ['images/stores/photo-270-1.jpg'],
    description: '打浦桥商圈的大型购物中心，美食众多',
    targetAudience: ['年轻人', '学生', '上班族', '游客'], bestTime: '全天', duration: '2-3小时',
  },

  // ===== 71-80: 更多美食 =====
  {
    id: 'sh-071', name: '小杨生煎(吴江路店)', category: 'food', subcategory: '上海小吃',
    city: '上海', district: '静安区', address: '吴江路269号',
    lat: 31.23, lng: 121.455, rating: 4.3, reviewCount: 38000, price: 25,
    openTime: '07:00-22:00', tags: ['生煎', '上海小吃', '老字号', '快餐'],
    images: ['images/stores/photo-271-1.jpg'],
    description: '上海著名生煎连锁品牌，皮薄汁多',
    targetAudience: ['游客', '本地居民', '上班族', '美食爱好者'], bestTime: '早餐或午餐', duration: '30分钟',
    ugcTags: ['生煎汁多', '皮薄底脆', '价格亲民', '出餐快', '排队人多', '店面小'],
    ugcSummary: '上海生煎的代表，咬一口汤汁四溢小心烫嘴，底煎得金黄酥脆。25块吃饱在上海算良心价了，就是店面太小永远在排队',
    riskTags: [],
  },
  {
    id: 'sh-072', name: '大壶春(四川中路店)', category: 'food', subcategory: '上海小吃',
    city: '上海', district: '黄浦区', address: '四川中路136号',
    lat: 31.235, lng: 121.485, rating: 4.2, reviewCount: 18000, price: 30,
    openTime: '07:00-20:00', tags: ['生煎', '老字号', '上海小吃', '早餐'],
    images: ['images/stores/photo-272-1.jpg'],
    description: '上海老牌生煎店，历史悠久',
    targetAudience: ['本地居民', '游客', '美食爱好者', '早餐者'], bestTime: '早餐', duration: '30分钟',
  },
  {
    id: 'sh-073', name: '沈大成(南京东路店)', category: 'food', subcategory: '糕点',
    city: '上海', district: '黄浦区', address: '南京东路636号',
    lat: 31.235, lng: 121.475, rating: 4.3, reviewCount: 28000, price: 30,
    openTime: '08:00-21:00', tags: ['糕点', '青团', '老字号', '伴手礼'],
    images: ['images/stores/photo-273-1.jpg'],
    description: '上海著名糕点老字号，以青团和条头糕闻名',
    targetAudience: ['游客', '本地居民', '送礼者', '老年人'], bestTime: '全天', duration: '30分钟',
    ugcTags: ['青团一绝', '伴手礼首选', '价格实惠', '排队人多', '只能外带', '保质期短'],
    ugcSummary: '沈大成的青团是上海春天最期待的味道，咸蛋黄肉松味永远排长队。只能外带不能堂食有点可惜，当天买当天吃放久了影响口感',
    riskTags: ['青团季节限定', '只能外带', '排队时间长'],
  },
  {
    id: 'sh-074', name: '杏花楼(福州路总店)', category: 'food', subcategory: '上海菜',
    city: '上海', district: '黄浦区', address: '福州路343号',
    lat: 31.235, lng: 121.475, rating: 4.3, reviewCount: 22000, price: 120,
    openTime: '11:00-21:00', tags: ['本帮菜', '月饼', '老字号', '宴请'],
    images: ['images/stores/photo-274-1.jpg'],
    description: '创建于1851年，上海最著名的餐饮老字号之一',
    targetAudience: ['商务宴请', '游客', '家庭聚餐', '美食爱好者'], bestTime: '午餐或晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-075', name: '王宝和酒家(福州路店)', category: 'food', subcategory: '上海菜',
    city: '上海', district: '黄浦区', address: '福州路603号',
    lat: 31.235, lng: 121.475, rating: 4.2, reviewCount: 15000, price: 180,
    openTime: '11:00-21:00', tags: ['大闸蟹', '本帮菜', '老字号', '宴请'],
    images: ['images/stores/photo-275-1.jpg'],
    description: '以大闸蟹闻名的百年老店',
    targetAudience: ['商务宴请', '美食爱好者', '游客', '家庭聚餐'], bestTime: '秋季(蟹季)', duration: '1.5-2小时',
  },
  {
    id: 'sh-076', name: '新荣记(上海广场店)', category: 'food', subcategory: '江浙菜',
    city: '上海', district: '黄浦区', address: '淮海中路138号',
    lat: 31.22, lng: 121.47, rating: 4.5, reviewCount: 12000, price: 400,
    openTime: '11:00-22:00', tags: ['台州菜', '海鲜', '高端', '米其林'],
    images: ['images/stores/photo-276-1.jpg'],
    description: '米其林星级餐厅，以台州海鲜闻名',
    targetAudience: ['高端消费者', '商务宴请', '美食爱好者', '情侣'], bestTime: '晚餐', duration: '2小时',
    ugcTags: ['海鲜新鲜', '米其林品质', '宴请有面子', '价格昂贵', '需提前订位', '服务偶尔冷脸'],
    ugcSummary: '台州海鲜的新鲜程度确实一流，沙蒜豆面和黄金脆带鱼是必点。请客来这里绝对有面子，但人均400+可能对服务员来说还不够高端，偶尔遇到冷脸',
    riskTags: ['人均消费高', '需提前订位', '服务不稳定'],
  },
  {
    id: 'sh-077', name: '人和馆(肇嘉浜路店)', category: 'food', subcategory: '上海菜',
    city: '上海', district: '徐汇区', address: '肇嘉浜路407号',
    lat: 31.2, lng: 121.445, rating: 4.4, reviewCount: 15000, price: 150,
    openTime: '11:00-21:30', tags: ['本帮菜', '老字号', '蟹粉', '精致'],
    images: ['images/stores/photo-277-1.jpg'],
    description: '上海老牌本帮菜馆，以蟹粉系列闻名',
    targetAudience: ['美食爱好者', '商务宴请', '家庭聚餐', '游客'], bestTime: '秋季(蟹季)', duration: '1.5小时',
  },
  {
    id: 'sh-078', name: '哈灵面馆(广西北路店)', category: 'food', subcategory: '面食',
    city: '上海', district: '黄浦区', address: '广西北路445号',
    lat: 31.235, lng: 121.475, rating: 4.2, reviewCount: 22000, price: 35,
    openTime: '10:00-21:00', tags: ['牛蛙面', '网红', '快餐', '一人食'],
    images: ['images/stores/photo-278-1.jpg'],
    description: '上海网红面馆，以牛蛙面闻名',
    targetAudience: ['年轻人', '上班族', '学生', '一人食'], bestTime: '午餐或晚餐', duration: '30分钟-1小时',
  },
  {
    id: 'sh-079', name: '阿大葱油饼(南昌路店)', category: 'food', subcategory: '上海小吃',
    city: '上海', district: '黄浦区', address: '南昌路666号',
    lat: 31.215, lng: 121.46, rating: 4.0, reviewCount: 25000, price: 10,
    openTime: '06:00-18:00', tags: ['葱油饼', '网红', '上海小吃', '排队'],
    images: ['images/stores/photo-279-1.jpg'],
    description: '上海最著名的葱油饼，常年排队',
    targetAudience: ['游客', '本地居民', '美食爱好者', '年轻人'], bestTime: '早餐或下午', duration: '30分钟',
  },
  {
    id: 'sh-080', name: 'M Stand(新天地店)', category: 'food', subcategory: '咖啡',
    city: '上海', district: '黄浦区', address: '太仓路181弄',
    lat: 31.222, lng: 121.473, rating: 4.2, reviewCount: 15000, price: 40,
    openTime: '08:00-22:00', tags: ['咖啡', '网红', '创意', '社交'],
    images: ['images/stores/photo-280-1.jpg'],
    description: '上海本土网红咖啡品牌，以创意咖啡闻名',
    targetAudience: ['年轻人', '白领', '咖啡爱好者', '游客'], bestTime: '上午或下午', duration: '1小时',
  },

  // ===== 81-90: 补充景点 =====
  {
    id: 'sh-081', name: '上海杜莎夫人蜡像馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '黄浦区', address: '南京西路2-68号',
    lat: 31.235, lng: 121.475, rating: 4.2, reviewCount: 35000, price: 190,
    openTime: '10:00-21:00', tags: ['蜡像', '明星', '亲子', '拍照'],
    images: ['images/stores/photo-281-1.jpg'],
    description: '世界第六座杜莎夫人蜡像馆',
    targetAudience: ['亲子', '年轻人', '游客', '追星族'], bestTime: '工作日', duration: '2-3小时',
  },
  {
    id: 'sh-082', name: '上海中心大厦朵云书院', category: 'attraction', subcategory: '文化场馆',
    city: '上海', district: '浦东新区', address: '银城中路501号52层',
    lat: 31.2335, lng: 121.5056, rating: 4.4, reviewCount: 18000, price: 0,
    openTime: '10:30-20:00', tags: ['书店', '高空', '咖啡', '免费'],
    images: ['images/stores/photo-282-1.jpg'],
    description: '位于上海中心52层的云端书店',
    targetAudience: ['文艺青年', '游客', '摄影爱好者', '阅读爱好者'], bestTime: '下午', duration: '1-2小时',
  },
  {
    id: 'sh-083', name: '上海浦东图书馆', category: 'attraction', subcategory: '文化场馆',
    city: '上海', district: '浦东新区', address: '前程路88号',
    lat: 31.2, lng: 121.535, rating: 4.5, reviewCount: 12000, price: 0,
    openTime: '09:00-20:00', tags: ['图书馆', '阅读', '建筑', '免费'],
    images: ['images/stores/photo-283-1.jpg'],
    description: '上海最大的公共图书馆，建筑宏伟',
    targetAudience: ['学生', '阅读爱好者', '自习者', '本地居民'], bestTime: '工作日', duration: '半天',
  },
  {
    id: 'sh-084', name: '上海交响乐团音乐厅', category: 'attraction', subcategory: '文化场馆',
    city: '上海', district: '徐汇区', address: '复兴中路1380号',
    lat: 31.215, lng: 121.445, rating: 4.5, reviewCount: 8000, price: 50,
    openTime: '09:00-17:00', tags: ['音乐', '交响乐', '建筑', '演出'],
    images: ['images/stores/photo-284-1.jpg'],
    description: '国内第一个采用葡萄园式布局的音乐厅',
    targetAudience: ['古典音乐爱好者', '情侣', '文化爱好者', '商务人士'], bestTime: '有演出时', duration: '2小时',
  },
  {
    id: 'sh-085', name: '上海当代艺术博物馆', category: 'attraction', subcategory: '美术馆',
    city: '上海', district: '黄浦区', address: '苗江路678号',
    lat: 31.2, lng: 121.495, rating: 4.3, reviewCount: 15000, price: 0,
    openTime: '11:00-19:00(周一闭馆)', tags: ['当代艺术', '建筑', '展览', '免费'],
    images: ['images/stores/photo-285-1.jpg'],
    description: '中国大陆第一家公立当代艺术博物馆',
    targetAudience: ['艺术爱好者', '文艺青年', '学生', '游客'], bestTime: '周末', duration: '2-3小时',
  },
  {
    id: 'sh-086', name: '上海龙美术馆(西岸馆)', category: 'attraction', subcategory: '美术馆',
    city: '上海', district: '徐汇区', address: '龙腾大道3398号',
    lat: 31.185, lng: 121.465, rating: 4.4, reviewCount: 12000, price: 100,
    openTime: '10:00-18:00(周一闭馆)', tags: ['当代艺术', '建筑', '展览', '拍照'],
    images: ['images/stores/photo-286-1.jpg'],
    description: '中国最具规模的私立美术馆',
    targetAudience: ['艺术爱好者', '摄影爱好者', '文艺青年', '情侣'], bestTime: '周末', duration: '2-3小时',
  },
  {
    id: 'sh-087', name: '上海余德耀美术馆', category: 'attraction', subcategory: '美术馆',
    city: '上海', district: '徐汇区', address: '丰谷路35号',
    lat: 31.18, lng: 121.46, rating: 4.3, reviewCount: 8000, price: 80,
    openTime: '10:00-21:00(周一闭馆)', tags: ['当代艺术', '建筑', '展览', '小众'],
    images: ['images/stores/photo-287-1.jpg'],
    description: '由老机库改造的美术馆，空间独特',
    targetAudience: ['艺术爱好者', '文艺青年', '摄影爱好者', '游客'], bestTime: '周末', duration: '2小时',
  },
  {
    id: 'sh-088', name: '上海玻璃博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '宝山区', address: '长江西路685号',
    lat: 31.33, lng: 121.445, rating: 4.4, reviewCount: 15000, price: 80,
    openTime: '10:00-17:00(周一闭馆)', tags: ['玻璃', '艺术', '互动', '4A景区'],
    images: ['images/stores/photo-288-1.jpg'],
    description: '中国首家玻璃主题博物馆',
    targetAudience: ['亲子', '艺术爱好者', '学生', '家庭'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'sh-089', name: '上海汽车博览公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '嘉定区', address: '博园路7565号',
    lat: 31.28, lng: 121.18, rating: 4.2, reviewCount: 10000, price: 60,
    openTime: '09:00-16:30', tags: ['汽车', '博物馆', '亲子', '4A景区'],
    images: ['images/stores/photo-289-1.jpg'],
    description: '集汽车博物馆、会展中心、试乘试驾于一体',
    targetAudience: ['亲子', '汽车爱好者', '学生', '家庭'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'sh-090', name: '上海方塔园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '松江区', address: '中山东路235号',
    lat: 31.0, lng: 121.23, rating: 4.2, reviewCount: 12000, price: 12,
    openTime: '07:00-17:00', tags: ['古塔', '园林', '历史', '4A景区'],
    images: ['images/stores/photo-290-1.jpg'],
    description: '以宋代方塔为中心的古典园林',
    targetAudience: ['文化爱好者', '游客', '摄影爱好者', '本地居民'], bestTime: '春秋两季', duration: '2小时',
  },

  // ===== 91-100: 最后补充 =====
  {
    id: 'sh-091', name: '上海醉白池', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '松江区', address: '人民南路64号',
    lat: 31.0, lng: 121.23, rating: 4.2, reviewCount: 10000, price: 12,
    openTime: '07:00-17:00', tags: ['园林', '荷花', '历史', '4A景区'],
    images: ['images/stores/photo-291-1.jpg'],
    description: '上海五大古典园林之一，以荷花闻名',
    targetAudience: ['文化爱好者', '摄影爱好者', '游客', '本地居民'], bestTime: '夏季(荷花季)', duration: '2小时',
  },
  {
    id: 'sh-092', name: '上海古猗园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '嘉定区', address: '沪宜公路218号',
    lat: 31.3, lng: 121.32, rating: 4.3, reviewCount: 15000, price: 12,
    openTime: '07:00-18:00', tags: ['园林', '竹子', '历史', '4A景区'],
    images: ['images/stores/photo-292-1.jpg'],
    description: '上海五大古典园林之一，以竹景闻名',
    targetAudience: ['文化爱好者', '摄影爱好者', '游客', '本地居民'], bestTime: '春夏两季', duration: '2小时',
  },
  {
    id: 'sh-093', name: '上海秋霞圃', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '嘉定区', address: '东大街314号',
    lat: 31.38, lng: 121.25, rating: 4.2, reviewCount: 8000, price: 10,
    openTime: '08:00-16:30', tags: ['园林', '红叶', '历史', '4A景区'],
    images: ['images/stores/photo-293-1.jpg'],
    description: '上海五大古典园林之一，秋季红叶最美',
    targetAudience: ['文化爱好者', '摄影爱好者', '游客', '本地居民'], bestTime: '秋季', duration: '2小时',
  },
  {
    id: 'sh-094', name: '上海曲水园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '青浦区', address: '公园路612号',
    lat: 31.15, lng: 121.12, rating: 4.1, reviewCount: 8000, price: 5,
    openTime: '06:00-17:00', tags: ['园林', '历史', '免费', '4A景区'],
    images: ['images/stores/photo-294-1.jpg'],
    description: '上海五大古典园林之一，始建于乾隆年间',
    targetAudience: ['文化爱好者', '摄影爱好者', '本地居民', '游客'], bestTime: '春秋两季', duration: '1-2小时',
  },
  {
    id: 'sh-095', name: '上海朱家角古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '青浦区', address: '朱家角镇',
    lat: 31.1, lng: 121.05, rating: 4.3, reviewCount: 45000, price: 0,
    openTime: '全天', tags: ['古镇', '水乡', '江南', '4A景区'],
    images: ['images/stores/photo-295-1.jpg'],
    description: '上海四大历史文化名镇之一，有"上海威尼斯"之称',
    targetAudience: ['游客', '摄影爱好者', '情侣', '文化爱好者'], bestTime: '春秋两季', duration: '半天至一天',
  },
  {
    id: 'sh-096', name: '上海七宝古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '闵行区', address: '七宝镇',
    lat: 31.15, lng: 121.35, rating: 4.2, reviewCount: 38000, price: 0,
    openTime: '全天', tags: ['古镇', '小吃', '历史', '4A景区'],
    images: ['images/stores/photo-296-1.jpg'],
    description: '上海著名的古镇，以七宝老街和特色小吃闻名',
    targetAudience: ['游客', '美食爱好者', '家庭', '本地居民'], bestTime: '全天', duration: '半天',
  },
  {
    id: 'sh-097', name: '上海枫泾古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '金山区', address: '枫泾镇',
    lat: 30.9, lng: 121.0, rating: 4.2, reviewCount: 22000, price: 0,
    openTime: '全天', tags: ['古镇', '水乡', '农民画', '4A景区'],
    images: ['images/stores/photo-297-1.jpg'],
    description: '中国历史文化名镇，典型的江南水乡',
    targetAudience: ['游客', '摄影爱好者', '文化爱好者', '情侣'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-098', name: '上海新场古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '浦东新区', address: '新场镇',
    lat: 31.05, lng: 121.65, rating: 4.1, reviewCount: 15000, price: 0,
    openTime: '全天', tags: ['古镇', '影视', '历史', '4A景区'],
    images: ['images/stores/photo-298-1.jpg'],
    description: '电影《色戒》取景地，保存完好的江南水乡',
    targetAudience: ['游客', '摄影爱好者', '电影爱好者', '情侣'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-099', name: '上海泰晤士小镇', category: 'attraction', subcategory: '商业街区',
    city: '上海', district: '松江区', address: '三新北路900弄',
    lat: 31.05, lng: 121.2, rating: 4.0, reviewCount: 22000, price: 0,
    openTime: '全天', tags: ['欧式', '拍照', '休闲', '免费'],
    images: ['images/stores/photo-299-1.jpg'],
    description: '仿英国泰晤士小镇建造的欧式风情区',
    targetAudience: ['年轻人', '摄影爱好者', '情侣', '游客'], bestTime: '下午', duration: '2-3小时',
  },
  {
    id: 'sh-100', name: '上海金山城市沙滩', category: 'attraction', subcategory: '自然景区',
    city: '上海', district: '金山区', address: '沪杭公路7555号',
    lat: 30.72, lng: 121.35, rating: 4.0, reviewCount: 18000, price: 20,
    openTime: '08:30-17:00', tags: ['海滩', '游泳', '亲子', '4A景区'],
    images: ['images/stores/photo-300-1.jpg'],
    description: '上海首个天然景观沙滩',
    targetAudience: ['亲子', '家庭', '年轻人', '本地居民'], bestTime: '夏季', duration: '半天至一天',
  },
  // ═══════════════════════════════════════════
  // 新增 100 POI (sh-101 ~ sh-200): 55 美食 + 45 景点
  // ═══════════════════════════════════════════
  // ── 美食 (sh-101 ~ sh-155) ──
  {
    id: 'sh-101', name: '福1088', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '静安区', address: '镇宁路375号',
    lat: 31.225, lng: 121.433, rating: 4.7, reviewCount: 3500, price: 350,
    openTime: '11:30-14:00,17:30-22:00', tags: ['本帮菜', '老洋房', '米其林', '宴请', '精致'],
    images: ['images/stores/photo-301-1.jpg'],
    description: '藏在老洋房里的米其林本帮菜，红烧肉和蟹粉豆腐是招牌',
    targetAudience: ['商务人士', '宴请', '美食爱好者', '情侣'], bestTime: '晚餐', duration: '2小时',
    ugcTags: ['老洋房有格调', '菜品精致', '米其林光环', '服务傲慢', '价格虚高', '预约困难', '份量极小', '性价比低'],
    ugcSummary: '老洋房环境确实独特拍照好看，菜品摆盘也精致。但服务生全程扑克脸，人均350吃完像吃了个前菜，三块红烧肉卖198简直抢钱，预约还要提前两周，再也不来了',
    riskTags: ['预约需提前两周', '性价比极低', '服务态度傲慢', '份量少吃不饱'],
  },
  {
    id: 'sh-102', name: '雍福会', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '徐汇区', address: '永福路200号',
    lat: 31.214, lng: 121.445, rating: 4.6, reviewCount: 2500, price: 500,
    openTime: '11:30-14:00,17:30-22:00', tags: ['本帮菜', '花园洋房', '米其林', '高端', '私密'],
    images: ['images/stores/photo-302-1.jpg'],
    description: '前英国领事馆改造的顶级本帮菜馆，花园用餐体验绝佳',
    targetAudience: ['商务人士', '高端消费', '宴请', '情侣'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'sh-103', name: '光明邨大酒家(淮海中路店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '黄浦区', address: '淮海中路588号',
    lat: 31.220, lng: 121.471, rating: 4.4, reviewCount: 20000, price: 80,
    openTime: '10:00-14:00,16:30-21:00', tags: ['本帮菜', '熟食', '鲜肉月饼', '排队', '老字号'],
    images: ['images/stores/photo-303-1.jpg'],
    description: '上海人从小吃到大的老字号，鲜肉月饼排队王，熟食窗口常年排队',
    targetAudience: ['本地居民', '中老年人', '游客', '美食爱好者'], bestTime: '午餐', duration: '1小时',
    ugcTags: ['鲜肉月饼一绝', '熟食窗口火爆', '老上海味道', '排队太久', '只能外带', '环境老旧'],
    ugcSummary: '上海阿姨爷叔的最爱，中秋节前买鲜肉月饼的队伍能排到街角。熟食窗口的酱鸭和熏鱼是小时候的味道，但想坐下来吃顿饭要等很久',
    riskTags: ['鲜肉月饼季节排队1小时+', '堂食等位久'],
  },
  {
    id: 'sh-104', name: 'Le Bec(新华路店)', category: 'food', subcategory: '法餐',
    city: '上海', district: '长宁区', address: '新华路321号',
    lat: 31.213, lng: 121.425, rating: 4.5, reviewCount: 2000, price: 400,
    openTime: '12:00-14:00,18:00-22:00', tags: ['法餐', '洋房', '米其林', '约会', '精致'],
    images: ['images/stores/photo-304-1.jpg'],
    description: '藏在老洋房里的米其林法餐厅，主厨来自里昂',
    targetAudience: ['情侣', '商务人士', '美食爱好者', '约会'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'sh-105', name: 'Pain Chaud(永康路店)', category: 'food', subcategory: '面包房',
    city: '上海', district: '徐汇区', address: '永康路41号',
    lat: 31.213, lng: 121.449, rating: 4.4, reviewCount: 5000, price: 45,
    openTime: '07:30-21:00', tags: ['面包房', '法式烘焙', '可颂', '咖啡', '网红'],
    images: ['images/stores/photo-305-1.jpg'],
    description: '上海最火的面包房之一，可颂外酥内软，搭配咖啡完美',
    targetAudience: ['年轻人', '面包爱好者', '咖啡爱好者', '上班族'], bestTime: '早餐或下午茶', duration: '30分钟',
  },
  {
    id: 'sh-106', name: '鮨一(外滩店)', category: 'food', subcategory: '日本料理',
    city: '上海', district: '黄浦区', address: '中山东一路18号外滩18号',
    lat: 31.241, lng: 121.491, rating: 4.8, reviewCount: 1500, price: 1500,
    openTime: '11:30-14:00,17:30-22:00', tags: ['日本料理', 'omakase', '江户前', '高端', '寿司'],
    images: ['images/stores/photo-306-1.jpg'],
    description: '东京银座名店上海分店，江户前寿司omakase，主厨精选当日鱼获',
    targetAudience: ['高端消费', '日料爱好者', '商务宴请', '美食家'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'sh-107', name: 'Chateau Dionne(建国西路店)', category: 'food', subcategory: '西餐',
    city: '上海', district: '徐汇区', address: '建国西路486号',
    lat: 31.208, lng: 121.452, rating: 4.5, reviewCount: 3000, price: 350,
    openTime: '11:30-14:00,17:30-22:00', tags: ['西餐', '花园洋房', '红酒', '约会', '精致'],
    images: ['images/stores/photo-307-1.jpg'],
    description: '建国西路老洋房西餐馆，有上海最美露台之称',
    targetAudience: ['情侣', '约会', '商务人士', '美食爱好者'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'sh-108', name: 'Luneurs(幸福里店)', category: 'food', subcategory: '甜品',
    city: '上海', district: '长宁区', address: '幸福路67号幸福里',
    lat: 31.216, lng: 121.428, rating: 4.5, reviewCount: 8000, price: 40,
    openTime: '10:00-22:00', tags: ['甜品', '冰淇淋', '可颂', '法式', '网红'],
    images: ['images/stores/photo-308-1.jpg'],
    description: '上海人气法式烘焙甜品店，海盐焦糖冰淇淋是人气王',
    targetAudience: ['年轻人', '甜品爱好者', '情侣', '亲子'], bestTime: '下午茶', duration: '30分钟',
  },
  {
    id: 'sh-109', name: '蜀大侠火锅(徐汇店)', category: 'food', subcategory: '川菜',
    city: '上海', district: '徐汇区', address: '天钥桥路218号',
    lat: 31.186, lng: 121.437, rating: 4.3, reviewCount: 12000, price: 120,
    openTime: '11:00-02:00', tags: ['川菜', '火锅', '麻辣', '江湖风', '聚会'],
    images: ['images/stores/photo-309-1.jpg'],
    description: '成都老火锅品牌，武侠江湖风装修，大侠套餐人气高',
    targetAudience: ['年轻人', '朋友聚会', '辣味爱好者'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-110', name: '度小月(长宁来福士店)', category: 'food', subcategory: '台湾菜',
    city: '上海', district: '长宁区', address: '长宁路1123号来福士',
    lat: 31.223, lng: 121.413, rating: 4.2, reviewCount: 4000, price: 80,
    openTime: '11:00-22:00', tags: ['台湾菜', '担仔面', '小吃', '连锁', '亲民'],
    images: ['images/stores/photo-310-1.jpg'],
    description: '台湾百年老店上海分店，担仔面和肉燥饭经典地道',
    targetAudience: ['上班族', '家庭', '学生', '台湾美食爱好者'], bestTime: '午餐', duration: '45分钟',
  },
  {
    id: 'sh-111', name: '天泰(新天地店)', category: 'food', subcategory: '泰国菜',
    city: '上海', district: '黄浦区', address: '太仓路181号新天地北里',
    lat: 31.221, lng: 121.474, rating: 4.4, reviewCount: 6000, price: 200,
    openTime: '11:00-22:00', tags: ['泰国菜', '咖喱', '冬阴功', '新天地', '约会'],
    images: ['images/stores/photo-311-1.jpg'],
    description: '上海最早的泰餐厅之一，泰式咖喱蟹是招牌，新天地环境极佳',
    targetAudience: ['情侣', '朋友聚会', '泰国菜爱好者', '约会'], bestTime: '晚餐', duration: '1.5小时',
    ugcTags: ['咖喱蟹好吃', '冬阴功正宗', '新天地氛围好', '适合约会', '价格偏贵', '服务偏慢'],
    ugcSummary: '坐在新天地露天位吃咖喱蟹配椰青太惬意了，冬阴功汤酸辣度刚好。约会氛围满分就是价格在新天地也算贵的，两个人轻松500+',
    riskTags: ['价格偏高'],
  },
  {
    id: 'sh-112', name: '鸟啸(乌鲁木齐中路店)', category: 'food', subcategory: '日本料理',
    city: '上海', district: '徐汇区', address: '乌鲁木齐中路238号',
    lat: 31.213, lng: 121.445, rating: 4.5, reviewCount: 3500, price: 200,
    openTime: '17:00-02:00', tags: ['日本料理', '烧鸟', '居酒屋', '深夜', '小众'],
    images: ['images/stores/photo-312-1.jpg'],
    description: '上海烧鸟名店，从鸡皮到提灯一应俱全，深夜食堂气氛',
    targetAudience: ['年轻人', '日料爱好者', '夜宵爱好者', '情侣'], bestTime: '夜宵', duration: '1-1.5小时',
  },
  {
    id: 'sh-113', name: '万寿斋(虹口店)', category: 'food', subcategory: '小吃',
    city: '上海', district: '虹口区', address: '山阴路123号',
    lat: 31.271, lng: 121.491, rating: 4.3, reviewCount: 5000, price: 25,
    openTime: '06:00-14:00', tags: ['小吃', '小笼包', '三鲜馄饨', '老字号', '早餐'],
    images: ['images/stores/photo-313-1.jpg'],
    description: '虹口老牌小吃店，三鲜馄饨和小笼是上海人心中的白月光',
    targetAudience: ['本地居民', '中老年人', '游客', '早餐'], bestTime: '早餐', duration: '30分钟',
  },
  {
    id: 'sh-114', name: '老半斋(福州路店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '黄浦区', address: '福州路600号',
    lat: 31.236, lng: 121.483, rating: 4.1, reviewCount: 4000, price: 70,
    openTime: '06:30-14:00,17:00-20:30', tags: ['本帮菜', '刀鱼面', '老字号', '传统', '面食'],
    images: ['images/stores/photo-314-1.jpg'],
    description: '百年老店，刀鱼汁面是镇店之宝，春季刀鱼季食客云集',
    targetAudience: ['本地居民', '中老年人', '面食爱好者', '游客'], bestTime: '午餐', duration: '45分钟',
  },
  {
    id: 'sh-115', name: '哥老官重庆美蛙鱼头(杨浦店)', category: 'food', subcategory: '火锅',
    city: '上海', district: '杨浦区', address: '淞沪路77号万达广场',
    lat: 31.299, lng: 121.518, rating: 4.4, reviewCount: 15000, price: 130,
    openTime: '11:00-02:00', tags: ['火锅', '美蛙鱼头', '川味', '网红', '排队'],
    images: ['images/stores/photo-315-1.jpg'],
    description: '上海火锅排队王，美蛙鱼头锅底是招牌，蛙肉嫩滑入味',
    targetAudience: ['年轻人', '朋友聚会', '学生', '辣味爱好者'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-116', name: '德兴馆(广东路总店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '黄浦区', address: '广东路471号',
    lat: 31.234, lng: 121.489, rating: 4.3, reviewCount: 6000, price: 100,
    openTime: '06:00-14:00,17:00-21:00', tags: ['本帮菜', '焖蹄面', '老字号', '早餐', '熟食'],
    images: ['images/stores/photo-316-1.jpg'],
    description: '创建于1878年的上海老饭店，焖蹄二鲜面是镇店之宝',
    targetAudience: ['本地居民', '中老年人', '游客', '美食爱好者'], bestTime: '早餐或午餐', duration: '45分钟',
  },
  {
    id: 'sh-117', name: '很久以前羊肉串(闵行韩国街店)', category: 'food', subcategory: '烧烤',
    city: '上海', district: '闵行区', address: '虹泉路1078号',
    lat: 31.176, lng: 121.365, rating: 4.3, reviewCount: 8000, price: 85,
    openTime: '11:00-02:00', tags: ['烧烤', '羊肉串', '呼伦贝尔', '夜宵', '聚会'],
    images: ['images/stores/photo-317-1.jpg'],
    description: '呼伦贝尔草原羊肉现串现烤，韩国街上的中国味',
    targetAudience: ['年轻人', '朋友聚会', '夜宵爱好者'], bestTime: '晚餐或夜宵', duration: '1-2小时',
  },
  {
    id: 'sh-118', name: '韩国街(虹泉路)', category: 'food', subcategory: '韩餐',
    city: '上海', district: '闵行区', address: '虹泉路1101号',
    lat: 31.175, lng: 121.366, rating: 4.2, reviewCount: 12000, price: 90,
    openTime: '10:00-23:00', tags: ['韩餐', '炸鸡', '烤肉', '韩国超市', '特色街区'],
    images: ['images/stores/photo-318-1.jpg'],
    description: '上海韩国人聚居区的美食街，正宗韩式炸鸡和烤肉随处可见',
    targetAudience: ['年轻人', '韩流粉丝', '朋友聚会', '学生'], bestTime: '晚餐', duration: '1-2小时',
  },
  {
    id: 'sh-119', name: '同济大排档(杨浦店)', category: 'food', subcategory: '快餐',
    city: '上海', district: '杨浦区', address: '四平路1239号同济大学内',
    lat: 31.286, lng: 121.504, rating: 4.1, reviewCount: 8000, price: 25,
    openTime: '10:30-13:00,16:30-19:00', tags: ['校园美食', '大排档', '性价比', '夜宵', '学生'],
    images: ['images/stores/photo-319-1.jpg'],
    description: '同济大学食堂的传奇，烤串和麻辣香锅被学生封神',
    targetAudience: ['学生', '年轻人', '校园体验', '性价比'], bestTime: '晚餐', duration: '45分钟',
  },
  {
    id: 'sh-120', name: '文汇路美食街', category: 'food', subcategory: '小吃',
    city: '上海', district: '松江区', address: '文汇路大学城段',
    lat: 31.048, lng: 121.221, rating: 4.0, reviewCount: 6000, price: 30,
    openTime: '10:00-22:00', tags: ['小吃', '学生', '性价比', '美食街', '校园'],
    images: ['images/stores/photo-320-1.jpg'],
    description: '松江大学城学生最爱的美食街，奶茶炸鸡小吃一应俱全',
    targetAudience: ['学生', '年轻人', '性价比', '小吃爱好者'], bestTime: '下午或晚上', duration: '1小时',
  },
  {
    id: 'sh-121', name: '淀山湖鱼馆(青浦店)', category: 'food', subcategory: '农家菜',
    city: '上海', district: '青浦区', address: '淀山湖大道1号',
    lat: 31.130, lng: 121.033, rating: 4.1, reviewCount: 2000, price: 100,
    openTime: '10:00-21:00', tags: ['农家菜', '湖鲜', '白水鱼', '自然', '乡村'],
    images: ['images/stores/photo-321-1.jpg'],
    description: '淀山湖畔农家菜馆，白水鱼和大闸蟹是时令美味',
    targetAudience: ['游客', '家庭', '自驾游', '自然爱好者'], bestTime: '午餐', duration: '1小时',
  },
  {
    id: 'sh-122', name: '南翔小笼(嘉定南翔老街店)', category: 'food', subcategory: '小吃',
    city: '上海', district: '嘉定区', address: '南翔镇人民街42号',
    lat: 31.305, lng: 121.304, rating: 4.4, reviewCount: 8000, price: 40,
    openTime: '07:00-19:00', tags: ['小笼包', '传统', '嘉定', '老字号', '小吃'],
    images: ['images/stores/photo-322-1.jpg'],
    description: '南翔小笼的发源地，皮薄汤多，一笼接一笼停不下来',
    targetAudience: ['游客', '美食爱好者', '家庭', '本地居民'], bestTime: '早餐或午餐', duration: '30分钟',
  },
  {
    id: 'sh-123', name: '翠园(ifc店)', category: 'food', subcategory: '粤菜',
    city: '上海', district: '浦东新区', address: '世纪大道8号ifc商场',
    lat: 31.236, lng: 121.507, rating: 4.5, reviewCount: 6000, price: 300,
    openTime: '11:00-22:00', tags: ['粤菜', '点心', '高端', '海景', '宴请'],
    images: ['images/stores/photo-323-1.jpg'],
    description: '香港美心集团旗下粤菜馆，点心精致，是陆家嘴粤菜标杆',
    targetAudience: ['商务人士', '家庭', '宴请', '粤菜爱好者'], bestTime: '午餐', duration: '1.5小时',
  },
  {
    id: 'sh-124', name: '滩万日本料理(陆家嘴店)', category: 'food', subcategory: '日本料理',
    city: '上海', district: '浦东新区', address: '富城路33号香格里拉大酒店',
    lat: 31.238, lng: 121.500, rating: 4.6, reviewCount: 2000, price: 800,
    openTime: '11:30-14:00,17:30-22:00', tags: ['日本料理', '怀石料理', '铁板烧', '高端', '景观'],
    images: ['images/stores/photo-324-1.jpg'],
    description: '源自1830年的东京名店，怀石料理配外滩夜景',
    targetAudience: ['商务宴请', '高端消费', '日料爱好者', '情侣'], bestTime: '晚餐', duration: '2小时',
  },
  {
    id: 'sh-125', name: '惠食佳(黄浦店)', category: 'food', subcategory: '粤菜',
    city: '上海', district: '黄浦区', address: '中山东一路18号',
    lat: 31.242, lng: 121.492, rating: 4.3, reviewCount: 4000, price: 180,
    openTime: '11:00-22:00', tags: ['粤菜', '煲仔饭', '啫啫煲', '老字号', '人气'],
    images: ['images/stores/photo-325-1.jpg'],
    description: '广州老牌粤菜馆上海分店，啫啫煲是特色，煲仔饭香飘四溢',
    targetAudience: ['朋友聚会', '家庭', '粤菜爱好者', '美食爱好者'], bestTime: '晚餐', duration: '1.5小时',
    ugcTags: ['煲仔饭一绝', '啫啫煲镬气足', '粤菜地道', '预约方便', '油烟味重', '座位拥挤'],
    ugcSummary: '啫啫煲上桌时还在滋滋作响太有食欲了，腊味煲仔饭底下的锅巴是灵魂。但店不大座位挤，吃完一身啫啫煲的油烟味',
    riskTags: ['油烟味重', '座位拥挤'],
  },
  {
    id: 'sh-126', name: '荣小馆(新天地店)', category: 'food', subcategory: '江浙菜',
    city: '上海', district: '黄浦区', address: '太仓路181号新天地',
    lat: 31.220, lng: 121.473, rating: 4.4, reviewCount: 5000, price: 200,
    openTime: '11:00-22:00', tags: ['江浙菜', '台州菜', '海鲜', '新天地', '品质'],
    images: ['images/stores/photo-326-1.jpg'],
    description: '新荣记旗下中端品牌，台州小海鲜和面食精致可口',
    targetAudience: ['家庭', '朋友聚会', '商务人士', '美食爱好者'], bestTime: '午餐或晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-127', name: '兰心餐厅(进贤路店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '黄浦区', address: '进贤路130号',
    lat: 31.220, lng: 121.461, rating: 4.5, reviewCount: 4000, price: 100,
    openTime: '11:00-14:00,17:00-21:00', tags: ['本帮菜', '家常', '老店', '弄堂', '地道'],
    images: ['images/stores/photo-327-1.jpg'],
    description: '开了30多年的弄堂本帮菜馆，红烧肉和油爆虾是上海家常味',
    targetAudience: ['本地居民', '游客', '美食爱好者', '家庭'], bestTime: '晚餐', duration: '1小时',
    ugcTags: ['红烧肉一绝', '弄堂氛围好', '本地人认证', '家常味道', '店面小', '不能预约'],
    ugcSummary: '藏在进贤路弄堂里的宝藏本帮菜馆，红烧肉浓油赤酱甜咸适中，油爆虾壳脆肉嫩。就是店太小只有几张桌子还不能预约，建议掐着开门时间去',
    riskTags: ['店面小座位少', '不接受预约'],
  },
  {
    id: 'sh-128', name: '星巴克臻选(上海烘焙工坊)', category: 'food', subcategory: '咖啡',
    city: '上海', district: '静安区', address: '南京西路789号兴业太古汇',
    lat: 31.232, lng: 121.459, rating: 4.7, reviewCount: 25000, price: 80,
    openTime: '07:00-23:00', tags: ['咖啡', '烘焙工坊', '臻选', '拍照', '体验'],
    images: ['images/stores/photo-328-1.jpg'],
    description: '星巴克全球最大门店，沉浸式咖啡体验，咖啡豆烘焙生产线',
    targetAudience: ['咖啡爱好者', '年轻人', '游客', '拍照'], bestTime: '下午茶', duration: '1-2小时',
    ugcTags: ['沉浸式体验', '咖啡品质高', '拍照圣地', '人多嘈杂', '价格昂贵', '等位久'],
    ugcSummary: '咖啡爱好者的朝圣地，看着豆子从烘焙到萃取的全过程很治愈。但人真的太多了完全没法安静喝咖啡，更像旅游景点。一杯手冲80+只能说是为体验买单',
    riskTags: ['周末人满为患', '价格偏高', '噪音大不适合谈话'],
  },
  {
    id: 'sh-129', name: 'M Stand(新天地店)', category: 'food', subcategory: '咖啡',
    city: '上海', district: '黄浦区', address: '马当路245号新天地',
    lat: 31.220, lng: 121.475, rating: 4.3, reviewCount: 8000, price: 45,
    openTime: '08:00-22:00', tags: ['咖啡', '极简', '设计感', '网红', '打卡'],
    images: ['images/stores/photo-329-1.jpg'],
    description: '上海本土精品咖啡品牌，极简工业风设计，燕麦曲奇拿铁是首创',
    targetAudience: ['年轻人', '咖啡爱好者', '拍照', '设计爱好者'], bestTime: '下午茶', duration: '30分钟',
  },
  {
    id: 'sh-130', name: '佳家汤包(黄河路店)', category: 'food', subcategory: '小吃',
    city: '上海', district: '黄浦区', address: '黄河路9号',
    lat: 31.235, lng: 121.472, rating: 4.4, reviewCount: 7000, price: 35,
    openTime: '06:30-19:30', tags: ['小吃', '汤包', '蟹粉', '老字号', '早餐'],
    images: ['images/stores/photo-330-1.jpg'],
    description: '上海汤包名店，蟹粉鲜肉汤包现包现蒸，吃的时候小心烫',
    targetAudience: ['游客', '美食爱好者', '本地居民', '早餐'], bestTime: '早餐', duration: '30分钟',
  },
  {
    id: 'sh-131', name: '哈灵面馆(广西北路店)', category: 'food', subcategory: '面食',
    city: '上海', district: '黄浦区', address: '广西北路450号',
    lat: 31.237, lng: 121.478, rating: 4.3, reviewCount: 10000, price: 45,
    openTime: '07:00-21:00', tags: ['面食', '牛蛙面', '本帮', '网红', '实惠'],
    images: ['images/stores/photo-331-1.jpg'],
    description: '上海必吃面馆，牛蛙面是招牌，蛙肉多到盖住碗面',
    targetAudience: ['年轻人', '面食爱好者', '游客', '上班族'], bestTime: '午餐', duration: '30分钟',
  },
  {
    id: 'sh-132', name: '阿大葱油饼(南昌路店)', category: 'food', subcategory: '小吃',
    city: '上海', district: '黄浦区', address: '南昌路226号',
    lat: 31.218, lng: 121.463, rating: 4.3, reviewCount: 6000, price: 10,
    openTime: '06:00-15:00(周一闭店)', tags: ['小吃', '葱油饼', '排队', '老上海', '网红'],
    images: ['images/stores/photo-332-1.jpg'],
    description: '上海传奇葱油饼，阿大师傅手工现做，每天排队至少1小时',
    targetAudience: ['游客', '美食爱好者', '网红打卡', '本地居民'], bestTime: '早餐', duration: '15分钟(排队1小时)',
  },
  {
    id: 'sh-133', name: 'FOMO(大学路店)', category: 'food', subcategory: '甜品',
    city: '上海', district: '杨浦区', address: '大学路128号',
    lat: 31.301, lng: 121.511, rating: 4.2, reviewCount: 3500, price: 35,
    openTime: '10:00-22:00', tags: ['甜品', '冰淇淋', '舒芙蕾', '网红', '打卡'],
    images: ['images/stores/photo-333-1.jpg'],
    description: '大学路上的网红甜品店，舒芙蕾松饼轻盈如云',
    targetAudience: ['年轻人', '学生', '甜品爱好者', '情侣'], bestTime: '下午茶', duration: '30分钟',
  },
  {
    id: 'sh-134', name: '老吉士(天平路店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '徐汇区', address: '天平路41号',
    lat: 31.209, lng: 121.443, rating: 4.5, reviewCount: 4500, price: 180,
    openTime: '11:30-14:00,17:30-21:30', tags: ['本帮菜', '老洋房', '红烧肉', '家庭', '品质'],
    images: ['images/stores/photo-334-1.jpg'],
    description: '上海本帮菜的代表性餐厅之一，外婆红烧肉是上海一绝',
    targetAudience: ['家庭', '游客', '美食爱好者', '商务人士'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-135', name: '喜茶(来福士店)', category: 'food', subcategory: '奶茶',
    city: '上海', district: '长宁区', address: '长宁路1123号来福士B1',
    lat: 31.222, lng: 121.414, rating: 4.3, reviewCount: 15000, price: 30,
    openTime: '10:00-22:00', tags: ['奶茶', '果茶', '网红', '年轻人', '排队'],
    images: ['images/stores/photo-335-1.jpg'],
    description: '新茶饮开创品牌，多肉葡萄和芝芝莓莓人气最高',
    targetAudience: ['年轻人', '学生', '奶茶爱好者', '上班族'], bestTime: '下午茶', duration: '15分钟',
  },
  {
    id: 'sh-136', name: '红盔甲小龙虾(长寿路店)', category: 'food', subcategory: '川菜',
    city: '上海', district: '普陀区', address: '长寿路432号',
    lat: 31.239, lng: 121.444, rating: 4.4, reviewCount: 12000, price: 150,
    openTime: '16:00-02:00', tags: ['小龙虾', '烧烤', '夜宵', '啤酒', '聚��'],
    images: ['images/stores/photo-336-1.jpg'],
    description: '上海小龙虾界的顶流，冰镇和十三香口味最受欢迎',
    targetAudience: ['年轻人', '朋友聚会', '夜宵爱好者', '美食爱好者'], bestTime: '夜宵', duration: '1.5小时',
  },
  {
    id: 'sh-137', name: '聚酒屋(仙霞路店)', category: 'food', subcategory: '日本料理',
    city: '上海', district: '长宁区', address: '仙霞路335号',
    lat: 31.216, lng: 121.384, rating: 4.3, reviewCount: 3000, price: 150,
    openTime: '17:00-02:00', tags: ['日本料理', '居酒屋', '串烧', '深夜', '小众'],
    images: ['images/stores/photo-337-1.jpg'],
    description: '仙霞路居酒屋代表，日式串烧配上朝日啤酒，深夜治愈所',
    targetAudience: ['年轻人', '日料爱好者', '上班族', '夜宵'], bestTime: '夜宵', duration: '1-1.5小时',
  },
  {
    id: 'sh-138', name: '大壶春(四川中路总店)', category: 'food', subcategory: '小吃',
    city: '上海', district: '黄浦区', address: '四川中路136号',
    lat: 31.236, lng: 121.492, rating: 4.4, reviewCount: 5000, price: 20,
    openTime: '06:30-13:30', tags: ['小吃', '生煎', '全发酵', '老字号', '早餐'],
    images: ['images/stores/photo-338-1.jpg'],
    description: '上海老字号生煎品牌，全发酵面皮，肉馅鲜甜，底脆汤少',
    targetAudience: ['本地居民', '游客', '早餐', '美食爱好者'], bestTime: '早餐', duration: '20分钟',
  },
  {
    id: 'sh-139', name: '沪西老弄堂面馆(定西路店)', category: 'food', subcategory: '面食',
    city: '上海', district: '长宁区', address: '定西路685号',
    lat: 31.220, lng: 121.423, rating: 4.4, reviewCount: 6000, price: 35,
    openTime: '07:00-14:00', tags: ['面食', '本帮面', '辣肉面', '弄堂', '实惠'],
    images: ['images/stores/photo-339-1.jpg'],
    description: '弄堂里的上海本帮面馆，辣肉面和猪肝面是招牌',
    targetAudience: ['本地居民', '面食爱好者', '上班族', '游客'], bestTime: '午餐', duration: '30分钟',
  },
  {
    id: 'sh-140', name: '哥老官重庆美蛙鱼头(徐汇日月光店)', category: 'food', subcategory: '火锅',
    city: '上海', district: '徐汇区', address: '漕宝路33号日月光中心',
    lat: 31.168, lng: 121.422, rating: 4.5, reviewCount: 12000, price: 140,
    openTime: '11:00-02:00', tags: ['火锅', '美蛙鱼头', '川味', '网红', '创世纪冰粉'],
    images: ['images/stores/photo-340-1.jpg'],
    description: '哥老官徐汇分店，创世纪冰粉是每桌必点的解辣神器',
    targetAudience: ['年轻人', '朋友聚会', '学生', '辣味爱好者'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-141', name: '平成屋(仙霞路店)', category: 'food', subcategory: '日本料理',
    city: '上海', district: '长宁区', address: '仙霞路158号',
    lat: 31.213, lng: 121.388, rating: 4.2, reviewCount: 8000, price: 100,
    openTime: '11:00-02:00', tags: ['日本料理', '居酒屋', '日剧', '平价', '深夜'],
    images: ['images/stores/photo-341-1.jpg'],
    description: '上海人气居酒屋，装修如日剧场景，烤牛舌和梅酒绝配',
    targetAudience: ['年轻人', '日剧迷', '朋友聚会', '上班族'], bestTime: '夜宵', duration: '1-1.5小时',
  },
  {
    id: 'sh-142', name: 'POPEYES(新天地店)', category: 'food', subcategory: '快餐',
    city: '上海', district: '黄浦区', address: '淮海中路566号',
    lat: 31.223, lng: 121.469, rating: 4.1, reviewCount: 6000, price: 45,
    openTime: '10:00-22:00', tags: ['快餐', '炸鸡', '美式', '排队', '网红'],
    images: ['images/stores/photo-342-1.jpg'],
    description: '美国网红炸鸡上海首店，酪乳脆皮鸡腿堡风靡全城',
    targetAudience: ['年轻人', '学生', '炸鸡爱好者', '快餐'], bestTime: '午餐', duration: '30分钟',
  },
  {
    id: 'sh-143', name: 'shake shack(新天地店)', category: 'food', subcategory: '快餐',
    city: '上海', district: '黄浦区', address: '太仓路181号新天地',
    lat: 31.221, lng: 121.473, rating: 4.3, reviewCount: 10000, price: 80,
    openTime: '10:00-22:00', tags: ['快餐', '汉堡', '美式', '奶昔', '网红'],
    images: ['images/stores/photo-343-1.jpg'],
    description: '纽约神级汉堡上海首店，招牌牛肉堡和上海限定奶昔',
    targetAudience: ['年轻人', '游客', '学生', '汉堡爱好者'], bestTime: '午餐', duration: '30分钟',
    ugcTags: ['牛肉堡多汁', '奶昔好喝', '新天地位置好', '价格偏高', '排队久', '座位少'],
    ugcSummary: '牛肉堡确实比普通快餐好吃很多肉饼juicy，上海限定奶昔也有特色。但80块吃个汉堡属实奢侈，新天地这家座位太少了经常要端着吃',
    riskTags: ['座位紧张', '价格偏高'],
  },
  {
    id: 'sh-144', name: '点都德(静安大悦城店)', category: 'food', subcategory: '粤菜',
    city: '上海', district: '静安区', address: '西藏北路198号大悦城',
    lat: 31.245, lng: 121.472, rating: 4.4, reviewCount: 10000, price: 100,
    openTime: '08:00-22:00', tags: ['粤菜', '早茶', '点心', '广州', '排队'],
    images: ['images/stores/photo-344-1.jpg'],
    description: '广州老字号茶楼上海分店，红米肠和虾饺王是必点',
    targetAudience: ['家庭', '朋友聚会', '粤菜爱好者', '游客'], bestTime: '早茶或午餐', duration: '1-1.5小时',
    ugcTags: ['点心精致', '红米肠必点', '服务热情', '性价比高', '适合家庭', '早茶氛围好', '虾饺晶莹剔透'],
    ugcSummary: '静安大悦城里性价比超高的早茶，红米肠外酥内嫩虾饺皮薄馅大，服务员阿姨特别热情一直帮忙添茶。人均100吃到撑还打包，比隔壁那些米其林洋房实在太多了，周末带爸妈来超开心',
    riskTags: [],
  },
  {
    id: 'sh-145', name: '久久滴水洞(进贤路店)', category: 'food', subcategory: '创意菜',
    city: '上海', district: '黄浦区', address: '进贤路167号',
    lat: 31.219, lng: 121.460, rating: 4.3, reviewCount: 3000, price: 120,
    openTime: '11:00-22:00', tags: ['创意菜', '湘菜', '隐藏', '弄堂', '小众'],
    images: ['images/stores/photo-345-1.jpg'],
    description: '弄堂深处的隐藏美食，私房湘菜和创意小炒令人惊喜',
    targetAudience: ['美食爱好者', '年轻人', '探索者', '情侣'], bestTime: '晚餐', duration: '1小时',
  },
  {
    id: 'sh-146', name: '蟹榭(静安寺店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '静安区', address: '南京西路1601号静安寺',
    lat: 31.228, lng: 121.451, rating: 4.5, reviewCount: 4000, price: 350,
    openTime: '11:00-14:00,17:00-21:30', tags: ['本帮菜', '大闸蟹', '蟹宴', '高端', '季节'],
    images: ['images/stores/photo-346-1.jpg'],
    description: '上海顶级蟹宴餐厅，秃黄油捞饭是秋季限定极品',
    targetAudience: ['商务宴请', '美食家', '高端消费', '大闸蟹爱好者'], bestTime: '秋季(蟹季)', duration: '2小时',
    ugcTags: ['蟹宴顶级', '秃黄油一绝', '秋季限定', '服务优秀', '价格昂贵', '非蟹季菜品少'],
    ugcSummary: '上海蟹宴的天花板，秃黄油捞饭蟹香浓郁拌饭能干掉三碗。但人均350只有蟹季来才值，其他季节菜单少了很多选择，建议9-11月来',
    riskTags: ['非蟹季体验下降', '人均较高'],
  },
  {
    id: 'sh-147', name: '本帮菜馆(瑞金二路店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '黄浦区', address: '瑞金二路118号',
    lat: 31.215, lng: 121.463, rating: 4.2, reviewCount: 3500, price: 90,
    openTime: '11:00-14:00,17:00-21:00', tags: ['本帮菜', '家常', '实惠', '本地风味', '社区'],
    images: ['images/stores/photo-347-1.jpg'],
    description: '社区本帮菜馆，糖醋排骨和草头圈子是上海人最爱的家常菜',
    targetAudience: ['本地居民', '家庭', '社区', '中老年人'], bestTime: '晚餐', duration: '1小时',
  },
  {
    id: 'sh-148', name: 'Taco Bell(南京西路店)', category: 'food', subcategory: '快餐',
    city: '上海', district: '静安区', address: '南京西路1618号',
    lat: 31.230, lng: 121.453, rating: 4.0, reviewCount: 5000, price: 50,
    openTime: '10:00-22:00', tags: ['快餐', '墨西哥菜', '塔可', '连锁', '休闲'],
    images: ['images/stores/photo-348-1.jpg'],
    description: '美国墨西哥快餐连锁，牛肉塔可和芝士玉米片适合快速解决',
    targetAudience: ['年轻人', '学生', '上班族', '快餐'], bestTime: '午餐', duration: '30分钟',
    ugcTags: ['出餐快', '塔可还行', '价格实惠', '口味一般', '不如美版好吃', '份量小'],
    ugcSummary: '南京西路附近难得50块能吃饱的地方，牛肉塔可中规中矩。但和美国原版比差了不少，芝士给得吝啬，更适合快速解决午饭',
    riskTags: [],
  },
  {
    id: 'sh-149', name: '上海老饭店(福佑路店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '黄浦区', address: '福佑路242号豫园',
    lat: 31.229, lng: 121.494, rating: 4.3, reviewCount: 8000, price: 180,
    openTime: '11:00-14:00,17:00-22:00', tags: ['本帮菜', '老字号', '八宝鸭', '豫园', '宴请'],
    images: ['images/stores/photo-349-1.jpg'],
    description: '创建于1875年的上海菜鼻祖，八宝鸭和扣三丝是经典',
    targetAudience: ['游客', '家庭聚会', '宴请', '中老年人'], bestTime: '晚餐', duration: '1.5小时',
    ugcTags: ['八宝鸭经典', '百年老店', '上海菜鼻祖', '请客有面子', '游客太多', '环境老旧', '服务一般'],
    ugcSummary: '上海菜的活化石，八宝鸭软烂入味扣三丝刀工精细。但挨着豫园游客实在太多了，环境也老旧得像80年代国营饭店，服务员态度看运气',
    riskTags: ['游客过多', '环境老旧', '服务不稳定'],
  },
  {
    id: 'sh-150', name: '蔡嘉法式甜品(新天地店)', category: 'food', subcategory: '甜品',
    city: '上海', district: '黄浦区', address: '黄陂南路380号新天地',
    lat: 31.218, lng: 121.475, rating: 4.5, reviewCount: 4000, price: 80,
    openTime: '10:00-22:00', tags: ['甜品', '法式', '下午茶', '拿破仑', '网红'],
    images: ['images/stores/photo-350-1.jpg'],
    description: '上海法式甜品标杆，金牌拿破仑酥每天限量供不应求',
    targetAudience: ['女生', '情侣', '下午茶', '甜品爱好者'], bestTime: '下午茶', duration: '1小时',
    ugcTags: ['拿破仑一绝', '下午茶首选', '拍照出片', '限量供应', '价格偏高', '排队久'],
    ugcSummary: '上海拿破仑酥的天花板，酥皮层层分明奶油轻盈不腻，配壶红茶就是完美下午。但每天限量下午两点前就卖完了，想吃一定要早去',
    riskTags: ['拿破仑每日限量', '周末需排队'],
  },
  {
    id: 'sh-151', name: '谷田稻香(宝山万达店)', category: 'food', subcategory: '快餐',
    city: '上海', district: '宝山区', address: '一二八纪念路988号万达广场',
    lat: 31.332, lng: 121.444, rating: 4.0, reviewCount: 4000, price: 35,
    openTime: '10:00-21:30', tags: ['快餐', '瓦锅饭', '中式', '性价比', '连锁'],
    images: ['images/stores/photo-351-1.jpg'],
    description: '瓦锅饭快餐品牌，现点现煲，米香四溢经济实惠',
    targetAudience: ['上班族', '家庭', '学生', '快餐'], bestTime: '午餐', duration: '30分钟',
  },
  {
    id: 'sh-152', name: '德大西菜社(云南南路店)', category: 'food', subcategory: '西餐',
    city: '上海', district: '黄浦区', address: '云南南路2号',
    lat: 31.233, lng: 121.485, rating: 4.2, reviewCount: 3000, price: 120,
    openTime: '10:00-21:00', tags: ['西餐', '海派西餐', '炸猪排', '罗宋汤', '老字号'],
    images: ['images/stores/photo-352-1.jpg'],
    description: '上海海派西餐的代表，炸猪排配辣酱油是几代人的记忆',
    targetAudience: ['中老年人', '怀旧', '本地居民', '游客'], bestTime: '午餐', duration: '1小时',
  },
  {
    id: 'sh-153', name: '兰亭餐厅(嵩山路店)', category: 'food', subcategory: '本帮菜',
    city: '上海', district: '黄浦区', address: '嵩山路107号',
    lat: 31.222, lng: 121.477, rating: 4.1, reviewCount: 2500, price: 70,
    openTime: '11:00-14:00,17:00-21:00', tags: ['本帮菜', '排档', '实惠', '家常', '弄堂'],
    images: ['images/stores/photo-353-1.jpg'],
    description: '弄堂本帮菜大排档，鸡骨酱和腐乳肉最受欢迎',
    targetAudience: ['本地居民', '朋友聚会', '游客', '实惠'], bestTime: '晚餐', duration: '1小时',
  },
  {
    id: 'sh-154', name: '人和馆(肇嘉浜路店)', category: 'food', subcategory: '湘菜',
    city: '上海', district: '徐汇区', address: '肇嘉浜路407号',
    lat: 31.205, lng: 121.455, rating: 4.5, reviewCount: 7000, price: 120,
    openTime: '11:00-22:00', tags: ['湘菜', '剁椒鱼头', '小炒肉', '地道', '人气'],
    images: ['images/stores/photo-354-1.jpg'],
    description: '上海最正宗的湖南菜之一，剁椒鱼头配手工面是招牌',
    targetAudience: ['朋友聚会', '湘菜爱好者', '年轻人', '家庭'], bestTime: '晚餐', duration: '1.5小时',
  },
  {
    id: 'sh-155', name: '龙华素斋(龙华寺店)', category: 'food', subcategory: '素食',
    city: '上海', district: '徐汇区', address: '龙华路2853号龙华寺内',
    lat: 31.177, lng: 121.446, rating: 4.5, reviewCount: 3500, price: 40,
    openTime: '07:00-14:00', tags: ['素食', '素面', '寺庙', '禅意', '健康'],
    images: ['images/stores/photo-355-1.jpg'],
    description: '龙华寺内的素斋馆，素面和素鸭是香客们的最爱',
    targetAudience: ['信众', '素食爱好者', '游客', '中老年人'], bestTime: '午餐', duration: '30分钟',
  },
  // ── 景点 (sh-156 ~ sh-200) ──
  {
    id: 'sh-156', name: '浦东美术馆', category: 'attraction', subcategory: '美术馆',
    city: '上海', district: '浦东新区', address: '滨江大道2777号',
    lat: 31.240, lng: 121.503, rating: 4.7, reviewCount: 15000, price: 150,
    openTime: '10:00-18:00(周一闭馆)', tags: ['美术馆', '让·努维尔', '建筑', '展览', '外滩景观'],
    images: ['images/stores/photo-356-1.jpg'],
    description: '由让·努维尔设计的顶级美术馆，镜厅和天台可观外滩全景',
    targetAudience: ['艺术爱好者', '建筑迷', '拍照', '游客', '文艺青年'], bestTime: '下午(看日落)', duration: '2-3小时',
  },
  {
    id: 'sh-157', name: '上海天文馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '浦东新区', address: '临港大道380号',
    lat: 30.916, lng: 121.923, rating: 4.8, reviewCount: 25000, price: 30,
    openTime: '09:30-16:00(周一闭馆)', tags: ['博物馆', '天文', '科技', '亲子', '建筑'],
    images: ['images/stores/photo-357-1.jpg'],
    description: '全球最大的天文馆，三体建筑惊艳，家园展区的8K影片不容错过',
    targetAudience: ['亲子', '科技爱好者', '学生', '天文迷', '建筑迷'], bestTime: '工作日(预约更易)', duration: '半天至一天',
  },
  {
    id: 'sh-158', name: '前滩休闲公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '浦东新区', address: '前滩大道',
    lat: 31.153, lng: 121.489, rating: 4.4, reviewCount: 8000, price: 0,
    openTime: '全天', tags: ['公园', '滨江', '露营', '骑行', '亲子'],
    images: ['images/stores/photo-358-1.jpg'],
    description: '前滩区域的滨江公园，草坪宽阔适合露营野餐和骑行',
    targetAudience: ['亲子', '露营', '骑行爱好者', '家庭', '年轻人'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-159', name: '衡山和集', category: 'attraction', subcategory: '书店',
    city: '上海', district: '徐汇区', address: '衡山路880号',
    lat: 31.207, lng: 121.446, rating: 4.4, reviewCount: 4000, price: 0,
    openTime: '10:00-22:00', tags: ['书店', '文艺', '杂志', '咖啡', '老洋房'],
    images: ['images/stores/photo-359-1.jpg'],
    description: '衡山路上最美的书店，三层洋房汇集国内外小众杂志',
    targetAudience: ['文艺青年', '书虫', '设计爱好者', '咖啡爱好者'], bestTime: '下午', duration: '1小时',
  },
  {
    id: 'sh-160', name: '武康大楼', category: 'attraction', subcategory: '历史建筑',
    city: '上海', district: '徐汇区', address: '淮海中路1850号',
    lat: 31.210, lng: 121.440, rating: 4.6, reviewCount: 20000, price: 0,
    openTime: '外观全天', tags: ['历史建筑', '邬达克', '地标', '拍照', '网红'],
    images: ['images/stores/photo-360-1.jpg'],
    description: '邬达克设计的船型公寓楼，上海最火的街拍地标之一',
    targetAudience: ['拍照', '建筑爱好者', '游客', '文艺青年', '网红打卡'], bestTime: '下午', duration: '30分钟',
  },
  {
    id: 'sh-161', name: '上海电影博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '徐汇区', address: '漕溪北路595号',
    lat: 31.174, lng: 121.438, rating: 4.4, reviewCount: 5000, price: 60,
    openTime: '09:00-16:30(周一闭馆)', tags: ['博物馆', '电影', '上海电影制片厂', '文化', '亲子'],
    images: ['images/stores/photo-361-1.jpg'],
    description: '原上海电影制片厂旧址，四层展厅讲述中国电影百年历史',
    targetAudience: ['电影爱好者', '亲子', '文化爱好者', '游客'], bestTime: '任何季节', duration: '2-3小时',
  },
  {
    id: 'sh-162', name: '上海展览中心', category: 'attraction', subcategory: '建筑',
    city: '上海', district: '静安区', address: '延安中路1000号',
    lat: 31.228, lng: 121.453, rating: 4.3, reviewCount: 5000, price: 0,
    openTime: '外观全天(展览期间可入内)', tags: ['建筑', '苏联风格', '展览', '地标', '历史'],
    images: ['images/stores/photo-362-1.jpg'],
    description: '俄罗斯古典主义建筑风格，原中苏友好大厦，顶尖展览场地',
    targetAudience: ['建筑爱好者', '游客', '展览观众', '摄影爱好者'], bestTime: '展览期间', duration: '1-2小时',
  },
  {
    id: 'sh-163', name: '800秀', category: 'attraction', subcategory: '文创园',
    city: '上海', district: '静安区', address: '常德路800号',
    lat: 31.234, lng: 121.446, rating: 4.2, reviewCount: 2500, price: 0,
    openTime: '全天', tags: ['文创园', '时尚', '秀场', '咖啡', '设计'],
    images: ['images/stores/photo-363-1.jpg'],
    description: '前身是人民电机厂，现在是上海时尚地标和创意办公园区',
    targetAudience: ['文艺青年', '设计师', '拍照', '咖啡爱好者'], bestTime: '下午', duration: '1小时',
  },
  {
    id: 'sh-164', name: '同乐坊', category: 'attraction', subcategory: '文创园',
    city: '上海', district: '静安区', address: '余姚路66号',
    lat: 31.236, lng: 121.445, rating: 4.1, reviewCount: 2000, price: 0,
    openTime: '全天', tags: ['文创园', '酒吧', '餐厅', '夜生活', '小众'],
    images: ['images/stores/photo-364-1.jpg'],
    description: '静安区的创意园区，白天咖啡晚上酒吧，年轻人聚集地',
    targetAudience: ['年轻人', '酒吧爱好者', '美食爱好者', '拍照'], bestTime: '晚上', duration: '1-2小时',
  },
  {
    id: 'sh-165', name: '上海文化广场', category: 'attraction', subcategory: '剧场',
    city: '上海', district: '黄浦区', address: '复兴中路597号',
    lat: 31.217, lng: 121.463, rating: 4.5, reviewCount: 8000, price: 200,
    openTime: '演出时间(见排期)', tags: ['剧场', '音乐剧', '绿地', '文化', '建筑'],
    images: ['images/stores/photo-365-1.jpg'],
    description: '上海音乐剧圣地，下沉式剧场和户外绿地是市民休闲好去处',
    targetAudience: ['音乐剧爱好者', '文化爱好者', '情侣', '市民'], bestTime: '演出季', duration: '2-3小时',
  },
  {
    id: 'sh-166', name: '外滩源', category: 'attraction', subcategory: '历史街区',
    city: '上海', district: '黄浦区', address: '南苏州路外滩',
    lat: 31.244, lng: 121.489, rating: 4.4, reviewCount: 6000, price: 0,
    openTime: '全天', tags: ['历史建筑', '外滩', '英伦', '拍照', '小众'],
    images: ['images/stores/photo-366-1.jpg'],
    description: '外滩的起点，原英国领事馆和划船俱乐部等百年建筑群',
    targetAudience: ['摄影爱好者', '游客', '建筑爱好者', '历史爱好者'], bestTime: '傍晚', duration: '1-2小时',
  },
  {
    id: 'sh-167', name: '福州路文化街', category: 'attraction', subcategory: '文化街区',
    city: '上海', district: '黄浦区', address: '福州路',
    lat: 31.235, lng: 121.484, rating: 4.3, reviewCount: 5000, price: 0,
    openTime: '全天(各店铺不同)', tags: ['文化街', '书店', '文具', '文房四宝', '老上海'],
    images: ['images/stores/photo-367-1.jpg'],
    description: '上海最有文化的马路，古籍书店和外文书店是爱书人的天堂',
    targetAudience: ['书虫', '文化爱好者', '游客', '学生'], bestTime: '下午', duration: '1-2小时',
  },
  {
    id: 'sh-168', name: '虹口足球场', category: 'attraction', subcategory: '体育场馆',
    city: '上海', district: '虹口区', address: '东江湾路444号',
    lat: 31.274, lng: 121.483, rating: 4.2, reviewCount: 8000, price: 100,
    openTime: '比赛日开放', tags: ['足球', '申花', '中超', '体育', '地标'],
    images: ['images/stores/photo-368-1.jpg'],
    description: '上海申花主场，中国第一家专业足球场，比赛日气氛炸裂',
    targetAudience: ['足球迷', '体育爱好者', '年轻人', '申花球迷'], bestTime: '比赛日', duration: '3小时(含比赛)',
  },
  {
    id: 'sh-169', name: '鲁迅公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '虹口区', address: '四川北路2288号',
    lat: 31.275, lng: 121.491, rating: 4.3, reviewCount: 6000, price: 0,
    openTime: '06:00-18:00', tags: ['公园', '鲁迅', '晨练', '历史', '梅园'],
    images: ['images/stores/photo-369-1.jpg'],
    description: '原虹口公园，鲁迅墓和鲁迅纪念馆坐落其中，春天梅花盛开',
    targetAudience: ['本地居民', '中老年人', '文化爱好者', '家庭'], bestTime: '春季(梅花)', duration: '1小时',
  },
  {
    id: 'sh-170', name: '和平公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '虹口区', address: '大连路1131号',
    lat: 31.267, lng: 121.511, rating: 4.1, reviewCount: 4000, price: 0,
    openTime: '06:00-21:00', tags: ['公园', '动物岛', '亲子', '休闲', '社区'],
    images: ['images/stores/photo-370-1.jpg'],
    description: '虹口居民的后花园，有小型动物岛适合亲子游',
    targetAudience: ['亲子', '本地居民', '家庭', '中老年人'], bestTime: '春秋两季', duration: '1小时',
  },
  {
    id: 'sh-171', name: '中山公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '长宁区', address: '长宁路780号',
    lat: 31.224, lng: 121.418, rating: 4.3, reviewCount: 8000, price: 0,
    openTime: '06:00-21:00', tags: ['公园', '龙之梦', '跑步', '休闲', '相亲角'],
    images: ['images/stores/photo-371-1.jpg'],
    description: '长宁区最大的公园，周末有著名的相亲角，市民休闲首选',
    targetAudience: ['本地居民', '家庭', '跑步爱好者', '中老年人'], bestTime: '春秋两季', duration: '1小时',
  },
  {
    id: 'sh-172', name: '天山公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '长宁区', address: '延安西路1731号',
    lat: 31.215, lng: 121.405, rating: 4.0, reviewCount: 2000, price: 0,
    openTime: '06:00-21:00', tags: ['公园', '湖泊', '安静', '小众', '社区'],
    images: ['images/stores/photo-372-1.jpg'],
    description: '长宁区的安静小公园，湖心亭和垂柳颇有江南韵味',
    targetAudience: ['本地居民', '中老年人', '散步', '安静'], bestTime: '任何季节', duration: '1小时',
  },
  {
    id: 'sh-173', name: '复旦大学', category: 'attraction', subcategory: '大学校园',
    city: '上海', district: '杨浦区', address: '邯郸路220号',
    lat: 31.298, lng: 121.503, rating: 4.8, reviewCount: 15000, price: 0,
    openTime: '全天', tags: ['大学', '名校', '相辉堂', '梧桐', '学术'],
    images: ['images/stores/photo-373-1.jpg'],
    description: '中国顶尖学府，梧桐大道和相辉堂是复旦人的精神象征',
    targetAudience: ['学生', '游客', '文化爱好者', '亲子', '摄影爱好者'], bestTime: '秋季(梧桐落叶)', duration: '1-2小时',
  },
  {
    id: 'sh-174', name: '同济大学', category: 'attraction', subcategory: '大学校园',
    city: '上海', district: '杨浦区', address: '四平路1239号',
    lat: 31.286, lng: 121.504, rating: 4.7, reviewCount: 10000, price: 0,
    openTime: '全天', tags: ['大学', '建筑', '樱花', '名校', '三好坞'],
    images: ['images/stores/photo-374-1.jpg'],
    description: '以建筑系闻名的大学，樱花大道春天美不胜收',
    targetAudience: ['学生', '游客', '摄影爱好者', '亲子'], bestTime: '春季(樱花)', duration: '1-2小时',
  },
  {
    id: 'sh-175', name: '杨浦滨江', category: 'attraction', subcategory: '滨江步道',
    city: '上海', district: '杨浦区', address: '杨树浦路滨江段',
    lat: 31.266, lng: 121.537, rating: 4.4, reviewCount: 6000, price: 0,
    openTime: '全天', tags: ['滨江', '工业遗址', '骑行', '跑步', '景观'],
    images: ['images/stores/photo-375-1.jpg'],
    description: '杨浦滨江工业遗址改造的公共空间，行走在历史与未来之间',
    targetAudience: ['骑行爱好者', '跑步', '摄影爱好者', '家庭', '年轻人'], bestTime: '傍晚', duration: '1-2小时',
  },
  {
    id: 'sh-176', name: '闵行博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '闵行区', address: '新镇路1538号',
    lat: 31.120, lng: 121.361, rating: 4.2, reviewCount: 2500, price: 0,
    openTime: '09:00-16:30(周一闭馆)', tags: ['博物馆', '地方史', '马桥文化', '亲子', '小众'],
    images: ['images/stores/photo-376-1.jpg'],
    description: '展示上海县历史和马桥文化的博物馆，了解上海起源',
    targetAudience: ['亲子', '学生', '历史爱好者', '文化爱好者'], bestTime: '任何季节', duration: '1-2小时',
  },
  {
    id: 'sh-177', name: '锦江乐园', category: 'attraction', subcategory: '主题乐园',
    city: '上海', district: '闵行区', address: '虹梅路201号',
    lat: 31.144, lng: 121.410, rating: 4.1, reviewCount: 10000, price: 130,
    openTime: '09:00-17:30', tags: ['主题乐园', '摩天轮', '亲子', '怀旧', '刺激'],
    images: ['images/stores/photo-377-1.jpg'],
    description: '上海第一座大型游乐园，摩天轮是上海西南地标',
    targetAudience: ['亲子', '年轻人', '家庭', '游客'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-178', name: '韩湘水博园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '闵行区', address: '江川路3800号',
    lat: 31.010, lng: 121.419, rating: 4.0, reviewCount: 3000, price: 30,
    openTime: '08:00-17:00', tags: ['园林', '水景', '古桥', '生态', '小众'],
    images: ['images/stores/photo-378-1.jpg'],
    description: '以水景和古桥为特色的生态园林，黄浦江上游水源地',
    targetAudience: ['摄影爱好者', '亲子', '家庭', '自然爱好者'], bestTime: '春夏两季', duration: '半天',
  },
  {
    id: 'sh-179', name: '吴淞炮台湾湿地森林公园', category: 'attraction', subcategory: '湿地',
    city: '上海', district: '宝山区', address: '塘后路206号',
    lat: 31.403, lng: 121.518, rating: 4.3, reviewCount: 8000, price: 10,
    openTime: '06:00-17:00', tags: ['湿地', '炮台', '长江口', '观鸟', '历史'],
    images: ['images/stores/photo-379-1.jpg'],
    description: '长江与黄浦江交汇处的湿地公园，清代的吴淞炮台遗址',
    targetAudience: ['亲子', '观鸟爱好者', '摄影爱好者', '历史爱好者'], bestTime: '春秋候鸟季', duration: '半天',
  },
  {
    id: 'sh-180', name: '上海大学(宝山校区)', category: 'attraction', subcategory: '大学校园',
    city: '上海', district: '宝山区', address: '上大路99号',
    lat: 31.320, lng: 121.393, rating: 4.2, reviewCount: 5000, price: 0,
    openTime: '全天', tags: ['大学', '现代建筑', '泮池', '文化', '校园'],
    images: ['images/stores/photo-380-1.jpg'],
    description: '上海市属重点大学，校园泮池和图书馆是标志性景观',
    targetAudience: ['学生', '游客', '文化爱好者'], bestTime: '春秋两季', duration: '1小时',
  },
  {
    id: 'sh-181', name: '东滩湿地公园', category: 'attraction', subcategory: '湿地',
    city: '上海', district: '崇明区', address: '东滩湿地',
    lat: 31.519, lng: 121.963, rating: 4.3, reviewCount: 5000, price: 50,
    openTime: '08:30-16:30', tags: ['湿地', '候鸟', '日出', '生态', '自然'],
    images: ['images/stores/photo-381-1.jpg'],
    description: '崇明岛东端的国际重要湿地，观鸟和看日出是最佳体验',
    targetAudience: ['观鸟爱好者', '摄影爱好者', '自然爱好者', '亲子'], bestTime: '春秋候鸟季', duration: '半天至一天',
  },
  {
    id: 'sh-182', name: '西沙湿地', category: 'attraction', subcategory: '湿地',
    city: '上海', district: '崇明区', address: '绿华镇堡湖路',
    lat: 31.688, lng: 121.197, rating: 4.2, reviewCount: 3500, price: 0,
    openTime: '08:30-16:30', tags: ['湿地', '芦苇', '木栈道', '日落', '自然'],
    images: ['images/stores/photo-382-1.jpg'],
    description: '崇明岛西端的湿地公园，木栈道穿行芦苇荡，日落绝美',
    targetAudience: ['摄影爱好者', '自然爱好者', '情侣', '亲子'], bestTime: '秋季(芦苇金黄)', duration: '半天',
  },
  {
    id: 'sh-183', name: '碧海金沙', category: 'attraction', subcategory: '海滩',
    city: '上海', district: '奉贤区', address: '海湾旅游区海涵路6号',
    lat: 30.821, lng: 121.569, rating: 4.0, reviewCount: 8000, price: 65,
    openTime: '08:30-17:00(夏季开放)', tags: ['海滩', '人工沙滩', '水上运动', '夏季', '亲子'],
    images: ['images/stores/photo-383-1.jpg'],
    description: '上海最大的人工沙滩，夏季玩水首选，沙滩足球和摩托艇',
    targetAudience: ['亲子', '年轻人', '水上运动', '夏季'], bestTime: '夏季', duration: '一整天',
  },
  {
    id: 'sh-184', name: '上海之鱼', category: 'attraction', subcategory: '公园',
    city: '上海', district: '奉贤区', address: '金海社区',
    lat: 30.927, lng: 121.488, rating: 4.1, reviewCount: 3500, price: 0,
    openTime: '全天', tags: ['公园', '金鱼造型', '湖泊', '野餐', '新地标'],
    images: ['images/stores/photo-384-1.jpg'],
    description: '奉贤新城的金鱼造型人工湖，环湖绿道和花海是周末好去处',
    targetAudience: ['家庭', '亲子', '本地居民', '野餐'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-185', name: '金山嘴渔村', category: 'attraction', subcategory: '古村落',
    city: '上海', district: '金山区', address: '山阳镇沪杭公路',
    lat: 30.729, lng: 121.387, rating: 4.2, reviewCount: 5000, price: 0,
    openTime: '全天', tags: ['渔村', '海鲜', '老街', '传统', '摄影'],
    images: ['images/stores/photo-385-1.jpg'],
    description: '上海最后一个渔村，老街海鲜一条街，渔民画和渔具陈列馆',
    targetAudience: ['游客', '摄影爱好者', '海鲜爱好者', '亲子'], bestTime: '秋季(海鲜肥美)', duration: '半天',
  },
  {
    id: 'sh-186', name: '花开海上生态园', category: 'attraction', subcategory: '花海',
    city: '上海', district: '金山区', address: '朱泾镇待泾村',
    lat: 30.875, lng: 121.159, rating: 4.3, reviewCount: 6000, price: 50,
    openTime: '08:00-17:00', tags: ['花海', '梅园', '樱花', '拍照', '网红'],
    images: ['images/stores/photo-386-1.jpg'],
    description: '金山大型花海公园，梅花樱花地肤草按季节轮换',
    targetAudience: ['拍照', '女生', '亲子', '摄影爱好者', '情侣'], bestTime: '春季和秋季', duration: '半天',
  },
  {
    id: 'sh-187', name: '松江方塔园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '松江区', address: '中山东路235号',
    lat: 31.009, lng: 121.254, rating: 4.3, reviewCount: 4000, price: 12,
    openTime: '07:00-17:00', tags: ['园林', '古塔', '宋代', '清幽', '小众'],
    images: ['images/stores/photo-387-1.jpg'],
    description: '以宋代方塔为核心的古典园林，安静清幽游客稀少',
    targetAudience: ['文化爱好者', '摄影爱好者', '游客', '中老年人'], bestTime: '任何季节', duration: '1-2小时',
  },
  {
    id: 'sh-188', name: '醉白池', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '松江区', address: '人民南路64号',
    lat: 31.006, lng: 121.238, rating: 4.3, reviewCount: 5000, price: 12,
    openTime: '07:00-17:00', tags: ['园林', '古树', '池塘', '江南', '安静'],
    images: ['images/stores/photo-388-1.jpg'],
    description: '上海五大古典园林之一，古树参天荷塘清幽',
    targetAudience: ['文化爱好者', '摄影爱好者', '中老年人', '游客'], bestTime: '夏季(荷花)', duration: '1-2小时',
  },
  {
    id: 'sh-189', name: '古猗园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '嘉定区', address: '沪宜公路218号',
    lat: 31.311, lng: 121.316, rating: 4.4, reviewCount: 8000, price: 12,
    openTime: '07:00-17:00', tags: ['园林', '明代', '荷花', '小笼包', '古典'],
    images: ['images/stores/photo-389-1.jpg'],
    description: '上海五大古典园林之一，明代私家园林，夏季荷花展闻名',
    targetAudience: ['游客', '摄影爱好者', '情侣', '亲子'], bestTime: '夏季(荷花展)', duration: '1-2小时',
  },
  {
    id: 'sh-190', name: '秋霞圃', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '嘉定区', address: '东大街314号',
    lat: 31.389, lng: 121.252, rating: 4.2, reviewCount: 3000, price: 10,
    openTime: '07:00-17:00', tags: ['园林', '古典', '安静', '小众', '秋天'],
    images: ['images/stores/photo-390-1.jpg'],
    description: '上海最安静的古典园林，秋日红枫配白墙黑瓦如画',
    targetAudience: ['摄影爱好者', '文化爱好者', '安静', '中老年人'], bestTime: '秋季(红叶)', duration: '1小时',
  },
  {
    id: 'sh-191', name: '曲水园', category: 'attraction', subcategory: '园林景观',
    city: '上海', district: '青浦区', address: '公园路612号',
    lat: 31.159, lng: 121.121, rating: 4.1, reviewCount: 2500, price: 5,
    openTime: '07:00-17:00', tags: ['园林', '水景', '安静', '小巧', '江南'],
    images: ['images/stores/photo-391-1.jpg'],
    description: '上海五大古典园林之一，以水景取胜，小巧而精致',
    targetAudience: ['文化爱好者', '游客', '中老年人', '摄影爱好者'], bestTime: '任何季节', duration: '1小时',
  },
  {
    id: 'sh-192', name: '朱家角古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '青浦区', address: '朱家角镇',
    lat: 31.110, lng: 121.057, rating: 4.5, reviewCount: 20000, price: 0,
    openTime: '全天', tags: ['古镇', '放生桥', '水乡', '小吃', '摇橹船'],
    images: ['images/stores/photo-392-1.jpg'],
    description: '上海保存最好的水乡古镇，放生桥和北大街小吃是亮点',
    targetAudience: ['游客', '摄影爱好者', '情侣', '亲子', '美食爱好者'], bestTime: '春秋两季', duration: '半天至一天',
  },
  {
    id: 'sh-193', name: '七宝古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '闵行区', address: '七宝镇',
    lat: 31.162, lng: 121.353, rating: 4.3, reviewCount: 15000, price: 0,
    openTime: '全天', tags: ['古镇', '小吃', '七宝羊肉', '老街', '离市区近'],
    images: ['images/stores/photo-393-1.jpg'],
    description: '离上海市区最近的水乡古镇，七宝羊肉和汤圆是必吃美食',
    targetAudience: ['游客', '美食爱好者', '家庭', '学生'], bestTime: '周末', duration: '半天',
  },
  {
    id: 'sh-194', name: '枫泾古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '金山区', address: '枫泾镇',
    lat: 30.888, lng: 121.016, rating: 4.2, reviewCount: 6000, price: 0,
    openTime: '全天', tags: ['古镇', '水乡', '丁蹄', '黄酒', '安静'],
    images: ['images/stores/photo-394-1.jpg'],
    description: '上海最西端的江南水乡，枫泾丁蹄和黄酒是特产',
    targetAudience: ['游客', '摄影爱好者', '文化爱好者', '家庭'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-195', name: '新场古镇', category: 'attraction', subcategory: '古镇',
    city: '上海', district: '浦东新区', address: '新场镇',
    lat: 31.051, lng: 121.678, rating: 4.3, reviewCount: 8000, price: 0,
    openTime: '全天', tags: ['古镇', '色戒', '水乡', '安静', '电影取景地'],
    images: ['images/stores/photo-395-1.jpg'],
    description: '《色戒》取景地，比朱家角更安静更原生态的水乡古镇',
    targetAudience: ['摄影爱好者', '游客', '电影爱好者', '情侣'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-196', name: '泰晤士小镇', category: 'attraction', subcategory: '特色街区',
    city: '上海', district: '松江区', address: '三新北路900弄',
    lat: 31.056, lng: 121.192, rating: 4.2, reviewCount: 10000, price: 0,
    openTime: '全天', tags: ['英伦风', '建筑', '拍照', '婚纱', '网红'],
    images: ['images/stores/photo-396-1.jpg'],
    description: '英伦风格小镇，钟书阁和小教堂是最火打卡点',
    targetAudience: ['拍照', '情侣', '婚纱摄影', '网红打卡', '亲子'], bestTime: '下午', duration: '1-2小时',
  },
  {
    id: 'sh-197', name: '上海杜莎夫人蜡像馆', category: 'attraction', subcategory: '娱乐',
    city: '上海', district: '黄浦区', address: '南京西路2号新世界城10楼',
    lat: 31.237, lng: 121.476, rating: 4.3, reviewCount: 20000, price: 190,
    openTime: '10:00-21:30', tags: ['蜡像馆', '名人', '拍照', '互动', '亲子'],
    images: ['images/stores/photo-397-1.jpg'],
    description: '全球第六家杜莎夫人蜡像馆，明星蜡像和漫威英雄互动区',
    targetAudience: ['游客', '亲子', '年轻人', '追星族'], bestTime: '工作日', duration: '2小时',
  },
  {
    id: 'sh-198', name: '上海世博文化公园', category: 'attraction', subcategory: '公园',
    city: '上海', district: '浦东新区', address: '世博大道1750号',
    lat: 31.186, lng: 121.488, rating: 4.5, reviewCount: 10000, price: 0,
    openTime: '06:00-22:00', tags: ['公园', '双子山', '温室', '世博', '新地标'],
    images: ['images/stores/photo-398-1.jpg'],
    description: '世博园区改建的城市公园，有上海市区内第一座人造山',
    targetAudience: ['亲子', '家庭', '年轻人', '市民'], bestTime: '春秋两季', duration: '半天',
  },
  {
    id: 'sh-199', name: '上海邮政博物馆', category: 'attraction', subcategory: '博物馆',
    city: '上海', district: '虹口区', address: '天潼路395号',
    lat: 31.249, lng: 121.490, rating: 4.2, reviewCount: 3000, price: 0,
    openTime: '09:00-17:00(周三/四/六/日开馆)', tags: ['博物馆', '邮政', '建筑', '外滩源', '小众'],
    images: ['images/stores/photo-399-1.jpg'],
    description: '1924年建成的邮政总局大楼，古典建筑和邮政历史展览',
    targetAudience: ['建筑爱好者', '历史爱好者', '游客', '邮票收藏'], bestTime: '周末', duration: '1-2小时',
  },
  {
    id: 'sh-200', name: '上海千古情', category: 'attraction', subcategory: '演出',
    city: '上海', district: '浦东新区', address: '世博大道1750号',
    lat: 31.188, lng: 121.486, rating: 4.5, reviewCount: 12000, price: 298,
    openTime: '演出时间(见排期)', tags: ['演出', '宋城', '歌舞', '上海历史', '视听盛宴'],
    images: ['images/stores/photo-400-1.jpg'],
    description: '宋城演艺打造的上海主题大秀，一小时穿梭上海千年历史',
    targetAudience: ['游客', '家庭', '团队游', '演出爱好者', '亲子'], bestTime: '任何季节', duration: '2小时',
  },
];

// 挂载到全局，兼容 Babel standalone（不支持 ES module）
window.shanghaiPOIs = shanghaiPOIs;
